// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Core(	// @[src/main/core/Core.scala:23:7]
  input         clock,	// @[src/main/core/Core.scala:23:7]
                reset,	// @[src/main/core/Core.scala:23:7]
  output [31:0] io_imem_araddr,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_arvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_imem_arready,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_arid,	// @[src/main/core/Core.scala:24:16]
  output [7:0]  io_imem_arlen,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_imem_arsize,	// @[src/main/core/Core.scala:24:16]
  output [1:0]  io_imem_arburst,	// @[src/main/core/Core.scala:24:16]
  input  [31:0] io_imem_rdata,	// @[src/main/core/Core.scala:24:16]
  input         io_imem_rvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_rready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_imem_awaddr,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_awvalid,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_awid,	// @[src/main/core/Core.scala:24:16]
  output [7:0]  io_imem_awlen,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_imem_awsize,	// @[src/main/core/Core.scala:24:16]
  output [1:0]  io_imem_awburst,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_imem_wdata,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_wstrb,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_wvalid,	// @[src/main/core/Core.scala:24:16]
                io_imem_wlast,	// @[src/main/core/Core.scala:24:16]
                io_imem_bready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_araddr,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_arvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_arready,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_dmem_arsize,	// @[src/main/core/Core.scala:24:16]
  input  [31:0] io_dmem_rdata,	// @[src/main/core/Core.scala:24:16]
  input  [1:0]  io_dmem_rresp,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_rvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_rready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_awaddr,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_awvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_awready,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_dmem_awsize,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_wdata,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_dmem_wstrb,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_wvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_wready,	// @[src/main/core/Core.scala:24:16]
  input  [1:0]  io_dmem_bresp,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_bvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_bready	// @[src/main/core/Core.scala:24:16]
);

  wire        _GEN;	// @[src/main/core/Core.scala:403:{34,56}, :449:22]
  wire        _GEN_0;	// @[src/main/core/Core.scala:402:{34,56}, :449:22]
  wire        _GEN_1;	// @[src/main/core/Core.scala:401:{34,56}, :449:22]
  wire        _icache_io_in_arready;	// @[src/main/core/Core.scala:59:24]
  wire [31:0] _icache_io_in_rdata;	// @[src/main/core/Core.scala:59:24]
  wire        _icache_io_in_rvalid;	// @[src/main/core/Core.scala:59:24]
  wire        _icache_fencei_io_vr_is_fencei_io_ready;	// @[src/main/core/Core.scala:59:24]
  wire [1:0]  _wbu_io_gpr_wen;	// @[src/main/core/Core.scala:33:21]
  wire [3:0]  _wbu_io_gpr_addr;	// @[src/main/core/Core.scala:33:21]
  wire [31:0] _wbu_io_gpr_wdata;	// @[src/main/core/Core.scala:33:21]
  wire [11:0] _wbu_io_csr_addr;	// @[src/main/core/Core.scala:33:21]
  wire [2:0]  _wbu_io_csr_cmd;	// @[src/main/core/Core.scala:33:21]
  wire [31:0] _wbu_io_csr_wdata;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_is_irq;	// @[src/main/core/Core.scala:33:21]
  wire [3:0]  _wbu_io_irq_num;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_irq_valid;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_pipe_in_ready;	// @[src/main/core/Core.scala:33:21]
  wire        _lsu_io_pipe_in_ready;	// @[src/main/core/Core.scala:32:21]
  wire        _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_reg_pc;	// @[src/main/core/Core.scala:32:21]
  wire [3:0]  _lsu_io_pipe_out_bits_ls2wb_wb_addr;	// @[src/main/core/Core.scala:32:21]
  wire [1:0]  _lsu_io_pipe_out_bits_ls2wb_rf_wen;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_wb_data;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:32:21]
  wire [11:0] _lsu_io_pipe_out_bits_ls2wb_csr_addr;	// @[src/main/core/Core.scala:32:21]
  wire [2:0]  _lsu_io_pipe_out_bits_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:32:21]
  wire        _lsu_io_pipe_out_bits_ls2wb_is_irq;	// @[src/main/core/Core.scala:32:21]
  wire [3:0]  _lsu_io_pipe_out_bits_ls2wb_irq_num;	// @[src/main/core/Core.scala:32:21]
  wire        _exu_io_br_flg;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_jmp_flg;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_br_target;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_alu_out;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_in_ready;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_reg_pc;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_op1_data;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_rs2_data;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _exu_io_pipe_out_bits_exe2ls_wb_addr;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_alu_out;	// @[src/main/core/Core.scala:31:21]
  wire [1:0]  _exu_io_pipe_out_bits_exe2ls_rf_wen;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_wb_sel;	// @[src/main/core/Core.scala:31:21]
  wire [11:0] _exu_io_pipe_out_bits_exe2ls_csr_addr;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:31:21]
  wire [1:0]  _exu_io_pipe_out_bits_exe2ls_mem_wen;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_mem_op;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_out_bits_exe2ls_is_irq;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _exu_io_pipe_out_bits_exe2ls_irq_num;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _idu_io_gpr_rs1_addr;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_gpr_rs2_addr;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_gpr_rs1_is_read;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_gpr_rs2_is_read;	// @[src/main/core/Core.scala:30:21]
  wire [11:0] _idu_io_csr_raddr;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_is_mret;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_in_ready;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_reg_pc;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_op1_sel;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_op2_sel;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_rs1_data;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_rs2_data;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_pipe_out_bits_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_rf_wen;	// @[src/main/core/Core.scala:30:21]
  wire [4:0]  _idu_io_pipe_out_bits_id2exe_exe_fun;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_wb_sel;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_imm_sext;	// @[src/main/core/Core.scala:30:21]
  wire [11:0] _idu_io_pipe_out_bits_id2exe_csr_addr;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_csr_cmd;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_mem_wen;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_mem_op;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_out_bits_id2exe_is_irq;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_pipe_out_bits_id2exe_irq_num;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_csr_rdata;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_fencei_io_vr_is_fencei_io_valid;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_fencei_io_vr_is_fencei_io_bits_is_fencei;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _ifu_io_imem_araddr;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_imem_arvalid;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_imem_rready;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_pipe_in_ready;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_pipe_out_bits_if2id_reg_pc;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_pipe_out_bits_if2id_inst;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_hazard_pc_plus4;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _csr_io_csr_mtvec;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _csr_io_csr_mepc;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _csr_io_csr_rdata;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _gpr_io_gpr_rs1_data;	// @[src/main/core/Core.scala:26:21]
  wire [31:0] _gpr_io_gpr_rs2_data;	// @[src/main/core/Core.scala:26:21]
  reg         ready_r;	// @[src/main/core/Core.scala:41:26]
  reg         ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:38]
  reg  [31:0] idu_io_pipe_in_bits_r_if2id_reg_pc;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] idu_io_pipe_in_bits_r_if2id_inst;	// @[src/main/core/Core.scala:448:33]
  reg         idu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:449:34]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_reg_pc;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_op1_sel;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_op2_sel;	// @[src/main/core/Core.scala:448:33]
  reg  [3:0]  exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_rf_wen;	// @[src/main/core/Core.scala:448:33]
  reg  [4:0]  exu_io_pipe_in_bits_r_id2exe_exe_fun;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_wb_sel;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_imm_sext;	// @[src/main/core/Core.scala:448:33]
  reg  [11:0] exu_io_pipe_in_bits_r_id2exe_csr_addr;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_csr_cmd;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_mem_wen;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_mem_op;	// @[src/main/core/Core.scala:448:33]
  reg         exu_io_pipe_in_bits_r_id2exe_is_irq;	// @[src/main/core/Core.scala:448:33]
  reg  [3:0]  exu_io_pipe_in_bits_r_id2exe_irq_num;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_csr_rdata;	// @[src/main/core/Core.scala:448:33]
  reg         exu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:449:34]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_reg_pc;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_op1_data;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_rs2_data;	// @[src/main/core/Core.scala:448:33]
  reg  [3:0]  lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_alu_out;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  lsu_io_pipe_in_bits_r_exe2ls_rf_wen;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_wb_sel;	// @[src/main/core/Core.scala:448:33]
  reg  [11:0] lsu_io_pipe_in_bits_r_exe2ls_csr_addr;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  lsu_io_pipe_in_bits_r_exe2ls_mem_wen;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_mem_op;	// @[src/main/core/Core.scala:448:33]
  reg         lsu_io_pipe_in_bits_r_exe2ls_is_irq;	// @[src/main/core/Core.scala:448:33]
  reg  [3:0]  lsu_io_pipe_in_bits_r_exe2ls_irq_num;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:448:33]
  reg         lsu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:449:34]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_reg_pc;	// @[src/main/core/Core.scala:448:33]
  reg  [3:0]  wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:448:33]
  reg  [1:0]  wbu_io_pipe_in_bits_r_ls2wb_rf_wen;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_wb_data;	// @[src/main/core/Core.scala:448:33]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:448:33]
  reg  [11:0] wbu_io_pipe_in_bits_r_ls2wb_csr_addr;	// @[src/main/core/Core.scala:448:33]
  reg  [2:0]  wbu_io_pipe_in_bits_r_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:448:33]
  reg         wbu_io_pipe_in_bits_r_ls2wb_is_irq;	// @[src/main/core/Core.scala:448:33]
  reg  [3:0]  wbu_io_pipe_in_bits_r_ls2wb_irq_num;	// @[src/main/core/Core.scala:448:33]
  reg         wbu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:449:34]
  wire        exu_is_working = ~_exu_io_pipe_in_ready | _GEN_1;	// @[src/main/core/Core.scala:31:21, :120:{26,48}, :401:{34,56}, :449:22]
  wire        lsu_is_working = ~_lsu_io_pipe_in_ready | _GEN_0;	// @[src/main/core/Core.scala:32:21, :121:{26,48}, :402:{34,56}, :449:22]
  wire        wbu_is_working = ~_wbu_io_pipe_in_ready | _GEN;	// @[src/main/core/Core.scala:33:21, :122:{26,48}, :403:{34,56}, :449:22]
  reg         wbu_end_flg_REG;	// @[src/main/core/Core.scala:123:30]
  wire        wbu_end_flg = wbu_end_flg_REG & ~wbu_is_working;	// @[src/main/core/Core.scala:122:48, :123:{30,47,49}]
  reg         exu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:462:41]
  wire        _exu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33, :452:48]
  wire        _exu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33, :452:48]
  wire        exu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _exu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _exu_raw_rs2_T)
    & exu_is_working & exu_io_pipe_in_bits_r_id2exe_rf_wen == 2'h1
    & exu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:30:21, :120:48, :128:132, :448:33, :452:48, :457:31, :458:31, :462:41, :463:{39,65,97,146}]
  reg         lsu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:462:41]
  wire        _lsu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33, :452:48]
  wire        _lsu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33, :452:48]
  wire        lsu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _lsu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _lsu_raw_rs2_T)
    & lsu_is_working & lsu_io_pipe_in_bits_r_exe2ls_rf_wen == 2'h1
    & lsu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:30:21, :121:48, :128:132, :129:132, :448:33, :452:48, :457:31, :458:31, :462:41, :463:{39,65,97,146}]
  reg         wbu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:462:41]
  wire        _wbu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33, :452:48]
  wire        _wbu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33, :452:48]
  wire        wbu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _wbu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _wbu_raw_rs2_T)
    & wbu_is_working & wbu_io_pipe_in_bits_r_ls2wb_rf_wen == 2'h1
    & wbu_raw_stage_left_valid_r;	// @[src/main/core/Core.scala:30:21, :122:48, :128:132, :130:130, :448:33, :452:48, :457:31, :458:31, :462:41, :463:{39,65,97,146}]
  wire        is_raw = exu_raw | lsu_raw | wbu_raw;	// @[src/main/core/Core.scala:131:37, :463:146]
  wire        exu_raw_rs1 = exu_raw & _exu_raw_rs1_T;	// @[src/main/core/Core.scala:132:31, :452:48, :463:146]
  wire        exu_raw_rs2 = exu_raw & _exu_raw_rs2_T;	// @[src/main/core/Core.scala:133:31, :452:48, :463:146]
  wire        lsu_raw_rs1 = lsu_raw & _lsu_raw_rs1_T;	// @[src/main/core/Core.scala:134:31, :452:48, :463:146]
  wire        lsu_raw_rs2 = lsu_raw & _lsu_raw_rs2_T;	// @[src/main/core/Core.scala:135:31, :452:48, :463:146]
  wire        wbu_raw_rs1 = wbu_raw & _wbu_raw_rs1_T;	// @[src/main/core/Core.scala:136:31, :452:48, :463:146]
  wire        wbu_raw_rs2 = wbu_raw & _wbu_raw_rs2_T;	// @[src/main/core/Core.scala:137:31, :452:48, :463:146]
  wire        rs1_raw = exu_raw_rs1 | lsu_raw_rs1 | wbu_raw_rs1;	// @[src/main/core/Core.scala:132:31, :134:31, :136:31, :138:46]
  wire        rs2_raw = exu_raw_rs2 | lsu_raw_rs2 | wbu_raw_rs2;	// @[src/main/core/Core.scala:133:31, :135:31, :137:31, :139:46]
  reg         exu_rs1_rawing;	// @[src/main/core/Core.scala:157:33]
  reg         exu_rs2_rawing;	// @[src/main/core/Core.scala:158:33]
  reg         lsu_rs1_rawing;	// @[src/main/core/Core.scala:159:33]
  reg         lsu_rs2_rawing;	// @[src/main/core/Core.scala:160:33]
  reg         wbu_rs1_rawing;	// @[src/main/core/Core.scala:161:33]
  reg         wbu_rs2_rawing;	// @[src/main/core/Core.scala:162:33]
  wire        rs1_rawing = exu_rs1_rawing | lsu_rs1_rawing | wbu_rs1_rawing;	// @[src/main/core/Core.scala:157:33, :159:33, :161:33, :169:55]
  wire        rs2_rawing = exu_rs2_rawing | lsu_rs2_rawing | wbu_rs2_rawing;	// @[src/main/core/Core.scala:158:33, :160:33, :162:33, :170:55]
  wire        rawing = rs1_rawing | rs2_rawing;	// @[src/main/core/Core.scala:169:55, :170:55, :171:29]
  reg         bt_fwd_fsh_rs1;	// @[src/main/core/Core.scala:182:33]
  reg         bt_fwd_fsh_rs2;	// @[src/main/core/Core.scala:184:33]
  wire        bt_fwd_fsh = bt_fwd_fsh_rs1 | bt_fwd_fsh_rs2;	// @[src/main/core/Core.scala:182:33, :184:33, :186:37]
  wire        _exu_can_forward_rs1_T = exu_rs1_rawing | exu_raw_rs1;	// @[src/main/core/Core.scala:132:31, :157:33, :192:47]
  wire        _exu_can_forward_rs2_T_1 = exu_io_pipe_in_bits_r_id2exe_wb_sel != 3'h1;	// @[src/main/core/Core.scala:192:101, :448:33]
  wire        exu_can_forward_rs1 = _exu_can_forward_rs1_T & _exu_can_forward_rs2_T_1;	// @[src/main/core/Core.scala:192:{47,63,101}]
  wire        _exu_can_forward_rs2_T = exu_rs2_rawing | exu_raw_rs2;	// @[src/main/core/Core.scala:133:31, :158:33, :193:47]
  wire        exu_can_forward_rs2 = _exu_can_forward_rs2_T & _exu_can_forward_rs2_T_1;	// @[src/main/core/Core.scala:192:101, :193:{47,63}]
  wire        _lsu_can_forward_rs1_T = lsu_rs1_rawing | lsu_raw_rs1;	// @[src/main/core/Core.scala:134:31, :159:33, :194:47]
  wire        _lsu_can_forward_rs2_T_1 = lsu_io_pipe_in_bits_r_exe2ls_wb_sel != 3'h1;	// @[src/main/core/Core.scala:192:101, :194:101, :448:33]
  wire        _lsu_can_forward_rs2_T_2 = _wbu_io_pipe_in_ready & _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21, :33:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        lsu_can_forward_rs1 =
    _lsu_can_forward_rs1_T & (_lsu_can_forward_rs2_T_1 | _lsu_can_forward_rs2_T_2);	// @[src/main/core/Core.scala:194:{47,63,101,112}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _lsu_can_forward_rs2_T = lsu_rs2_rawing | lsu_raw_rs2;	// @[src/main/core/Core.scala:135:31, :160:33, :195:47]
  wire        lsu_can_forward_rs2 =
    _lsu_can_forward_rs2_T & (_lsu_can_forward_rs2_T_1 | _lsu_can_forward_rs2_T_2);	// @[src/main/core/Core.scala:194:101, :195:{47,63,112}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        wbu_can_forward_rs1 = wbu_rs1_rawing | wbu_raw_rs1;	// @[src/main/core/Core.scala:136:31, :161:33, :196:47]
  wire        wbu_can_forward_rs2 = wbu_rs2_rawing | wbu_raw_rs2;	// @[src/main/core/Core.scala:137:31, :162:33, :197:47]
  wire [31:0] exu_forward_data =
    exu_io_pipe_in_bits_r_id2exe_wb_sel == 3'h0
      ? _exu_io_pipe_out_bits_exe2ls_alu_out
      : exu_io_pipe_in_bits_r_id2exe_wb_sel == 3'h3
          ? _exu_io_pipe_out_bits_exe2ls_csr_rdata
          : exu_io_pipe_in_bits_r_id2exe_wb_sel == 3'h2
              ? _exu_io_pipe_out_bits_exe2ls_reg_pc + 32'h4
              : 32'h0;	// @[src/main/core/Core.scala:31:21, :198:77, :199:59, :448:33]
  wire        rd1_forward_en =
    _exu_can_forward_rs1_T
      ? exu_can_forward_rs1 & ~bt_fwd_fsh_rs1
      : _lsu_can_forward_rs1_T
          ? lsu_can_forward_rs1 & ~bt_fwd_fsh_rs1
          : wbu_can_forward_rs1 & wbu_can_forward_rs1 & ~bt_fwd_fsh_rs1;	// @[src/main/core/Core.scala:153:30, :182:33, :192:{47,63}, :194:{47,63}, :196:47, :215:40, :216:{24,47,50}, :217:46, :218:{24,47,50}, :219:46, :220:{24,50}, :222:24]
  wire        rd2_forward_en =
    _exu_can_forward_rs2_T
      ? exu_can_forward_rs2 & ~bt_fwd_fsh_rs2
      : _lsu_can_forward_rs2_T
          ? lsu_can_forward_rs2 & ~bt_fwd_fsh_rs2
          : wbu_can_forward_rs2 & wbu_can_forward_rs2 & ~bt_fwd_fsh_rs2;	// @[src/main/core/Core.scala:154:30, :184:33, :193:{47,63}, :195:{47,63}, :197:47, :224:40, :225:{24,47,50}, :226:46, :227:{24,47,50}, :228:46, :229:{24,50}, :231:24]
  wire [31:0] rd1_forward_data =
    rd1_forward_en
      ? (exu_can_forward_rs1
           ? exu_forward_data
           : lsu_can_forward_rs1
               ? _lsu_io_pipe_out_bits_ls2wb_wb_data
               : wbu_can_forward_rs1 ? _wbu_io_gpr_wdata : 32'h0)
      : _idu_io_pipe_out_bits_id2exe_rs1_data;	// @[src/main/core/Core.scala:30:21, :32:21, :33:21, :153:30, :192:63, :194:63, :196:47, :198:77, :233:31, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [31:0] rd2_forward_data =
    rd2_forward_en
      ? (exu_can_forward_rs2
           ? exu_forward_data
           : lsu_can_forward_rs2
               ? _lsu_io_pipe_out_bits_ls2wb_wb_data
               : wbu_can_forward_rs2 ? _wbu_io_gpr_wdata : 32'h0)
      : _idu_io_pipe_out_bits_id2exe_rs2_data;	// @[src/main/core/Core.scala:30:21, :32:21, :33:21, :154:30, :193:63, :195:63, :197:47, :198:77, :238:31, src/main/scala/chisel3/util/Mux.scala:126:16]
  reg  [31:0] rd1_forward_data_r;	// @[src/main/core/Core.scala:243:39]
  reg  [31:0] rd2_forward_data_r;	// @[src/main/core/Core.scala:244:39]
  reg  [31:0] exu_io_pipe_in_bits_id2exe_rs1_data_r;	// @[src/main/core/Core.scala:252:53]
  reg  [31:0] exu_io_pipe_in_bits_id2exe_rs2_data_r;	// @[src/main/core/Core.scala:253:53]
  reg         is_irq;	// @[src/main/core/Core.scala:361:25]
  reg         is_mret_rise_REG;	// @[src/main/core/Core.scala:367:49]
  wire        is_mret_rise = _idu_io_is_mret & ~is_mret_rise_REG;	// @[src/main/core/Core.scala:30:21, :367:{39,41,49}]
  reg         is_mret_r;	// @[src/main/core/Core.scala:369:28]
  wire        is_ctrl_hazard =
    (_exu_io_br_flg & _exu_io_br_target != _ifu_io_pipe_out_bits_if2id_reg_pc
     | _exu_io_jmp_flg & _exu_io_alu_out != _ifu_io_pipe_out_bits_if2id_reg_pc)
    & _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21, :31:21, :372:{42,62,101,120,138,178}]
  reg         is_ctrl_hazard_r;	// @[src/main/core/Core.scala:375:35]
  reg         is_irq_r;	// @[src/main/core/Core.scala:376:27]
  wire        _idu_io_hazard_flush_flg_T = is_ctrl_hazard | is_irq;	// @[src/main/core/Core.scala:361:25, :372:178, :380:47]
  wire        _GEN_2 = ~_idu_io_hazard_flush_flg_T & ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:{26,38}, :380:47, :399:{34,56}]
  wire        _GEN_3 = ~_idu_io_hazard_flush_flg_T & idu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:26, :380:47, :399:{34,56}, :400:{34,56}, :449:{22,34}]
  assign _GEN_1 = ~is_irq & exu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:361:25, :401:{34,56}, :449:{22,34}]
  assign _GEN_0 = ~is_irq & lsu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:361:25, :401:{34,56}, :402:{34,56}, :449:{22,34}]
  assign _GEN = ~is_irq & wbu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:361:25, :401:{34,56}, :403:{34,56}, :449:{22,34}]
  wire        _wbu_rs2_rawing_T = rd1_forward_en | rd2_forward_en;	// @[src/main/core/Core.scala:153:30, :154:30, :163:42]
  wire        _is_irq_r_T = _ifu_io_pipe_in_ready & _GEN_2;	// @[src/main/core/Core.scala:29:21, :42:26, :370:69, :399:{34,56}]
  wire        _exu_io_pipe_in_bits_id2exe_rs2_data_T_5 =
    _exu_io_pipe_in_ready & _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21, :31:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[src/main/core/Core.scala:23:7]
    ready_r <= _ifu_io_pipe_in_ready;	// @[src/main/core/Core.scala:29:21, :41:26]
    if (_ifu_io_pipe_out_valid & _idu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:29:21, :30:21, :448:62]
      idu_io_pipe_in_bits_r_if2id_reg_pc <= _ifu_io_pipe_out_bits_if2id_reg_pc;	// @[src/main/core/Core.scala:29:21, :448:33]
      idu_io_pipe_in_bits_r_if2id_inst <= _ifu_io_pipe_out_bits_if2id_inst;	// @[src/main/core/Core.scala:29:21, :448:33]
    end
    if (_idu_io_pipe_in_ready)	// @[src/main/core/Core.scala:30:21]
      idu_io_pipe_in_valid_r <= _ifu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21, :449:34]
    if (_idu_io_pipe_out_valid & _exu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:30:21, :31:21, :448:62]
      exu_io_pipe_in_bits_r_id2exe_reg_pc <= _idu_io_pipe_out_bits_id2exe_reg_pc;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_op1_sel <= _idu_io_pipe_out_bits_id2exe_op1_sel;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_op2_sel <= _idu_io_pipe_out_bits_id2exe_op2_sel;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_wb_addr <= _idu_io_pipe_out_bits_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_rf_wen <= _idu_io_pipe_out_bits_id2exe_rf_wen;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_exe_fun <= _idu_io_pipe_out_bits_id2exe_exe_fun;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_wb_sel <= _idu_io_pipe_out_bits_id2exe_wb_sel;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_imm_sext <= _idu_io_pipe_out_bits_id2exe_imm_sext;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_csr_addr <= _idu_io_pipe_out_bits_id2exe_csr_addr;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_csr_cmd <= _idu_io_pipe_out_bits_id2exe_csr_cmd;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_mem_wen <= _idu_io_pipe_out_bits_id2exe_mem_wen;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_mem_op <= _idu_io_pipe_out_bits_id2exe_mem_op;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_is_irq <= _idu_io_pipe_out_bits_id2exe_is_irq;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_irq_num <= _idu_io_pipe_out_bits_id2exe_irq_num;	// @[src/main/core/Core.scala:30:21, :448:33]
      exu_io_pipe_in_bits_r_id2exe_csr_rdata <= _idu_io_pipe_out_bits_id2exe_csr_rdata;	// @[src/main/core/Core.scala:30:21, :448:33]
    end
    if (_exu_io_pipe_in_ready)	// @[src/main/core/Core.scala:31:21]
      exu_io_pipe_in_valid_r <= _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21, :449:34]
    if (_exu_io_pipe_out_valid & _lsu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:31:21, :32:21, :448:62]
      lsu_io_pipe_in_bits_r_exe2ls_reg_pc <= _exu_io_pipe_out_bits_exe2ls_reg_pc;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_op1_data <= _exu_io_pipe_out_bits_exe2ls_op1_data;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_rs2_data <= _exu_io_pipe_out_bits_exe2ls_rs2_data;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_wb_addr <= _exu_io_pipe_out_bits_exe2ls_wb_addr;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_alu_out <= _exu_io_pipe_out_bits_exe2ls_alu_out;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_rf_wen <= _exu_io_pipe_out_bits_exe2ls_rf_wen;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_wb_sel <= _exu_io_pipe_out_bits_exe2ls_wb_sel;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_addr <= _exu_io_pipe_out_bits_exe2ls_csr_addr;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_cmd <= _exu_io_pipe_out_bits_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_mem_wen <= _exu_io_pipe_out_bits_exe2ls_mem_wen;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_mem_op <= _exu_io_pipe_out_bits_exe2ls_mem_op;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_is_irq <= _exu_io_pipe_out_bits_exe2ls_is_irq;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_irq_num <= _exu_io_pipe_out_bits_exe2ls_irq_num;	// @[src/main/core/Core.scala:31:21, :448:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_rdata <= _exu_io_pipe_out_bits_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:31:21, :448:33]
    end
    if (_lsu_io_pipe_in_ready)	// @[src/main/core/Core.scala:32:21]
      lsu_io_pipe_in_valid_r <= _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21, :449:34]
    if (_lsu_io_pipe_out_valid & _wbu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:32:21, :33:21, :448:62]
      wbu_io_pipe_in_bits_r_ls2wb_reg_pc <= _lsu_io_pipe_out_bits_ls2wb_reg_pc;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_wb_addr <= _lsu_io_pipe_out_bits_ls2wb_wb_addr;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_rf_wen <= _lsu_io_pipe_out_bits_ls2wb_rf_wen;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_wb_data <= _lsu_io_pipe_out_bits_ls2wb_wb_data;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_wdata <= _lsu_io_pipe_out_bits_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_addr <= _lsu_io_pipe_out_bits_ls2wb_csr_addr;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_cmd <= _lsu_io_pipe_out_bits_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_is_irq <= _lsu_io_pipe_out_bits_ls2wb_is_irq;	// @[src/main/core/Core.scala:32:21, :448:33]
      wbu_io_pipe_in_bits_r_ls2wb_irq_num <= _lsu_io_pipe_out_bits_ls2wb_irq_num;	// @[src/main/core/Core.scala:32:21, :448:33]
    end
    if (_wbu_io_pipe_in_ready)	// @[src/main/core/Core.scala:33:21]
      wbu_io_pipe_in_valid_r <= _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21, :449:34]
    wbu_end_flg_REG <= wbu_is_working;	// @[src/main/core/Core.scala:122:48, :123:30]
    exu_raw_stage_left_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:400:{34,56}, :449:22, :462:41]
    lsu_raw_stage_left_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:400:{34,56}, :449:22, :462:41]
    wbu_raw_stage_left_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:400:{34,56}, :449:22, :462:41]
    if (rd1_forward_en)	// @[src/main/core/Core.scala:153:30]
      rd1_forward_data_r <= rd1_forward_data;	// @[src/main/core/Core.scala:233:31, :243:39]
    if (rd2_forward_en)	// @[src/main/core/Core.scala:154:30]
      rd2_forward_data_r <= rd2_forward_data;	// @[src/main/core/Core.scala:238:31, :244:39]
    if (_exu_io_pipe_in_bits_id2exe_rs2_data_T_5) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      exu_io_pipe_in_bits_id2exe_rs1_data_r <=
        rd1_forward_en | ~rs1_rawing & ~bt_fwd_fsh_rs1
          ? rd1_forward_data
          : rd1_forward_data_r;	// @[src/main/core/Core.scala:153:30, :169:55, :182:33, :233:31, :243:39, :252:{53,57,73,77,89,92}]
      exu_io_pipe_in_bits_id2exe_rs2_data_r <=
        rd2_forward_en | ~rs2_rawing & ~bt_fwd_fsh_rs2
          ? rd2_forward_data
          : rd2_forward_data_r;	// @[src/main/core/Core.scala:154:30, :170:55, :184:33, :238:31, :244:39, :253:{53,57,73,77,89,92}]
    end
    is_irq <= _wbu_io_irq_valid & _wbu_io_is_irq;	// @[src/main/core/Core.scala:33:21, :361:{25,43}]
    is_mret_rise_REG <= _idu_io_is_mret;	// @[src/main/core/Core.scala:30:21, :367:49]
    if (reset) begin	// @[src/main/core/Core.scala:23:7]
      ifu_io_pipe_in_valid_r <= _GEN_2;	// @[src/main/core/Core.scala:42:{26,38}, :399:{34,56}]
      exu_rs1_rawing <= 1'h0;	// @[src/main/core/Core.scala:157:33, :457:31]
      exu_rs2_rawing <= 1'h0;	// @[src/main/core/Core.scala:158:33, :457:31]
      lsu_rs1_rawing <= 1'h0;	// @[src/main/core/Core.scala:159:33, :457:31]
      lsu_rs2_rawing <= 1'h0;	// @[src/main/core/Core.scala:160:33, :457:31]
      wbu_rs1_rawing <= 1'h0;	// @[src/main/core/Core.scala:161:33, :457:31]
      wbu_rs2_rawing <= 1'h0;	// @[src/main/core/Core.scala:162:33, :457:31]
      bt_fwd_fsh_rs1 <= 1'h0;	// @[src/main/core/Core.scala:182:33, :457:31]
      bt_fwd_fsh_rs2 <= 1'h0;	// @[src/main/core/Core.scala:184:33, :457:31]
      is_mret_r <= 1'h0;	// @[src/main/core/Core.scala:369:28, :457:31]
      is_ctrl_hazard_r <= 1'h0;	// @[src/main/core/Core.scala:375:35, :457:31]
      is_irq_r <= 1'h0;	// @[src/main/core/Core.scala:376:27, :457:31]
    end
    else begin	// @[src/main/core/Core.scala:23:7]
      ifu_io_pipe_in_valid_r <= _ifu_io_pipe_in_ready & ready_r | ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:29:21, :41:26, :42:{38,90}]
      exu_rs1_rawing <= ~_wbu_rs2_rawing_T & (exu_raw_rs1 | exu_rs1_rawing);	// @[src/main/core/Core.scala:132:31, :157:33, :163:{26,42,72}]
      exu_rs2_rawing <= ~_wbu_rs2_rawing_T & (exu_raw_rs2 | exu_rs2_rawing);	// @[src/main/core/Core.scala:133:31, :158:33, :163:{26,42}, :164:{26,72}]
      lsu_rs1_rawing <= ~_wbu_rs2_rawing_T & (lsu_raw_rs1 | lsu_rs1_rawing);	// @[src/main/core/Core.scala:134:31, :159:33, :163:{26,42}, :165:{26,72}]
      lsu_rs2_rawing <= ~_wbu_rs2_rawing_T & (lsu_raw_rs2 | lsu_rs2_rawing);	// @[src/main/core/Core.scala:135:31, :160:33, :163:{26,42}, :166:{26,72}]
      wbu_rs1_rawing <= ~_wbu_rs2_rawing_T & (wbu_raw_rs1 | wbu_rs1_rawing);	// @[src/main/core/Core.scala:136:31, :161:33, :163:{26,42}, :167:{26,72}]
      wbu_rs2_rawing <= ~_wbu_rs2_rawing_T & (wbu_raw_rs2 | wbu_rs2_rawing);	// @[src/main/core/Core.scala:137:31, :162:33, :163:{26,42}, :168:{26,72}]
      bt_fwd_fsh_rs1 <=
        ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_5 & (rd1_forward_en | bt_fwd_fsh_rs1);	// @[src/main/core/Core.scala:153:30, :182:33, :183:{26,61}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      bt_fwd_fsh_rs2 <=
        ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_5 & (rd2_forward_en | bt_fwd_fsh_rs2);	// @[src/main/core/Core.scala:154:30, :183:26, :184:33, :185:{26,61}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      is_mret_r <= is_mret_rise | ~_is_irq_r_T & is_mret_r;	// @[src/main/core/Core.scala:367:39, :369:28, :370:{21,47,69}]
      is_ctrl_hazard_r <= is_ctrl_hazard | ~_is_irq_r_T & is_ctrl_hazard_r;	// @[src/main/core/Core.scala:370:{47,69}, :372:178, :375:35, :377:{28,56}]
      is_irq_r <= is_irq | ~_is_irq_r_T & is_irq_r;	// @[src/main/core/Core.scala:361:25, :370:{47,69}, :376:27, :378:{20,40}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/Core.scala:23:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/Core.scala:23:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/Core.scala:23:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:23];	// @[src/main/core/Core.scala:23:7]
    initial begin	// @[src/main/core/Core.scala:23:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/Core.scala:23:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/Core.scala:23:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/Core.scala:23:7]
        for (logic [4:0] i = 5'h0; i < 5'h18; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/core/Core.scala:23:7]
        end	// @[src/main/core/Core.scala:23:7]
        ready_r = _RANDOM[5'h0][0];	// @[src/main/core/Core.scala:23:7, :41:26]
        ifu_io_pipe_in_valid_r = _RANDOM[5'h0][1];	// @[src/main/core/Core.scala:23:7, :41:26, :42:38]
        idu_io_pipe_in_bits_r_if2id_reg_pc = {_RANDOM[5'h0][31:2], _RANDOM[5'h1][1:0]};	// @[src/main/core/Core.scala:23:7, :41:26, :448:33]
        idu_io_pipe_in_bits_r_if2id_inst = {_RANDOM[5'h1][31:2], _RANDOM[5'h2][1:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        idu_io_pipe_in_valid_r = _RANDOM[5'h2][2];	// @[src/main/core/Core.scala:23:7, :448:33, :449:34]
        exu_io_pipe_in_bits_r_id2exe_reg_pc = {_RANDOM[5'h2][31:3], _RANDOM[5'h3][2:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_op1_sel = _RANDOM[5'h3][4:3];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_op2_sel = _RANDOM[5'h3][6:5];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_wb_addr = _RANDOM[5'h5][10:7];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_rf_wen = _RANDOM[5'h5][12:11];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_exe_fun = _RANDOM[5'h5][17:13];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_wb_sel = _RANDOM[5'h5][20:18];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_imm_sext =
          {_RANDOM[5'h5][31:21], _RANDOM[5'h6][20:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_csr_addr = {_RANDOM[5'h6][31:21], _RANDOM[5'h7][0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_csr_cmd = _RANDOM[5'h7][3:1];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_mem_wen = _RANDOM[5'h7][5:4];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_mem_op = _RANDOM[5'h7][8:6];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_is_irq = _RANDOM[5'h7][9];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_irq_num = _RANDOM[5'h7][13:10];	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_bits_r_id2exe_csr_rdata =
          {_RANDOM[5'h7][31:14], _RANDOM[5'h8][13:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        exu_io_pipe_in_valid_r = _RANDOM[5'h8][14];	// @[src/main/core/Core.scala:23:7, :448:33, :449:34]
        lsu_io_pipe_in_bits_r_exe2ls_reg_pc = {_RANDOM[5'h8][31:15], _RANDOM[5'h9][14:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_op1_data =
          {_RANDOM[5'h9][31:15], _RANDOM[5'hA][14:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_rs2_data =
          {_RANDOM[5'hA][31:15], _RANDOM[5'hB][14:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_wb_addr = _RANDOM[5'hB][18:15];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_alu_out =
          {_RANDOM[5'hB][31:19], _RANDOM[5'hC][18:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_rf_wen = _RANDOM[5'hC][20:19];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_wb_sel = _RANDOM[5'hC][23:21];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_addr =
          {_RANDOM[5'hC][31:24], _RANDOM[5'hD][3:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_cmd = _RANDOM[5'hD][6:4];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_mem_wen = _RANDOM[5'hD][8:7];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_mem_op = _RANDOM[5'hD][11:9];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_is_irq = _RANDOM[5'hD][12];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_irq_num = _RANDOM[5'hD][16:13];	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_rdata =
          {_RANDOM[5'hD][31:17], _RANDOM[5'hE][16:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        lsu_io_pipe_in_valid_r = _RANDOM[5'hE][17];	// @[src/main/core/Core.scala:23:7, :448:33, :449:34]
        wbu_io_pipe_in_bits_r_ls2wb_reg_pc = {_RANDOM[5'hE][31:18], _RANDOM[5'hF][17:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_wb_addr = _RANDOM[5'hF][21:18];	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_rf_wen = _RANDOM[5'hF][23:22];	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_wb_data =
          {_RANDOM[5'hF][31:24], _RANDOM[5'h10][23:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_wdata =
          {_RANDOM[5'h10][31:24], _RANDOM[5'h11][23:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_addr =
          {_RANDOM[5'h11][31:24], _RANDOM[5'h12][3:0]};	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_cmd = _RANDOM[5'h12][6:4];	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_is_irq = _RANDOM[5'h12][7];	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_bits_r_ls2wb_irq_num = _RANDOM[5'h12][11:8];	// @[src/main/core/Core.scala:23:7, :448:33]
        wbu_io_pipe_in_valid_r = _RANDOM[5'h12][12];	// @[src/main/core/Core.scala:23:7, :448:33, :449:34]
        wbu_end_flg_REG = _RANDOM[5'h12][13];	// @[src/main/core/Core.scala:23:7, :123:30, :448:33]
        exu_raw_stage_left_valid_r = _RANDOM[5'h12][14];	// @[src/main/core/Core.scala:23:7, :448:33, :462:41]
        lsu_raw_stage_left_valid_r = _RANDOM[5'h12][15];	// @[src/main/core/Core.scala:23:7, :448:33, :462:41]
        wbu_raw_stage_left_valid_r = _RANDOM[5'h12][16];	// @[src/main/core/Core.scala:23:7, :448:33, :462:41]
        exu_rs1_rawing = _RANDOM[5'h12][17];	// @[src/main/core/Core.scala:23:7, :157:33, :448:33]
        exu_rs2_rawing = _RANDOM[5'h12][18];	// @[src/main/core/Core.scala:23:7, :158:33, :448:33]
        lsu_rs1_rawing = _RANDOM[5'h12][19];	// @[src/main/core/Core.scala:23:7, :159:33, :448:33]
        lsu_rs2_rawing = _RANDOM[5'h12][20];	// @[src/main/core/Core.scala:23:7, :160:33, :448:33]
        wbu_rs1_rawing = _RANDOM[5'h12][21];	// @[src/main/core/Core.scala:23:7, :161:33, :448:33]
        wbu_rs2_rawing = _RANDOM[5'h12][22];	// @[src/main/core/Core.scala:23:7, :162:33, :448:33]
        bt_fwd_fsh_rs1 = _RANDOM[5'h12][23];	// @[src/main/core/Core.scala:23:7, :182:33, :448:33]
        bt_fwd_fsh_rs2 = _RANDOM[5'h12][24];	// @[src/main/core/Core.scala:23:7, :184:33, :448:33]
        rd1_forward_data_r = {_RANDOM[5'h12][31:25], _RANDOM[5'h13][24:0]};	// @[src/main/core/Core.scala:23:7, :243:39, :448:33]
        rd2_forward_data_r = {_RANDOM[5'h13][31:25], _RANDOM[5'h14][24:0]};	// @[src/main/core/Core.scala:23:7, :243:39, :244:39]
        exu_io_pipe_in_bits_id2exe_rs1_data_r =
          {_RANDOM[5'h14][31:25], _RANDOM[5'h15][24:0]};	// @[src/main/core/Core.scala:23:7, :244:39, :252:53]
        exu_io_pipe_in_bits_id2exe_rs2_data_r =
          {_RANDOM[5'h15][31:25], _RANDOM[5'h16][24:0]};	// @[src/main/core/Core.scala:23:7, :252:53, :253:53]
        is_irq = _RANDOM[5'h17][11];	// @[src/main/core/Core.scala:23:7, :361:25]
        is_mret_rise_REG = _RANDOM[5'h17][12];	// @[src/main/core/Core.scala:23:7, :361:25, :367:49]
        is_mret_r = _RANDOM[5'h17][13];	// @[src/main/core/Core.scala:23:7, :361:25, :369:28]
        is_ctrl_hazard_r = _RANDOM[5'h17][14];	// @[src/main/core/Core.scala:23:7, :361:25, :375:35]
        is_irq_r = _RANDOM[5'h17][15];	// @[src/main/core/Core.scala:23:7, :361:25, :376:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/Core.scala:23:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/Core.scala:23:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  GPR gpr (	// @[src/main/core/Core.scala:26:21]
    .clock           (clock),
    .reset           (reset),
    .io_gpr_rs1_addr (_idu_io_gpr_rs1_addr),	// @[src/main/core/Core.scala:30:21]
    .io_gpr_rs2_addr (_idu_io_gpr_rs2_addr),	// @[src/main/core/Core.scala:30:21]
    .io_gpr_rs1_data (_gpr_io_gpr_rs1_data),
    .io_gpr_rs2_data (_gpr_io_gpr_rs2_data),
    .io_gpr_wen      (_wbu_io_gpr_wen),	// @[src/main/core/Core.scala:33:21]
    .io_gpr_addr     (_wbu_io_gpr_addr),	// @[src/main/core/Core.scala:33:21]
    .io_gpr_wdata    (_wbu_io_gpr_wdata)	// @[src/main/core/Core.scala:33:21]
  );
  CSR csr (	// @[src/main/core/Core.scala:27:21]
    .clock          (clock),
    .reset          (reset),
    .io_csr_mtvec   (_csr_io_csr_mtvec),
    .io_csr_mepc    (_csr_io_csr_mepc),
    .io_csr_rdata   (_csr_io_csr_rdata),
    .io_csr_wdata   (_wbu_io_csr_wdata),	// @[src/main/core/Core.scala:33:21]
    .io_csr_addr    (_wbu_io_csr_addr),	// @[src/main/core/Core.scala:33:21]
    .io_csr_cmd     (_wbu_io_csr_cmd),	// @[src/main/core/Core.scala:33:21]
    .io_csr_raddr   (_idu_io_csr_raddr),	// @[src/main/core/Core.scala:30:21]
    .io_csr_reg_pc  (wbu_io_pipe_in_bits_r_ls2wb_reg_pc),	// @[src/main/core/Core.scala:448:33]
    .io_csr_irq_num (_wbu_io_irq_num),	// @[src/main/core/Core.scala:33:21]
    .io_csr_is_irq  (is_irq)	// @[src/main/core/Core.scala:361:25]
  );
  IFU ifu (	// @[src/main/core/Core.scala:29:21]
    .clock                         (clock),
    .reset                         (reset),
    .io_imem_araddr                (_ifu_io_imem_araddr),
    .io_imem_arvalid               (_ifu_io_imem_arvalid),
    .io_imem_arready               (_icache_io_in_arready),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rdata                 (_icache_io_in_rdata),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rvalid                (_icache_io_in_rvalid),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rready                (_ifu_io_imem_rready),
    .io_pipe_in_ready              (_ifu_io_pipe_in_ready),
    .io_pipe_in_valid              (_GEN_2),	// @[src/main/core/Core.scala:42:26, :399:{34,56}]
    .io_pipe_out_ready             (_idu_io_pipe_in_ready),	// @[src/main/core/Core.scala:30:21]
    .io_pipe_out_valid             (_ifu_io_pipe_out_valid),
    .io_pipe_out_bits_if2id_reg_pc (_ifu_io_pipe_out_bits_if2id_reg_pc),
    .io_pipe_out_bits_if2id_inst   (_ifu_io_pipe_out_bits_if2id_inst),
    .io_hazard_flush_flg           (_idu_io_hazard_flush_flg_T),	// @[src/main/core/Core.scala:380:47]
    .io_hazard_pc_plus4            (_ifu_io_hazard_pc_plus4),
    .io_hazard_pc_real_next
      (is_irq_r
         ? _csr_io_csr_mtvec
         : is_ctrl_hazard_r | is_mret_r
             ? (_exu_io_br_flg ? _exu_io_br_target : 32'h0)
               | (_exu_io_jmp_flg ? _exu_io_alu_out : 32'h0)
               | (_idu_io_is_mret ? _csr_io_csr_mepc : 32'h0)
             : _ifu_io_hazard_pc_plus4),	// @[src/main/core/Core.scala:27:21, :29:21, :30:21, :31:21, :198:77, :369:28, :375:35, :376:27, :395:{27,59,77}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_hazard_is_mret_rise        (is_mret_rise)	// @[src/main/core/Core.scala:367:39]
  );
  IDU idu (	// @[src/main/core/Core.scala:30:21]
    .clock                                    (clock),
    .reset                                    (reset),
    .io_gpr_rs1_addr                          (_idu_io_gpr_rs1_addr),
    .io_gpr_rs2_addr                          (_idu_io_gpr_rs2_addr),
    .io_gpr_rs1_data                          (_gpr_io_gpr_rs1_data),	// @[src/main/core/Core.scala:26:21]
    .io_gpr_rs2_data                          (_gpr_io_gpr_rs2_data),	// @[src/main/core/Core.scala:26:21]
    .io_gpr_rs1_is_read                       (_idu_io_gpr_rs1_is_read),
    .io_gpr_rs2_is_read                       (_idu_io_gpr_rs2_is_read),
    .io_csr_raddr                             (_idu_io_csr_raddr),
    .io_csr_rdata                             (_csr_io_csr_rdata),	// @[src/main/core/Core.scala:27:21]
    .io_is_mret                               (_idu_io_is_mret),
    .io_pipe_in_ready                         (_idu_io_pipe_in_ready),
    .io_pipe_in_valid                         (_GEN_3),	// @[src/main/core/Core.scala:400:{34,56}, :449:22]
    .io_pipe_in_bits_if2id_reg_pc             (idu_io_pipe_in_bits_r_if2id_reg_pc),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_if2id_inst               (idu_io_pipe_in_bits_r_if2id_inst),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_out_ready                        (_exu_io_pipe_in_ready),	// @[src/main/core/Core.scala:31:21]
    .io_pipe_out_valid                        (_idu_io_pipe_out_valid),
    .io_pipe_out_bits_id2exe_reg_pc           (_idu_io_pipe_out_bits_id2exe_reg_pc),
    .io_pipe_out_bits_id2exe_op1_sel          (_idu_io_pipe_out_bits_id2exe_op1_sel),
    .io_pipe_out_bits_id2exe_op2_sel          (_idu_io_pipe_out_bits_id2exe_op2_sel),
    .io_pipe_out_bits_id2exe_rs1_data         (_idu_io_pipe_out_bits_id2exe_rs1_data),
    .io_pipe_out_bits_id2exe_rs2_data         (_idu_io_pipe_out_bits_id2exe_rs2_data),
    .io_pipe_out_bits_id2exe_wb_addr          (_idu_io_pipe_out_bits_id2exe_wb_addr),
    .io_pipe_out_bits_id2exe_rf_wen           (_idu_io_pipe_out_bits_id2exe_rf_wen),
    .io_pipe_out_bits_id2exe_exe_fun          (_idu_io_pipe_out_bits_id2exe_exe_fun),
    .io_pipe_out_bits_id2exe_wb_sel           (_idu_io_pipe_out_bits_id2exe_wb_sel),
    .io_pipe_out_bits_id2exe_imm_sext         (_idu_io_pipe_out_bits_id2exe_imm_sext),
    .io_pipe_out_bits_id2exe_csr_addr         (_idu_io_pipe_out_bits_id2exe_csr_addr),
    .io_pipe_out_bits_id2exe_csr_cmd          (_idu_io_pipe_out_bits_id2exe_csr_cmd),
    .io_pipe_out_bits_id2exe_mem_wen          (_idu_io_pipe_out_bits_id2exe_mem_wen),
    .io_pipe_out_bits_id2exe_mem_op           (_idu_io_pipe_out_bits_id2exe_mem_op),
    .io_pipe_out_bits_id2exe_is_irq           (_idu_io_pipe_out_bits_id2exe_is_irq),
    .io_pipe_out_bits_id2exe_irq_num          (_idu_io_pipe_out_bits_id2exe_irq_num),
    .io_pipe_out_bits_id2exe_csr_rdata        (_idu_io_pipe_out_bits_id2exe_csr_rdata),
    .fencei_io_vr_is_fencei_io_ready          (_icache_fencei_io_vr_is_fencei_io_ready),	// @[src/main/core/Core.scala:59:24]
    .fencei_io_vr_is_fencei_io_valid          (_idu_fencei_io_vr_is_fencei_io_valid),
    .fencei_io_vr_is_fencei_io_bits_is_fencei
      (_idu_fencei_io_vr_is_fencei_io_bits_is_fencei),
    .io_hazard_stall_flg
      ((is_raw | rawing) & ~rd1_forward_en & ~rd2_forward_en & ~bt_fwd_fsh)	// @[src/main/core/Core.scala:131:37, :153:30, :154:30, :171:29, :186:37, :254:{40,51,55,74,93}]
  );
  EXU exu (	// @[src/main/core/Core.scala:31:21]
    .clock                             (clock),
    .reset                             (reset),
    .io_br_flg                         (_exu_io_br_flg),
    .io_jmp_flg                        (_exu_io_jmp_flg),
    .io_br_target                      (_exu_io_br_target),
    .io_alu_out                        (_exu_io_alu_out),
    .io_pipe_in_ready                  (_exu_io_pipe_in_ready),
    .io_pipe_in_valid                  (_GEN_1),	// @[src/main/core/Core.scala:401:{34,56}, :449:22]
    .io_pipe_in_bits_id2exe_reg_pc     (exu_io_pipe_in_bits_r_id2exe_reg_pc),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_op1_sel    (exu_io_pipe_in_bits_r_id2exe_op1_sel),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_op2_sel    (exu_io_pipe_in_bits_r_id2exe_op2_sel),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_rs1_data   (exu_io_pipe_in_bits_id2exe_rs1_data_r),	// @[src/main/core/Core.scala:252:53]
    .io_pipe_in_bits_id2exe_rs2_data   (exu_io_pipe_in_bits_id2exe_rs2_data_r),	// @[src/main/core/Core.scala:253:53]
    .io_pipe_in_bits_id2exe_wb_addr    (exu_io_pipe_in_bits_r_id2exe_wb_addr),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_rf_wen     (exu_io_pipe_in_bits_r_id2exe_rf_wen),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_exe_fun    (exu_io_pipe_in_bits_r_id2exe_exe_fun),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_wb_sel     (exu_io_pipe_in_bits_r_id2exe_wb_sel),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_imm_sext   (exu_io_pipe_in_bits_r_id2exe_imm_sext),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_csr_addr   (exu_io_pipe_in_bits_r_id2exe_csr_addr),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_csr_cmd    (exu_io_pipe_in_bits_r_id2exe_csr_cmd),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_mem_wen    (exu_io_pipe_in_bits_r_id2exe_mem_wen),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_mem_op     (exu_io_pipe_in_bits_r_id2exe_mem_op),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_is_irq     (exu_io_pipe_in_bits_r_id2exe_is_irq),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_irq_num    (exu_io_pipe_in_bits_r_id2exe_irq_num),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_id2exe_csr_rdata  (exu_io_pipe_in_bits_r_id2exe_csr_rdata),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_out_ready                 (_lsu_io_pipe_in_ready),	// @[src/main/core/Core.scala:32:21]
    .io_pipe_out_valid                 (_exu_io_pipe_out_valid),
    .io_pipe_out_bits_exe2ls_reg_pc    (_exu_io_pipe_out_bits_exe2ls_reg_pc),
    .io_pipe_out_bits_exe2ls_op1_data  (_exu_io_pipe_out_bits_exe2ls_op1_data),
    .io_pipe_out_bits_exe2ls_rs2_data  (_exu_io_pipe_out_bits_exe2ls_rs2_data),
    .io_pipe_out_bits_exe2ls_wb_addr   (_exu_io_pipe_out_bits_exe2ls_wb_addr),
    .io_pipe_out_bits_exe2ls_alu_out   (_exu_io_pipe_out_bits_exe2ls_alu_out),
    .io_pipe_out_bits_exe2ls_rf_wen    (_exu_io_pipe_out_bits_exe2ls_rf_wen),
    .io_pipe_out_bits_exe2ls_wb_sel    (_exu_io_pipe_out_bits_exe2ls_wb_sel),
    .io_pipe_out_bits_exe2ls_csr_addr  (_exu_io_pipe_out_bits_exe2ls_csr_addr),
    .io_pipe_out_bits_exe2ls_csr_cmd   (_exu_io_pipe_out_bits_exe2ls_csr_cmd),
    .io_pipe_out_bits_exe2ls_mem_wen   (_exu_io_pipe_out_bits_exe2ls_mem_wen),
    .io_pipe_out_bits_exe2ls_mem_op    (_exu_io_pipe_out_bits_exe2ls_mem_op),
    .io_pipe_out_bits_exe2ls_is_irq    (_exu_io_pipe_out_bits_exe2ls_is_irq),
    .io_pipe_out_bits_exe2ls_irq_num   (_exu_io_pipe_out_bits_exe2ls_irq_num),
    .io_pipe_out_bits_exe2ls_csr_rdata (_exu_io_pipe_out_bits_exe2ls_csr_rdata),
    .io_hazard_flush_flg               (is_irq)	// @[src/main/core/Core.scala:361:25]
  );
  LSU lsu (	// @[src/main/core/Core.scala:32:21]
    .clock                            (clock),
    .reset                            (reset),
    .io_dmem_araddr                   (io_dmem_araddr),
    .io_dmem_arvalid                  (io_dmem_arvalid),
    .io_dmem_arready                  (io_dmem_arready),
    .io_dmem_arsize                   (io_dmem_arsize),
    .io_dmem_rdata                    (io_dmem_rdata),
    .io_dmem_rresp                    (io_dmem_rresp),
    .io_dmem_rvalid                   (io_dmem_rvalid),
    .io_dmem_rready                   (io_dmem_rready),
    .io_dmem_awaddr                   (io_dmem_awaddr),
    .io_dmem_awvalid                  (io_dmem_awvalid),
    .io_dmem_awready                  (io_dmem_awready),
    .io_dmem_awsize                   (io_dmem_awsize),
    .io_dmem_wdata                    (io_dmem_wdata),
    .io_dmem_wstrb                    (io_dmem_wstrb),
    .io_dmem_wvalid                   (io_dmem_wvalid),
    .io_dmem_wready                   (io_dmem_wready),
    .io_dmem_bresp                    (io_dmem_bresp),
    .io_dmem_bvalid                   (io_dmem_bvalid),
    .io_dmem_bready                   (io_dmem_bready),
    .io_pipe_in_ready                 (_lsu_io_pipe_in_ready),
    .io_pipe_in_valid                 (_GEN_0),	// @[src/main/core/Core.scala:402:{34,56}, :449:22]
    .io_pipe_in_bits_exe2ls_reg_pc    (lsu_io_pipe_in_bits_r_exe2ls_reg_pc),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_op1_data  (lsu_io_pipe_in_bits_r_exe2ls_op1_data),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_rs2_data  (lsu_io_pipe_in_bits_r_exe2ls_rs2_data),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_wb_addr   (lsu_io_pipe_in_bits_r_exe2ls_wb_addr),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_alu_out   (lsu_io_pipe_in_bits_r_exe2ls_alu_out),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_rf_wen    (lsu_io_pipe_in_bits_r_exe2ls_rf_wen),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_wb_sel    (lsu_io_pipe_in_bits_r_exe2ls_wb_sel),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_csr_addr  (lsu_io_pipe_in_bits_r_exe2ls_csr_addr),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_csr_cmd   (lsu_io_pipe_in_bits_r_exe2ls_csr_cmd),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_mem_wen   (lsu_io_pipe_in_bits_r_exe2ls_mem_wen),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_mem_op    (lsu_io_pipe_in_bits_r_exe2ls_mem_op),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_is_irq    (lsu_io_pipe_in_bits_r_exe2ls_is_irq),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_irq_num   (lsu_io_pipe_in_bits_r_exe2ls_irq_num),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_exe2ls_csr_rdata (lsu_io_pipe_in_bits_r_exe2ls_csr_rdata),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_out_ready                (_wbu_io_pipe_in_ready),	// @[src/main/core/Core.scala:33:21]
    .io_pipe_out_valid                (_lsu_io_pipe_out_valid),
    .io_pipe_out_bits_ls2wb_reg_pc    (_lsu_io_pipe_out_bits_ls2wb_reg_pc),
    .io_pipe_out_bits_ls2wb_wb_addr   (_lsu_io_pipe_out_bits_ls2wb_wb_addr),
    .io_pipe_out_bits_ls2wb_rf_wen    (_lsu_io_pipe_out_bits_ls2wb_rf_wen),
    .io_pipe_out_bits_ls2wb_wb_data   (_lsu_io_pipe_out_bits_ls2wb_wb_data),
    .io_pipe_out_bits_ls2wb_csr_wdata (_lsu_io_pipe_out_bits_ls2wb_csr_wdata),
    .io_pipe_out_bits_ls2wb_csr_addr  (_lsu_io_pipe_out_bits_ls2wb_csr_addr),
    .io_pipe_out_bits_ls2wb_csr_cmd   (_lsu_io_pipe_out_bits_ls2wb_csr_cmd),
    .io_pipe_out_bits_ls2wb_is_irq    (_lsu_io_pipe_out_bits_ls2wb_is_irq),
    .io_pipe_out_bits_ls2wb_irq_num   (_lsu_io_pipe_out_bits_ls2wb_irq_num),
    .io_hazard_flush_flg              (is_irq)	// @[src/main/core/Core.scala:361:25]
  );
  WBU wbu (	// @[src/main/core/Core.scala:33:21]
    .clock                           (clock),
    .reset                           (reset),
    .io_gpr_wen                      (_wbu_io_gpr_wen),
    .io_gpr_addr                     (_wbu_io_gpr_addr),
    .io_gpr_wdata                    (_wbu_io_gpr_wdata),
    .io_csr_addr                     (_wbu_io_csr_addr),
    .io_csr_cmd                      (_wbu_io_csr_cmd),
    .io_csr_wdata                    (_wbu_io_csr_wdata),
    .io_is_irq                       (_wbu_io_is_irq),
    .io_irq_num                      (_wbu_io_irq_num),
    .io_irq_valid                    (_wbu_io_irq_valid),
    .io_pipe_in_ready                (_wbu_io_pipe_in_ready),
    .io_pipe_in_valid                (_GEN),	// @[src/main/core/Core.scala:403:{34,56}, :449:22]
    .io_pipe_in_bits_ls2wb_reg_pc    (wbu_io_pipe_in_bits_r_ls2wb_reg_pc),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_wb_addr   (wbu_io_pipe_in_bits_r_ls2wb_wb_addr),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_rf_wen    (wbu_io_pipe_in_bits_r_ls2wb_rf_wen),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_wb_data   (wbu_io_pipe_in_bits_r_ls2wb_wb_data),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_csr_wdata (wbu_io_pipe_in_bits_r_ls2wb_csr_wdata),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_csr_addr  (wbu_io_pipe_in_bits_r_ls2wb_csr_addr),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_csr_cmd   (wbu_io_pipe_in_bits_r_ls2wb_csr_cmd),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_is_irq    (wbu_io_pipe_in_bits_r_ls2wb_is_irq),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_in_bits_ls2wb_irq_num   (wbu_io_pipe_in_bits_r_ls2wb_irq_num),	// @[src/main/core/Core.scala:448:33]
    .io_pipe_out_ready               (1'h1),	// @[src/main/core/Core.scala:40:27]
    .io_pipe_out_valid               (/* unused */),
    .io_hazard_flush_flg             (is_irq)	// @[src/main/core/Core.scala:361:25]
  );
  iCache icache (	// @[src/main/core/Core.scala:59:24]
    .clock                                    (clock),
    .reset                                    (reset),
    .io_in_araddr                             (_ifu_io_imem_araddr),	// @[src/main/core/Core.scala:29:21]
    .io_in_arvalid                            (_ifu_io_imem_arvalid),	// @[src/main/core/Core.scala:29:21]
    .io_in_arready                            (_icache_io_in_arready),
    .io_in_rdata                              (_icache_io_in_rdata),
    .io_in_rvalid                             (_icache_io_in_rvalid),
    .io_in_rready                             (_ifu_io_imem_rready),	// @[src/main/core/Core.scala:29:21]
    .io_out_araddr                            (io_imem_araddr),
    .io_out_arvalid                           (io_imem_arvalid),
    .io_out_arready                           (io_imem_arready),
    .io_out_arid                              (io_imem_arid),
    .io_out_arlen                             (io_imem_arlen),
    .io_out_arsize                            (io_imem_arsize),
    .io_out_arburst                           (io_imem_arburst),
    .io_out_rdata                             (io_imem_rdata),
    .io_out_rvalid                            (io_imem_rvalid),
    .io_out_rready                            (io_imem_rready),
    .io_out_awaddr                            (io_imem_awaddr),
    .io_out_awvalid                           (io_imem_awvalid),
    .io_out_awid                              (io_imem_awid),
    .io_out_awlen                             (io_imem_awlen),
    .io_out_awsize                            (io_imem_awsize),
    .io_out_awburst                           (io_imem_awburst),
    .io_out_wdata                             (io_imem_wdata),
    .io_out_wstrb                             (io_imem_wstrb),
    .io_out_wvalid                            (io_imem_wvalid),
    .io_out_wlast                             (io_imem_wlast),
    .io_out_bready                            (io_imem_bready),
    .fencei_io_vr_is_fencei_io_ready          (_icache_fencei_io_vr_is_fencei_io_ready),
    .fencei_io_vr_is_fencei_io_valid          (_idu_fencei_io_vr_is_fencei_io_valid),	// @[src/main/core/Core.scala:30:21]
    .fencei_io_vr_is_fencei_io_bits_is_fencei
      (_idu_fencei_io_vr_is_fencei_io_bits_is_fencei)	// @[src/main/core/Core.scala:30:21]
  );
endmodule

