// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Core(	// @[src/main/core/Core.scala:23:7]
  input         clock,	// @[src/main/core/Core.scala:23:7]
                reset,	// @[src/main/core/Core.scala:23:7]
  output [31:0] io_imem_araddr,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_arvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_imem_arready,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_arid,	// @[src/main/core/Core.scala:24:16]
  output [7:0]  io_imem_arlen,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_imem_arsize,	// @[src/main/core/Core.scala:24:16]
  output [1:0]  io_imem_arburst,	// @[src/main/core/Core.scala:24:16]
  input  [31:0] io_imem_rdata,	// @[src/main/core/Core.scala:24:16]
  input         io_imem_rvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_rready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_imem_awaddr,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_awvalid,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_awid,	// @[src/main/core/Core.scala:24:16]
  output [7:0]  io_imem_awlen,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_imem_awsize,	// @[src/main/core/Core.scala:24:16]
  output [1:0]  io_imem_awburst,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_imem_wdata,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_imem_wstrb,	// @[src/main/core/Core.scala:24:16]
  output        io_imem_wvalid,	// @[src/main/core/Core.scala:24:16]
                io_imem_wlast,	// @[src/main/core/Core.scala:24:16]
                io_imem_bready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_araddr,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_arvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_arready,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_dmem_arsize,	// @[src/main/core/Core.scala:24:16]
  input  [31:0] io_dmem_rdata,	// @[src/main/core/Core.scala:24:16]
  input  [1:0]  io_dmem_rresp,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_rvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_rready,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_awaddr,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_awvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_awready,	// @[src/main/core/Core.scala:24:16]
  output [2:0]  io_dmem_awsize,	// @[src/main/core/Core.scala:24:16]
  output [31:0] io_dmem_wdata,	// @[src/main/core/Core.scala:24:16]
  output [3:0]  io_dmem_wstrb,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_wvalid,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_wready,	// @[src/main/core/Core.scala:24:16]
  input  [1:0]  io_dmem_bresp,	// @[src/main/core/Core.scala:24:16]
  input         io_dmem_bvalid,	// @[src/main/core/Core.scala:24:16]
  output        io_dmem_bready	// @[src/main/core/Core.scala:24:16]
);

  wire        _GEN;	// @[src/main/core/Core.scala:399:{34,56}, :445:22]
  wire        _GEN_0;	// @[src/main/core/Core.scala:398:{34,56}, :445:22]
  wire        _GEN_1;	// @[src/main/core/Core.scala:397:{34,56}, :445:22]
  wire        _GEN_2;	// @[src/main/core/Core.scala:396:{34,56}, :445:22]
  wire        _icache_io_in_arready;	// @[src/main/core/Core.scala:59:24]
  wire [31:0] _icache_io_in_rdata;	// @[src/main/core/Core.scala:59:24]
  wire        _icache_io_in_rvalid;	// @[src/main/core/Core.scala:59:24]
  wire        _icache_fencei_io_vr_is_fencei_io_ready;	// @[src/main/core/Core.scala:59:24]
  wire [1:0]  _wbu_io_gpr_wen;	// @[src/main/core/Core.scala:33:21]
  wire [3:0]  _wbu_io_gpr_addr;	// @[src/main/core/Core.scala:33:21]
  wire [31:0] _wbu_io_gpr_wdata;	// @[src/main/core/Core.scala:33:21]
  wire [11:0] _wbu_io_csr_addr;	// @[src/main/core/Core.scala:33:21]
  wire [2:0]  _wbu_io_csr_cmd;	// @[src/main/core/Core.scala:33:21]
  wire [31:0] _wbu_io_csr_wdata;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_is_irq;	// @[src/main/core/Core.scala:33:21]
  wire [3:0]  _wbu_io_irq_num;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_irq_valid;	// @[src/main/core/Core.scala:33:21]
  wire        _wbu_io_pipe_in_ready;	// @[src/main/core/Core.scala:33:21]
  wire        _lsu_io_pipe_in_ready;	// @[src/main/core/Core.scala:32:21]
  wire        _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_reg_pc;	// @[src/main/core/Core.scala:32:21]
  wire [3:0]  _lsu_io_pipe_out_bits_ls2wb_wb_addr;	// @[src/main/core/Core.scala:32:21]
  wire [1:0]  _lsu_io_pipe_out_bits_ls2wb_rf_wen;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_wb_data;	// @[src/main/core/Core.scala:32:21]
  wire [31:0] _lsu_io_pipe_out_bits_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:32:21]
  wire [11:0] _lsu_io_pipe_out_bits_ls2wb_csr_addr;	// @[src/main/core/Core.scala:32:21]
  wire [2:0]  _lsu_io_pipe_out_bits_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:32:21]
  wire        _lsu_io_pipe_out_bits_ls2wb_is_irq;	// @[src/main/core/Core.scala:32:21]
  wire [3:0]  _lsu_io_pipe_out_bits_ls2wb_irq_num;	// @[src/main/core/Core.scala:32:21]
  wire        _exu_io_br_flg;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_jmp_flg;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_br_target;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_alu_out;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_in_ready;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_reg_pc;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_op1_data;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_rs2_data;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _exu_io_pipe_out_bits_exe2ls_wb_addr;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_alu_out;	// @[src/main/core/Core.scala:31:21]
  wire [1:0]  _exu_io_pipe_out_bits_exe2ls_rf_wen;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_wb_sel;	// @[src/main/core/Core.scala:31:21]
  wire [11:0] _exu_io_pipe_out_bits_exe2ls_csr_addr;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:31:21]
  wire [1:0]  _exu_io_pipe_out_bits_exe2ls_mem_wen;	// @[src/main/core/Core.scala:31:21]
  wire [2:0]  _exu_io_pipe_out_bits_exe2ls_mem_op;	// @[src/main/core/Core.scala:31:21]
  wire        _exu_io_pipe_out_bits_exe2ls_is_irq;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _exu_io_pipe_out_bits_exe2ls_irq_num;	// @[src/main/core/Core.scala:31:21]
  wire [31:0] _exu_io_pipe_out_bits_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:31:21]
  wire [3:0]  _idu_io_gpr_rs1_addr;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_gpr_rs2_addr;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_gpr_rs1_is_read;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_gpr_rs2_is_read;	// @[src/main/core/Core.scala:30:21]
  wire [11:0] _idu_io_csr_raddr;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_is_mret;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_in_ready;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_reg_pc;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_op1_sel;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_op2_sel;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_rs1_data;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_rs2_data;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_pipe_out_bits_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_rf_wen;	// @[src/main/core/Core.scala:30:21]
  wire [4:0]  _idu_io_pipe_out_bits_id2exe_exe_fun;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_wb_sel;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_imm_sext;	// @[src/main/core/Core.scala:30:21]
  wire [11:0] _idu_io_pipe_out_bits_id2exe_csr_addr;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_csr_cmd;	// @[src/main/core/Core.scala:30:21]
  wire [1:0]  _idu_io_pipe_out_bits_id2exe_mem_wen;	// @[src/main/core/Core.scala:30:21]
  wire [2:0]  _idu_io_pipe_out_bits_id2exe_mem_op;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_io_pipe_out_bits_id2exe_is_irq;	// @[src/main/core/Core.scala:30:21]
  wire [3:0]  _idu_io_pipe_out_bits_id2exe_irq_num;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _idu_io_pipe_out_bits_id2exe_csr_rdata;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_fencei_io_vr_is_fencei_io_valid;	// @[src/main/core/Core.scala:30:21]
  wire        _idu_fencei_io_vr_is_fencei_io_bits_is_fencei;	// @[src/main/core/Core.scala:30:21]
  wire [31:0] _ifu_io_imem_araddr;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_imem_arvalid;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_imem_rready;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_pipe_in_ready;	// @[src/main/core/Core.scala:29:21]
  wire        _ifu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_pipe_out_bits_if2id_reg_pc;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_pipe_out_bits_if2id_inst;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _ifu_io_hazard_pc_plus4;	// @[src/main/core/Core.scala:29:21]
  wire [31:0] _csr_io_csr_mtvec;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _csr_io_csr_mepc;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _csr_io_csr_rdata;	// @[src/main/core/Core.scala:27:21]
  wire [31:0] _gpr_io_gpr_rs1_data;	// @[src/main/core/Core.scala:26:21]
  wire [31:0] _gpr_io_gpr_rs2_data;	// @[src/main/core/Core.scala:26:21]
  reg         ready_r;	// @[src/main/core/Core.scala:41:26]
  reg         ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:38]
  reg  [31:0] idu_io_pipe_in_bits_r_if2id_reg_pc;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] idu_io_pipe_in_bits_r_if2id_inst;	// @[src/main/core/Core.scala:444:33]
  reg         idu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:445:34]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_reg_pc;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_op1_sel;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_op2_sel;	// @[src/main/core/Core.scala:444:33]
  reg  [3:0]  exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_rf_wen;	// @[src/main/core/Core.scala:444:33]
  reg  [4:0]  exu_io_pipe_in_bits_r_id2exe_exe_fun;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_wb_sel;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_imm_sext;	// @[src/main/core/Core.scala:444:33]
  reg  [11:0] exu_io_pipe_in_bits_r_id2exe_csr_addr;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_csr_cmd;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  exu_io_pipe_in_bits_r_id2exe_mem_wen;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  exu_io_pipe_in_bits_r_id2exe_mem_op;	// @[src/main/core/Core.scala:444:33]
  reg         exu_io_pipe_in_bits_r_id2exe_is_irq;	// @[src/main/core/Core.scala:444:33]
  reg  [3:0]  exu_io_pipe_in_bits_r_id2exe_irq_num;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] exu_io_pipe_in_bits_r_id2exe_csr_rdata;	// @[src/main/core/Core.scala:444:33]
  reg         exu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:445:34]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_reg_pc;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_op1_data;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_rs2_data;	// @[src/main/core/Core.scala:444:33]
  reg  [3:0]  lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_alu_out;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  lsu_io_pipe_in_bits_r_exe2ls_rf_wen;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_wb_sel;	// @[src/main/core/Core.scala:444:33]
  reg  [11:0] lsu_io_pipe_in_bits_r_exe2ls_csr_addr;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  lsu_io_pipe_in_bits_r_exe2ls_mem_wen;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  lsu_io_pipe_in_bits_r_exe2ls_mem_op;	// @[src/main/core/Core.scala:444:33]
  reg         lsu_io_pipe_in_bits_r_exe2ls_is_irq;	// @[src/main/core/Core.scala:444:33]
  reg  [3:0]  lsu_io_pipe_in_bits_r_exe2ls_irq_num;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] lsu_io_pipe_in_bits_r_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:444:33]
  reg         lsu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:445:34]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_reg_pc;	// @[src/main/core/Core.scala:444:33]
  reg  [3:0]  wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:444:33]
  reg  [1:0]  wbu_io_pipe_in_bits_r_ls2wb_rf_wen;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_wb_data;	// @[src/main/core/Core.scala:444:33]
  reg  [31:0] wbu_io_pipe_in_bits_r_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:444:33]
  reg  [11:0] wbu_io_pipe_in_bits_r_ls2wb_csr_addr;	// @[src/main/core/Core.scala:444:33]
  reg  [2:0]  wbu_io_pipe_in_bits_r_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:444:33]
  reg         wbu_io_pipe_in_bits_r_ls2wb_is_irq;	// @[src/main/core/Core.scala:444:33]
  reg  [3:0]  wbu_io_pipe_in_bits_r_ls2wb_irq_num;	// @[src/main/core/Core.scala:444:33]
  reg         wbu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:445:34]
  wire        exu_is_working = ~_exu_io_pipe_in_ready | _GEN_1;	// @[src/main/core/Core.scala:31:21, :120:{26,48}, :397:{34,56}, :445:22]
  wire        lsu_is_working = ~_lsu_io_pipe_in_ready | _GEN_0;	// @[src/main/core/Core.scala:32:21, :121:{26,48}, :398:{34,56}, :445:22]
  wire        wbu_is_working = ~_wbu_io_pipe_in_ready | _GEN;	// @[src/main/core/Core.scala:33:21, :122:{26,48}, :399:{34,56}, :445:22]
  reg         wbu_end_flg_REG;	// @[src/main/core/Core.scala:123:30]
  wire        wbu_end_flg = wbu_end_flg_REG & ~wbu_is_working;	// @[src/main/core/Core.scala:122:48, :123:{30,47,49}]
  wire        _exu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33, :448:48]
  wire        _exu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == exu_io_pipe_in_bits_r_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33, :448:48]
  wire        exu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _exu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _exu_raw_rs2_T)
    & exu_is_working & exu_io_pipe_in_bits_r_id2exe_rf_wen == 2'h1 & _GEN_2;	// @[src/main/core/Core.scala:30:21, :120:48, :128:132, :396:{34,56}, :444:33, :445:22, :448:48, :453:31, :454:31, :459:{39,65,97,146}]
  wire        _lsu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33, :448:48]
  wire        _lsu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == lsu_io_pipe_in_bits_r_exe2ls_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33, :448:48]
  wire        lsu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _lsu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _lsu_raw_rs2_T)
    & lsu_is_working & lsu_io_pipe_in_bits_r_exe2ls_rf_wen == 2'h1 & _GEN_2;	// @[src/main/core/Core.scala:30:21, :121:48, :128:132, :129:132, :396:{34,56}, :444:33, :445:22, :448:48, :453:31, :454:31, :459:{39,65,97,146}]
  wire        _wbu_raw_rs1_T =
    _idu_io_gpr_rs1_addr == wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33, :448:48]
  wire        _wbu_raw_rs2_T =
    _idu_io_gpr_rs2_addr == wbu_io_pipe_in_bits_r_ls2wb_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33, :448:48]
  wire        wbu_raw =
    (_idu_io_gpr_rs1_is_read & (|_idu_io_gpr_rs1_addr) & _wbu_raw_rs1_T
     | _idu_io_gpr_rs2_is_read & (|_idu_io_gpr_rs2_addr) & _wbu_raw_rs2_T)
    & wbu_is_working & wbu_io_pipe_in_bits_r_ls2wb_rf_wen == 2'h1 & _GEN_2;	// @[src/main/core/Core.scala:30:21, :122:48, :128:132, :130:130, :396:{34,56}, :444:33, :445:22, :448:48, :453:31, :454:31, :459:{39,65,97,146}]
  wire        is_raw = exu_raw | lsu_raw | wbu_raw;	// @[src/main/core/Core.scala:131:37, :459:146]
  wire        exu_raw_rs1 = exu_raw & _exu_raw_rs1_T;	// @[src/main/core/Core.scala:132:31, :448:48, :459:146]
  wire        exu_raw_rs2 = exu_raw & _exu_raw_rs2_T;	// @[src/main/core/Core.scala:133:31, :448:48, :459:146]
  wire        lsu_raw_rs1 = lsu_raw & _lsu_raw_rs1_T;	// @[src/main/core/Core.scala:134:31, :448:48, :459:146]
  wire        lsu_raw_rs2 = lsu_raw & _lsu_raw_rs2_T;	// @[src/main/core/Core.scala:135:31, :448:48, :459:146]
  wire        wbu_raw_rs1 = wbu_raw & _wbu_raw_rs1_T;	// @[src/main/core/Core.scala:136:31, :448:48, :459:146]
  wire        wbu_raw_rs2 = wbu_raw & _wbu_raw_rs2_T;	// @[src/main/core/Core.scala:137:31, :448:48, :459:146]
  wire        rs1_raw = exu_raw_rs1 | lsu_raw_rs1 | wbu_raw_rs1;	// @[src/main/core/Core.scala:132:31, :134:31, :136:31, :138:46]
  wire        rs2_raw = exu_raw_rs2 | lsu_raw_rs2 | wbu_raw_rs2;	// @[src/main/core/Core.scala:133:31, :135:31, :137:31, :139:46]
  reg         exu_rs1_rawing;	// @[src/main/core/Core.scala:141:33]
  reg         exu_rs2_rawing;	// @[src/main/core/Core.scala:142:33]
  reg         lsu_rs1_rawing;	// @[src/main/core/Core.scala:143:33]
  reg         lsu_rs2_rawing;	// @[src/main/core/Core.scala:144:33]
  reg         wbu_rs1_rawing;	// @[src/main/core/Core.scala:145:33]
  reg         wbu_rs2_rawing;	// @[src/main/core/Core.scala:146:33]
  wire        rawing =
    exu_rs1_rawing | exu_rs2_rawing | lsu_rs1_rawing | lsu_rs2_rawing | wbu_rs1_rawing
    | wbu_rs2_rawing;	// @[src/main/core/Core.scala:141:33, :142:33, :143:33, :144:33, :145:33, :146:33, :172:105]
  wire        rs1_rawing = exu_rs1_rawing | lsu_rs1_rawing | wbu_rs1_rawing;	// @[src/main/core/Core.scala:141:33, :143:33, :145:33, :174:55]
  wire        rs2_rawing = exu_rs2_rawing | lsu_rs2_rawing | wbu_rs2_rawing;	// @[src/main/core/Core.scala:142:33, :144:33, :146:33, :175:55]
  reg         rd1_forward_en_r;	// @[src/main/core/Core.scala:179:35]
  reg         rd2_forward_en_r;	// @[src/main/core/Core.scala:180:35]
  wire        rd1_rd2_forward_en_r = rd1_forward_en_r | rd2_forward_en_r;	// @[src/main/core/Core.scala:179:35, :180:35, :181:49]
  wire        _exu_can_forward_rs2_T = exu_io_pipe_in_bits_r_id2exe_wb_sel != 3'h1;	// @[src/main/core/Core.scala:183:84, :444:33]
  wire        exu_can_forward_rs1 =
    exu_rs1_rawing & _exu_can_forward_rs2_T & ~rd1_rd2_forward_en_r;	// @[src/main/core/Core.scala:141:33, :181:49, :183:{84,96,99}]
  wire        exu_can_forward_rs2 =
    exu_rs2_rawing & _exu_can_forward_rs2_T & ~rd1_rd2_forward_en_r;	// @[src/main/core/Core.scala:142:33, :181:49, :183:{84,99}, :184:96]
  wire        _lsu_can_forward_rs2_T = lsu_io_pipe_in_bits_r_exe2ls_wb_sel != 3'h1;	// @[src/main/core/Core.scala:183:84, :185:84, :444:33]
  wire        _lsu_can_forward_rs2_T_1 = _wbu_io_pipe_in_ready & _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21, :33:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        lsu_can_forward_rs1 =
    lsu_rs1_rawing & (_lsu_can_forward_rs2_T | _lsu_can_forward_rs2_T_1)
    & ~rd1_rd2_forward_en_r;	// @[src/main/core/Core.scala:143:33, :181:49, :183:99, :185:{84,95,120}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        lsu_can_forward_rs2 =
    lsu_rs2_rawing & (_lsu_can_forward_rs2_T | _lsu_can_forward_rs2_T_1)
    & ~rd1_rd2_forward_en_r;	// @[src/main/core/Core.scala:144:33, :181:49, :183:99, :185:84, :186:{95,120}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        wbu_can_forward_rs1 = wbu_rs1_rawing & ~rd1_rd2_forward_en_r;	// @[src/main/core/Core.scala:145:33, :181:49, :183:99, :187:46]
  wire        wbu_can_forward_rs2 = wbu_rs2_rawing & ~rd1_rd2_forward_en_r;	// @[src/main/core/Core.scala:146:33, :181:49, :183:99, :188:46]
  wire [31:0] exu_forward_data =
    exu_io_pipe_in_bits_r_id2exe_wb_sel == 3'h0
      ? _exu_io_pipe_out_bits_exe2ls_alu_out
      : exu_io_pipe_in_bits_r_id2exe_wb_sel == 3'h3
          ? _exu_io_pipe_out_bits_exe2ls_csr_rdata
          : exu_io_pipe_in_bits_r_id2exe_wb_sel == 3'h2
              ? _exu_io_pipe_out_bits_exe2ls_reg_pc + 32'h4
              : 32'h0;	// @[src/main/core/Core.scala:31:21, :189:77, :190:59, :444:33]
  wire        rd1_forward_en =
    exu_rs1_rawing
      ? exu_can_forward_rs1
      : lsu_rs1_rawing ? lsu_can_forward_rs1 : wbu_rs1_rawing & wbu_can_forward_rs1;	// @[src/main/core/Core.scala:141:33, :143:33, :145:33, :183:96, :185:120, :187:46, :206:30, :207:25, :208:24, :209:31, :210:24, :211:31, :212:24, :214:24]
  wire        rd2_forward_en =
    exu_rs2_rawing
      ? exu_can_forward_rs2
      : lsu_rs2_rawing ? lsu_can_forward_rs2 : wbu_rs2_rawing & wbu_can_forward_rs2;	// @[src/main/core/Core.scala:142:33, :144:33, :146:33, :184:96, :186:120, :188:46, :216:30, :217:25, :218:24, :219:31, :220:24, :221:31, :222:24, :224:24]
  wire [31:0] rd1_forward_data =
    rd1_forward_en
      ? (exu_can_forward_rs1
           ? exu_forward_data
           : lsu_can_forward_rs1
               ? _lsu_io_pipe_out_bits_ls2wb_wb_data
               : wbu_can_forward_rs1 ? _wbu_io_gpr_wdata : 32'h0)
      : _idu_io_pipe_out_bits_id2exe_rs1_data;	// @[src/main/core/Core.scala:30:21, :32:21, :33:21, :183:96, :185:120, :187:46, :189:77, :206:30, :226:31, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire [31:0] rd2_forward_data =
    rd2_forward_en
      ? (exu_can_forward_rs2
           ? exu_forward_data
           : lsu_can_forward_rs2
               ? _lsu_io_pipe_out_bits_ls2wb_wb_data
               : wbu_can_forward_rs2 ? _wbu_io_gpr_wdata : 32'h0)
      : _idu_io_pipe_out_bits_id2exe_rs2_data;	// @[src/main/core/Core.scala:30:21, :32:21, :33:21, :184:96, :186:120, :188:46, :189:77, :216:30, :231:31, src/main/scala/chisel3/util/Mux.scala:126:16]
  reg  [31:0] rd1_forward_data_r;	// @[src/main/core/Core.scala:244:39]
  reg  [31:0] rd2_forward_data_r;	// @[src/main/core/Core.scala:245:39]
  reg  [31:0] exu_io_pipe_in_bits_id2exe_rs1_data_r;	// @[src/main/core/Core.scala:247:53]
  reg  [31:0] exu_io_pipe_in_bits_id2exe_rs2_data_r;	// @[src/main/core/Core.scala:248:53]
  reg         is_irq;	// @[src/main/core/Core.scala:357:25]
  reg         is_mret_rise_REG;	// @[src/main/core/Core.scala:363:49]
  wire        is_mret_rise = _idu_io_is_mret & ~is_mret_rise_REG;	// @[src/main/core/Core.scala:30:21, :363:{39,41,49}]
  reg         is_mret_r;	// @[src/main/core/Core.scala:365:28]
  wire        is_ctrl_hazard =
    (_exu_io_br_flg & _exu_io_br_target != _ifu_io_pipe_out_bits_if2id_reg_pc
     | _exu_io_jmp_flg & _exu_io_alu_out != _ifu_io_pipe_out_bits_if2id_reg_pc)
    & _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21, :31:21, :368:{42,62,101,120,138,178}]
  reg         is_ctrl_hazard_r;	// @[src/main/core/Core.scala:371:35]
  reg         is_irq_r;	// @[src/main/core/Core.scala:372:27]
  wire        _idu_io_hazard_flush_flg_T = is_ctrl_hazard | is_irq;	// @[src/main/core/Core.scala:357:25, :368:178, :376:47]
  wire        _GEN_3 = ~_idu_io_hazard_flush_flg_T & ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:{26,38}, :376:47, :395:{34,56}]
  assign _GEN_2 = ~_idu_io_hazard_flush_flg_T & idu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:42:26, :376:47, :395:{34,56}, :396:{34,56}, :445:{22,34}]
  assign _GEN_1 = ~is_irq & exu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:357:25, :397:{34,56}, :445:{22,34}]
  assign _GEN_0 = ~is_irq & lsu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:357:25, :397:{34,56}, :398:{34,56}, :445:{22,34}]
  assign _GEN = ~is_irq & wbu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:357:25, :397:{34,56}, :399:{34,56}, :445:{22,34}]
  wire        _is_irq_r_T = _ifu_io_pipe_in_ready & _GEN_3;	// @[src/main/core/Core.scala:29:21, :42:26, :366:69, :395:{34,56}]
  wire        _exu_io_pipe_in_bits_id2exe_rs2_data_T_3 =
    _exu_io_pipe_in_ready & _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21, :31:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[src/main/core/Core.scala:23:7]
    ready_r <= _ifu_io_pipe_in_ready;	// @[src/main/core/Core.scala:29:21, :41:26]
    if (_ifu_io_pipe_out_valid & _idu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:29:21, :30:21, :444:62]
      idu_io_pipe_in_bits_r_if2id_reg_pc <= _ifu_io_pipe_out_bits_if2id_reg_pc;	// @[src/main/core/Core.scala:29:21, :444:33]
      idu_io_pipe_in_bits_r_if2id_inst <= _ifu_io_pipe_out_bits_if2id_inst;	// @[src/main/core/Core.scala:29:21, :444:33]
    end
    if (_idu_io_pipe_in_ready)	// @[src/main/core/Core.scala:30:21]
      idu_io_pipe_in_valid_r <= _ifu_io_pipe_out_valid;	// @[src/main/core/Core.scala:29:21, :445:34]
    if (_idu_io_pipe_out_valid & _exu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:30:21, :31:21, :444:62]
      exu_io_pipe_in_bits_r_id2exe_reg_pc <= _idu_io_pipe_out_bits_id2exe_reg_pc;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_op1_sel <= _idu_io_pipe_out_bits_id2exe_op1_sel;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_op2_sel <= _idu_io_pipe_out_bits_id2exe_op2_sel;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_wb_addr <= _idu_io_pipe_out_bits_id2exe_wb_addr;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_rf_wen <= _idu_io_pipe_out_bits_id2exe_rf_wen;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_exe_fun <= _idu_io_pipe_out_bits_id2exe_exe_fun;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_wb_sel <= _idu_io_pipe_out_bits_id2exe_wb_sel;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_imm_sext <= _idu_io_pipe_out_bits_id2exe_imm_sext;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_csr_addr <= _idu_io_pipe_out_bits_id2exe_csr_addr;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_csr_cmd <= _idu_io_pipe_out_bits_id2exe_csr_cmd;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_mem_wen <= _idu_io_pipe_out_bits_id2exe_mem_wen;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_mem_op <= _idu_io_pipe_out_bits_id2exe_mem_op;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_is_irq <= _idu_io_pipe_out_bits_id2exe_is_irq;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_irq_num <= _idu_io_pipe_out_bits_id2exe_irq_num;	// @[src/main/core/Core.scala:30:21, :444:33]
      exu_io_pipe_in_bits_r_id2exe_csr_rdata <= _idu_io_pipe_out_bits_id2exe_csr_rdata;	// @[src/main/core/Core.scala:30:21, :444:33]
    end
    if (_exu_io_pipe_in_ready)	// @[src/main/core/Core.scala:31:21]
      exu_io_pipe_in_valid_r <= _idu_io_pipe_out_valid;	// @[src/main/core/Core.scala:30:21, :445:34]
    if (_exu_io_pipe_out_valid & _lsu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:31:21, :32:21, :444:62]
      lsu_io_pipe_in_bits_r_exe2ls_reg_pc <= _exu_io_pipe_out_bits_exe2ls_reg_pc;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_op1_data <= _exu_io_pipe_out_bits_exe2ls_op1_data;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_rs2_data <= _exu_io_pipe_out_bits_exe2ls_rs2_data;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_wb_addr <= _exu_io_pipe_out_bits_exe2ls_wb_addr;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_alu_out <= _exu_io_pipe_out_bits_exe2ls_alu_out;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_rf_wen <= _exu_io_pipe_out_bits_exe2ls_rf_wen;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_wb_sel <= _exu_io_pipe_out_bits_exe2ls_wb_sel;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_addr <= _exu_io_pipe_out_bits_exe2ls_csr_addr;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_cmd <= _exu_io_pipe_out_bits_exe2ls_csr_cmd;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_mem_wen <= _exu_io_pipe_out_bits_exe2ls_mem_wen;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_mem_op <= _exu_io_pipe_out_bits_exe2ls_mem_op;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_is_irq <= _exu_io_pipe_out_bits_exe2ls_is_irq;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_irq_num <= _exu_io_pipe_out_bits_exe2ls_irq_num;	// @[src/main/core/Core.scala:31:21, :444:33]
      lsu_io_pipe_in_bits_r_exe2ls_csr_rdata <= _exu_io_pipe_out_bits_exe2ls_csr_rdata;	// @[src/main/core/Core.scala:31:21, :444:33]
    end
    if (_lsu_io_pipe_in_ready)	// @[src/main/core/Core.scala:32:21]
      lsu_io_pipe_in_valid_r <= _exu_io_pipe_out_valid;	// @[src/main/core/Core.scala:31:21, :445:34]
    if (_lsu_io_pipe_out_valid & _wbu_io_pipe_in_ready) begin	// @[src/main/core/Core.scala:32:21, :33:21, :444:62]
      wbu_io_pipe_in_bits_r_ls2wb_reg_pc <= _lsu_io_pipe_out_bits_ls2wb_reg_pc;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_wb_addr <= _lsu_io_pipe_out_bits_ls2wb_wb_addr;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_rf_wen <= _lsu_io_pipe_out_bits_ls2wb_rf_wen;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_wb_data <= _lsu_io_pipe_out_bits_ls2wb_wb_data;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_wdata <= _lsu_io_pipe_out_bits_ls2wb_csr_wdata;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_addr <= _lsu_io_pipe_out_bits_ls2wb_csr_addr;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_csr_cmd <= _lsu_io_pipe_out_bits_ls2wb_csr_cmd;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_is_irq <= _lsu_io_pipe_out_bits_ls2wb_is_irq;	// @[src/main/core/Core.scala:32:21, :444:33]
      wbu_io_pipe_in_bits_r_ls2wb_irq_num <= _lsu_io_pipe_out_bits_ls2wb_irq_num;	// @[src/main/core/Core.scala:32:21, :444:33]
    end
    if (_wbu_io_pipe_in_ready)	// @[src/main/core/Core.scala:33:21]
      wbu_io_pipe_in_valid_r <= _lsu_io_pipe_out_valid;	// @[src/main/core/Core.scala:32:21, :445:34]
    wbu_end_flg_REG <= wbu_is_working;	// @[src/main/core/Core.scala:122:48, :123:30]
    if (rd1_forward_en)	// @[src/main/core/Core.scala:206:30]
      rd1_forward_data_r <= rd1_forward_data;	// @[src/main/core/Core.scala:226:31, :244:39]
    if (rd2_forward_en)	// @[src/main/core/Core.scala:216:30]
      rd2_forward_data_r <= rd2_forward_data;	// @[src/main/core/Core.scala:231:31, :245:39]
    if (_exu_io_pipe_in_bits_id2exe_rs2_data_T_3) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      exu_io_pipe_in_bits_id2exe_rs1_data_r <=
        rd1_forward_en | ~rs1_rawing ? rd1_forward_data : rd1_forward_data_r;	// @[src/main/core/Core.scala:174:55, :206:30, :226:31, :244:39, :247:{53,57,73,76}]
      exu_io_pipe_in_bits_id2exe_rs2_data_r <=
        rd2_forward_en | ~rs2_rawing ? rd2_forward_data : rd2_forward_data_r;	// @[src/main/core/Core.scala:175:55, :216:30, :231:31, :245:39, :248:{53,57,73,76}]
    end
    is_irq <= _wbu_io_irq_valid & _wbu_io_is_irq;	// @[src/main/core/Core.scala:33:21, :357:{25,43}]
    is_mret_rise_REG <= _idu_io_is_mret;	// @[src/main/core/Core.scala:30:21, :363:49]
    if (reset) begin	// @[src/main/core/Core.scala:23:7]
      ifu_io_pipe_in_valid_r <= _GEN_3;	// @[src/main/core/Core.scala:42:{26,38}, :395:{34,56}]
      exu_rs1_rawing <= 1'h0;	// @[src/main/core/Core.scala:141:33, :453:31]
      exu_rs2_rawing <= 1'h0;	// @[src/main/core/Core.scala:142:33, :453:31]
      lsu_rs1_rawing <= 1'h0;	// @[src/main/core/Core.scala:143:33, :453:31]
      lsu_rs2_rawing <= 1'h0;	// @[src/main/core/Core.scala:144:33, :453:31]
      wbu_rs1_rawing <= 1'h0;	// @[src/main/core/Core.scala:145:33, :453:31]
      wbu_rs2_rawing <= 1'h0;	// @[src/main/core/Core.scala:146:33, :453:31]
      rd1_forward_en_r <= 1'h0;	// @[src/main/core/Core.scala:179:35, :453:31]
      rd2_forward_en_r <= 1'h0;	// @[src/main/core/Core.scala:180:35, :453:31]
      is_mret_r <= 1'h0;	// @[src/main/core/Core.scala:365:28, :453:31]
      is_ctrl_hazard_r <= 1'h0;	// @[src/main/core/Core.scala:371:35, :453:31]
      is_irq_r <= 1'h0;	// @[src/main/core/Core.scala:372:27, :453:31]
    end
    else begin	// @[src/main/core/Core.scala:23:7]
      ifu_io_pipe_in_valid_r <= _ifu_io_pipe_in_ready & ready_r | ifu_io_pipe_in_valid_r;	// @[src/main/core/Core.scala:29:21, :41:26, :42:{38,90}]
      exu_rs1_rawing <=
        exu_raw_rs1 | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & exu_rs1_rawing;	// @[src/main/core/Core.scala:132:31, :141:33, :147:{26,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      exu_rs2_rawing <=
        exu_raw_rs2 | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & exu_rs2_rawing;	// @[src/main/core/Core.scala:133:31, :142:33, :147:51, :148:{26,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      lsu_rs1_rawing <=
        lsu_raw_rs1 | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & lsu_rs1_rawing;	// @[src/main/core/Core.scala:134:31, :143:33, :147:51, :149:{26,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      lsu_rs2_rawing <=
        lsu_raw_rs2 | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & lsu_rs2_rawing;	// @[src/main/core/Core.scala:135:31, :144:33, :147:51, :150:{26,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      wbu_rs1_rawing <=
        wbu_raw_rs1 | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & wbu_rs1_rawing;	// @[src/main/core/Core.scala:136:31, :145:33, :147:51, :151:{26,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      wbu_rs2_rawing <=
        wbu_raw_rs2 | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & wbu_rs2_rawing;	// @[src/main/core/Core.scala:137:31, :146:33, :147:51, :152:{26,51}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      rd1_forward_en_r <=
        rd1_forward_en | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & rd1_forward_en_r;	// @[src/main/core/Core.scala:147:51, :179:35, :206:30, :241:{28,56}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      rd2_forward_en_r <=
        rd2_forward_en | ~_exu_io_pipe_in_bits_id2exe_rs2_data_T_3 & rd2_forward_en_r;	// @[src/main/core/Core.scala:147:51, :180:35, :216:30, :242:{28,56}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      is_mret_r <= is_mret_rise | ~_is_irq_r_T & is_mret_r;	// @[src/main/core/Core.scala:363:39, :365:28, :366:{21,47,69}]
      is_ctrl_hazard_r <= is_ctrl_hazard | ~_is_irq_r_T & is_ctrl_hazard_r;	// @[src/main/core/Core.scala:366:{47,69}, :368:178, :371:35, :373:{28,56}]
      is_irq_r <= is_irq | ~_is_irq_r_T & is_irq_r;	// @[src/main/core/Core.scala:357:25, :366:{47,69}, :372:27, :374:{20,40}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/Core.scala:23:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/Core.scala:23:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/Core.scala:23:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:23];	// @[src/main/core/Core.scala:23:7]
    initial begin	// @[src/main/core/Core.scala:23:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/Core.scala:23:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/Core.scala:23:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/Core.scala:23:7]
        for (logic [4:0] i = 5'h0; i < 5'h18; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/core/Core.scala:23:7]
        end	// @[src/main/core/Core.scala:23:7]
        ready_r = _RANDOM[5'h0][0];	// @[src/main/core/Core.scala:23:7, :41:26]
        ifu_io_pipe_in_valid_r = _RANDOM[5'h0][1];	// @[src/main/core/Core.scala:23:7, :41:26, :42:38]
        idu_io_pipe_in_bits_r_if2id_reg_pc = {_RANDOM[5'h0][31:2], _RANDOM[5'h1][1:0]};	// @[src/main/core/Core.scala:23:7, :41:26, :444:33]
        idu_io_pipe_in_bits_r_if2id_inst = {_RANDOM[5'h1][31:2], _RANDOM[5'h2][1:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        idu_io_pipe_in_valid_r = _RANDOM[5'h2][2];	// @[src/main/core/Core.scala:23:7, :444:33, :445:34]
        exu_io_pipe_in_bits_r_id2exe_reg_pc = {_RANDOM[5'h2][31:3], _RANDOM[5'h3][2:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_op1_sel = _RANDOM[5'h3][4:3];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_op2_sel = _RANDOM[5'h3][6:5];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_wb_addr = _RANDOM[5'h5][10:7];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_rf_wen = _RANDOM[5'h5][12:11];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_exe_fun = _RANDOM[5'h5][17:13];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_wb_sel = _RANDOM[5'h5][20:18];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_imm_sext =
          {_RANDOM[5'h5][31:21], _RANDOM[5'h6][20:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_csr_addr = {_RANDOM[5'h6][31:21], _RANDOM[5'h7][0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_csr_cmd = _RANDOM[5'h7][3:1];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_mem_wen = _RANDOM[5'h7][5:4];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_mem_op = _RANDOM[5'h7][8:6];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_is_irq = _RANDOM[5'h7][9];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_irq_num = _RANDOM[5'h7][13:10];	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_bits_r_id2exe_csr_rdata =
          {_RANDOM[5'h7][31:14], _RANDOM[5'h8][13:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        exu_io_pipe_in_valid_r = _RANDOM[5'h8][14];	// @[src/main/core/Core.scala:23:7, :444:33, :445:34]
        lsu_io_pipe_in_bits_r_exe2ls_reg_pc = {_RANDOM[5'h8][31:15], _RANDOM[5'h9][14:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_op1_data =
          {_RANDOM[5'h9][31:15], _RANDOM[5'hA][14:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_rs2_data =
          {_RANDOM[5'hA][31:15], _RANDOM[5'hB][14:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_wb_addr = _RANDOM[5'hB][18:15];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_alu_out =
          {_RANDOM[5'hB][31:19], _RANDOM[5'hC][18:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_rf_wen = _RANDOM[5'hC][20:19];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_wb_sel = _RANDOM[5'hC][23:21];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_addr =
          {_RANDOM[5'hC][31:24], _RANDOM[5'hD][3:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_cmd = _RANDOM[5'hD][6:4];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_mem_wen = _RANDOM[5'hD][8:7];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_mem_op = _RANDOM[5'hD][11:9];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_is_irq = _RANDOM[5'hD][12];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_irq_num = _RANDOM[5'hD][16:13];	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_bits_r_exe2ls_csr_rdata =
          {_RANDOM[5'hD][31:17], _RANDOM[5'hE][16:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        lsu_io_pipe_in_valid_r = _RANDOM[5'hE][17];	// @[src/main/core/Core.scala:23:7, :444:33, :445:34]
        wbu_io_pipe_in_bits_r_ls2wb_reg_pc = {_RANDOM[5'hE][31:18], _RANDOM[5'hF][17:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_wb_addr = _RANDOM[5'hF][21:18];	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_rf_wen = _RANDOM[5'hF][23:22];	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_wb_data =
          {_RANDOM[5'hF][31:24], _RANDOM[5'h10][23:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_wdata =
          {_RANDOM[5'h10][31:24], _RANDOM[5'h11][23:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_addr =
          {_RANDOM[5'h11][31:24], _RANDOM[5'h12][3:0]};	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_csr_cmd = _RANDOM[5'h12][6:4];	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_is_irq = _RANDOM[5'h12][7];	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_bits_r_ls2wb_irq_num = _RANDOM[5'h12][11:8];	// @[src/main/core/Core.scala:23:7, :444:33]
        wbu_io_pipe_in_valid_r = _RANDOM[5'h12][12];	// @[src/main/core/Core.scala:23:7, :444:33, :445:34]
        wbu_end_flg_REG = _RANDOM[5'h12][13];	// @[src/main/core/Core.scala:23:7, :123:30, :444:33]
        exu_rs1_rawing = _RANDOM[5'h12][17];	// @[src/main/core/Core.scala:23:7, :141:33, :444:33]
        exu_rs2_rawing = _RANDOM[5'h12][18];	// @[src/main/core/Core.scala:23:7, :142:33, :444:33]
        lsu_rs1_rawing = _RANDOM[5'h12][19];	// @[src/main/core/Core.scala:23:7, :143:33, :444:33]
        lsu_rs2_rawing = _RANDOM[5'h12][20];	// @[src/main/core/Core.scala:23:7, :144:33, :444:33]
        wbu_rs1_rawing = _RANDOM[5'h12][21];	// @[src/main/core/Core.scala:23:7, :145:33, :444:33]
        wbu_rs2_rawing = _RANDOM[5'h12][22];	// @[src/main/core/Core.scala:23:7, :146:33, :444:33]
        rd1_forward_en_r = _RANDOM[5'h12][23];	// @[src/main/core/Core.scala:23:7, :179:35, :444:33]
        rd2_forward_en_r = _RANDOM[5'h12][24];	// @[src/main/core/Core.scala:23:7, :180:35, :444:33]
        rd1_forward_data_r = {_RANDOM[5'h12][31:25], _RANDOM[5'h13][24:0]};	// @[src/main/core/Core.scala:23:7, :244:39, :444:33]
        rd2_forward_data_r = {_RANDOM[5'h13][31:25], _RANDOM[5'h14][24:0]};	// @[src/main/core/Core.scala:23:7, :244:39, :245:39]
        exu_io_pipe_in_bits_id2exe_rs1_data_r =
          {_RANDOM[5'h14][31:25], _RANDOM[5'h15][24:0]};	// @[src/main/core/Core.scala:23:7, :245:39, :247:53]
        exu_io_pipe_in_bits_id2exe_rs2_data_r =
          {_RANDOM[5'h15][31:25], _RANDOM[5'h16][24:0]};	// @[src/main/core/Core.scala:23:7, :247:53, :248:53]
        is_irq = _RANDOM[5'h17][11];	// @[src/main/core/Core.scala:23:7, :357:25]
        is_mret_rise_REG = _RANDOM[5'h17][12];	// @[src/main/core/Core.scala:23:7, :357:25, :363:49]
        is_mret_r = _RANDOM[5'h17][13];	// @[src/main/core/Core.scala:23:7, :357:25, :365:28]
        is_ctrl_hazard_r = _RANDOM[5'h17][14];	// @[src/main/core/Core.scala:23:7, :357:25, :371:35]
        is_irq_r = _RANDOM[5'h17][15];	// @[src/main/core/Core.scala:23:7, :357:25, :372:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/Core.scala:23:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/Core.scala:23:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  GPR gpr (	// @[src/main/core/Core.scala:26:21]
    .clock           (clock),
    .reset           (reset),
    .io_gpr_rs1_addr (_idu_io_gpr_rs1_addr),	// @[src/main/core/Core.scala:30:21]
    .io_gpr_rs2_addr (_idu_io_gpr_rs2_addr),	// @[src/main/core/Core.scala:30:21]
    .io_gpr_rs1_data (_gpr_io_gpr_rs1_data),
    .io_gpr_rs2_data (_gpr_io_gpr_rs2_data),
    .io_gpr_wen      (_wbu_io_gpr_wen),	// @[src/main/core/Core.scala:33:21]
    .io_gpr_addr     (_wbu_io_gpr_addr),	// @[src/main/core/Core.scala:33:21]
    .io_gpr_wdata    (_wbu_io_gpr_wdata)	// @[src/main/core/Core.scala:33:21]
  );
  CSR csr (	// @[src/main/core/Core.scala:27:21]
    .clock          (clock),
    .reset          (reset),
    .io_csr_mtvec   (_csr_io_csr_mtvec),
    .io_csr_mepc    (_csr_io_csr_mepc),
    .io_csr_rdata   (_csr_io_csr_rdata),
    .io_csr_wdata   (_wbu_io_csr_wdata),	// @[src/main/core/Core.scala:33:21]
    .io_csr_addr    (_wbu_io_csr_addr),	// @[src/main/core/Core.scala:33:21]
    .io_csr_cmd     (_wbu_io_csr_cmd),	// @[src/main/core/Core.scala:33:21]
    .io_csr_raddr   (_idu_io_csr_raddr),	// @[src/main/core/Core.scala:30:21]
    .io_csr_reg_pc  (wbu_io_pipe_in_bits_r_ls2wb_reg_pc),	// @[src/main/core/Core.scala:444:33]
    .io_csr_irq_num (_wbu_io_irq_num),	// @[src/main/core/Core.scala:33:21]
    .io_csr_is_irq  (is_irq)	// @[src/main/core/Core.scala:357:25]
  );
  IFU ifu (	// @[src/main/core/Core.scala:29:21]
    .clock                         (clock),
    .reset                         (reset),
    .io_imem_araddr                (_ifu_io_imem_araddr),
    .io_imem_arvalid               (_ifu_io_imem_arvalid),
    .io_imem_arready               (_icache_io_in_arready),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rdata                 (_icache_io_in_rdata),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rvalid                (_icache_io_in_rvalid),	// @[src/main/core/Core.scala:59:24]
    .io_imem_rready                (_ifu_io_imem_rready),
    .io_pipe_in_ready              (_ifu_io_pipe_in_ready),
    .io_pipe_in_valid              (_GEN_3),	// @[src/main/core/Core.scala:42:26, :395:{34,56}]
    .io_pipe_out_ready             (_idu_io_pipe_in_ready),	// @[src/main/core/Core.scala:30:21]
    .io_pipe_out_valid             (_ifu_io_pipe_out_valid),
    .io_pipe_out_bits_if2id_reg_pc (_ifu_io_pipe_out_bits_if2id_reg_pc),
    .io_pipe_out_bits_if2id_inst   (_ifu_io_pipe_out_bits_if2id_inst),
    .io_hazard_flush_flg           (_idu_io_hazard_flush_flg_T),	// @[src/main/core/Core.scala:376:47]
    .io_hazard_pc_plus4            (_ifu_io_hazard_pc_plus4),
    .io_hazard_pc_real_next
      (is_irq_r
         ? _csr_io_csr_mtvec
         : is_ctrl_hazard_r | is_mret_r
             ? (_exu_io_br_flg ? _exu_io_br_target : 32'h0)
               | (_exu_io_jmp_flg ? _exu_io_alu_out : 32'h0)
               | (_idu_io_is_mret ? _csr_io_csr_mepc : 32'h0)
             : _ifu_io_hazard_pc_plus4),	// @[src/main/core/Core.scala:27:21, :29:21, :30:21, :31:21, :189:77, :365:28, :371:35, :372:27, :391:{27,59,77}, src/main/scala/chisel3/util/Mux.scala:30:73]
    .io_hazard_is_mret_rise        (is_mret_rise)	// @[src/main/core/Core.scala:363:39]
  );
  IDU idu (	// @[src/main/core/Core.scala:30:21]
    .clock                                    (clock),
    .reset                                    (reset),
    .io_gpr_rs1_addr                          (_idu_io_gpr_rs1_addr),
    .io_gpr_rs2_addr                          (_idu_io_gpr_rs2_addr),
    .io_gpr_rs1_data                          (_gpr_io_gpr_rs1_data),	// @[src/main/core/Core.scala:26:21]
    .io_gpr_rs2_data                          (_gpr_io_gpr_rs2_data),	// @[src/main/core/Core.scala:26:21]
    .io_gpr_rs1_is_read                       (_idu_io_gpr_rs1_is_read),
    .io_gpr_rs2_is_read                       (_idu_io_gpr_rs2_is_read),
    .io_csr_raddr                             (_idu_io_csr_raddr),
    .io_csr_rdata                             (_csr_io_csr_rdata),	// @[src/main/core/Core.scala:27:21]
    .io_is_mret                               (_idu_io_is_mret),
    .io_pipe_in_ready                         (_idu_io_pipe_in_ready),
    .io_pipe_in_valid                         (_GEN_2),	// @[src/main/core/Core.scala:396:{34,56}, :445:22]
    .io_pipe_in_bits_if2id_reg_pc             (idu_io_pipe_in_bits_r_if2id_reg_pc),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_if2id_inst               (idu_io_pipe_in_bits_r_if2id_inst),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_out_ready                        (_exu_io_pipe_in_ready),	// @[src/main/core/Core.scala:31:21]
    .io_pipe_out_valid                        (_idu_io_pipe_out_valid),
    .io_pipe_out_bits_id2exe_reg_pc           (_idu_io_pipe_out_bits_id2exe_reg_pc),
    .io_pipe_out_bits_id2exe_op1_sel          (_idu_io_pipe_out_bits_id2exe_op1_sel),
    .io_pipe_out_bits_id2exe_op2_sel          (_idu_io_pipe_out_bits_id2exe_op2_sel),
    .io_pipe_out_bits_id2exe_rs1_data         (_idu_io_pipe_out_bits_id2exe_rs1_data),
    .io_pipe_out_bits_id2exe_rs2_data         (_idu_io_pipe_out_bits_id2exe_rs2_data),
    .io_pipe_out_bits_id2exe_wb_addr          (_idu_io_pipe_out_bits_id2exe_wb_addr),
    .io_pipe_out_bits_id2exe_rf_wen           (_idu_io_pipe_out_bits_id2exe_rf_wen),
    .io_pipe_out_bits_id2exe_exe_fun          (_idu_io_pipe_out_bits_id2exe_exe_fun),
    .io_pipe_out_bits_id2exe_wb_sel           (_idu_io_pipe_out_bits_id2exe_wb_sel),
    .io_pipe_out_bits_id2exe_imm_sext         (_idu_io_pipe_out_bits_id2exe_imm_sext),
    .io_pipe_out_bits_id2exe_csr_addr         (_idu_io_pipe_out_bits_id2exe_csr_addr),
    .io_pipe_out_bits_id2exe_csr_cmd          (_idu_io_pipe_out_bits_id2exe_csr_cmd),
    .io_pipe_out_bits_id2exe_mem_wen          (_idu_io_pipe_out_bits_id2exe_mem_wen),
    .io_pipe_out_bits_id2exe_mem_op           (_idu_io_pipe_out_bits_id2exe_mem_op),
    .io_pipe_out_bits_id2exe_is_irq           (_idu_io_pipe_out_bits_id2exe_is_irq),
    .io_pipe_out_bits_id2exe_irq_num          (_idu_io_pipe_out_bits_id2exe_irq_num),
    .io_pipe_out_bits_id2exe_csr_rdata        (_idu_io_pipe_out_bits_id2exe_csr_rdata),
    .fencei_io_vr_is_fencei_io_ready          (_icache_fencei_io_vr_is_fencei_io_ready),	// @[src/main/core/Core.scala:59:24]
    .fencei_io_vr_is_fencei_io_valid          (_idu_fencei_io_vr_is_fencei_io_valid),
    .fencei_io_vr_is_fencei_io_bits_is_fencei
      (_idu_fencei_io_vr_is_fencei_io_bits_is_fencei),
    .io_hazard_stall_flg
      (is_raw | rawing & ~rd1_forward_en & ~rd2_forward_en & ~rd1_rd2_forward_en_r)	// @[src/main/core/Core.scala:131:37, :172:105, :181:49, :183:99, :206:30, :216:30, :250:{39,53,72,89}]
  );
  EXU exu (	// @[src/main/core/Core.scala:31:21]
    .clock                             (clock),
    .reset                             (reset),
    .io_br_flg                         (_exu_io_br_flg),
    .io_jmp_flg                        (_exu_io_jmp_flg),
    .io_br_target                      (_exu_io_br_target),
    .io_alu_out                        (_exu_io_alu_out),
    .io_pipe_in_ready                  (_exu_io_pipe_in_ready),
    .io_pipe_in_valid                  (_GEN_1),	// @[src/main/core/Core.scala:397:{34,56}, :445:22]
    .io_pipe_in_bits_id2exe_reg_pc     (exu_io_pipe_in_bits_r_id2exe_reg_pc),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_op1_sel    (exu_io_pipe_in_bits_r_id2exe_op1_sel),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_op2_sel    (exu_io_pipe_in_bits_r_id2exe_op2_sel),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_rs1_data   (exu_io_pipe_in_bits_id2exe_rs1_data_r),	// @[src/main/core/Core.scala:247:53]
    .io_pipe_in_bits_id2exe_rs2_data   (exu_io_pipe_in_bits_id2exe_rs2_data_r),	// @[src/main/core/Core.scala:248:53]
    .io_pipe_in_bits_id2exe_wb_addr    (exu_io_pipe_in_bits_r_id2exe_wb_addr),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_rf_wen     (exu_io_pipe_in_bits_r_id2exe_rf_wen),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_exe_fun    (exu_io_pipe_in_bits_r_id2exe_exe_fun),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_wb_sel     (exu_io_pipe_in_bits_r_id2exe_wb_sel),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_imm_sext   (exu_io_pipe_in_bits_r_id2exe_imm_sext),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_csr_addr   (exu_io_pipe_in_bits_r_id2exe_csr_addr),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_csr_cmd    (exu_io_pipe_in_bits_r_id2exe_csr_cmd),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_mem_wen    (exu_io_pipe_in_bits_r_id2exe_mem_wen),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_mem_op     (exu_io_pipe_in_bits_r_id2exe_mem_op),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_is_irq     (exu_io_pipe_in_bits_r_id2exe_is_irq),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_irq_num    (exu_io_pipe_in_bits_r_id2exe_irq_num),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_id2exe_csr_rdata  (exu_io_pipe_in_bits_r_id2exe_csr_rdata),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_out_ready                 (_lsu_io_pipe_in_ready),	// @[src/main/core/Core.scala:32:21]
    .io_pipe_out_valid                 (_exu_io_pipe_out_valid),
    .io_pipe_out_bits_exe2ls_reg_pc    (_exu_io_pipe_out_bits_exe2ls_reg_pc),
    .io_pipe_out_bits_exe2ls_op1_data  (_exu_io_pipe_out_bits_exe2ls_op1_data),
    .io_pipe_out_bits_exe2ls_rs2_data  (_exu_io_pipe_out_bits_exe2ls_rs2_data),
    .io_pipe_out_bits_exe2ls_wb_addr   (_exu_io_pipe_out_bits_exe2ls_wb_addr),
    .io_pipe_out_bits_exe2ls_alu_out   (_exu_io_pipe_out_bits_exe2ls_alu_out),
    .io_pipe_out_bits_exe2ls_rf_wen    (_exu_io_pipe_out_bits_exe2ls_rf_wen),
    .io_pipe_out_bits_exe2ls_wb_sel    (_exu_io_pipe_out_bits_exe2ls_wb_sel),
    .io_pipe_out_bits_exe2ls_csr_addr  (_exu_io_pipe_out_bits_exe2ls_csr_addr),
    .io_pipe_out_bits_exe2ls_csr_cmd   (_exu_io_pipe_out_bits_exe2ls_csr_cmd),
    .io_pipe_out_bits_exe2ls_mem_wen   (_exu_io_pipe_out_bits_exe2ls_mem_wen),
    .io_pipe_out_bits_exe2ls_mem_op    (_exu_io_pipe_out_bits_exe2ls_mem_op),
    .io_pipe_out_bits_exe2ls_is_irq    (_exu_io_pipe_out_bits_exe2ls_is_irq),
    .io_pipe_out_bits_exe2ls_irq_num   (_exu_io_pipe_out_bits_exe2ls_irq_num),
    .io_pipe_out_bits_exe2ls_csr_rdata (_exu_io_pipe_out_bits_exe2ls_csr_rdata),
    .io_hazard_flush_flg               (is_irq)	// @[src/main/core/Core.scala:357:25]
  );
  LSU lsu (	// @[src/main/core/Core.scala:32:21]
    .clock                            (clock),
    .reset                            (reset),
    .io_dmem_araddr                   (io_dmem_araddr),
    .io_dmem_arvalid                  (io_dmem_arvalid),
    .io_dmem_arready                  (io_dmem_arready),
    .io_dmem_arsize                   (io_dmem_arsize),
    .io_dmem_rdata                    (io_dmem_rdata),
    .io_dmem_rresp                    (io_dmem_rresp),
    .io_dmem_rvalid                   (io_dmem_rvalid),
    .io_dmem_rready                   (io_dmem_rready),
    .io_dmem_awaddr                   (io_dmem_awaddr),
    .io_dmem_awvalid                  (io_dmem_awvalid),
    .io_dmem_awready                  (io_dmem_awready),
    .io_dmem_awsize                   (io_dmem_awsize),
    .io_dmem_wdata                    (io_dmem_wdata),
    .io_dmem_wstrb                    (io_dmem_wstrb),
    .io_dmem_wvalid                   (io_dmem_wvalid),
    .io_dmem_wready                   (io_dmem_wready),
    .io_dmem_bresp                    (io_dmem_bresp),
    .io_dmem_bvalid                   (io_dmem_bvalid),
    .io_dmem_bready                   (io_dmem_bready),
    .io_pipe_in_ready                 (_lsu_io_pipe_in_ready),
    .io_pipe_in_valid                 (_GEN_0),	// @[src/main/core/Core.scala:398:{34,56}, :445:22]
    .io_pipe_in_bits_exe2ls_reg_pc    (lsu_io_pipe_in_bits_r_exe2ls_reg_pc),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_op1_data  (lsu_io_pipe_in_bits_r_exe2ls_op1_data),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_rs2_data  (lsu_io_pipe_in_bits_r_exe2ls_rs2_data),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_wb_addr   (lsu_io_pipe_in_bits_r_exe2ls_wb_addr),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_alu_out   (lsu_io_pipe_in_bits_r_exe2ls_alu_out),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_rf_wen    (lsu_io_pipe_in_bits_r_exe2ls_rf_wen),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_wb_sel    (lsu_io_pipe_in_bits_r_exe2ls_wb_sel),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_csr_addr  (lsu_io_pipe_in_bits_r_exe2ls_csr_addr),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_csr_cmd   (lsu_io_pipe_in_bits_r_exe2ls_csr_cmd),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_mem_wen   (lsu_io_pipe_in_bits_r_exe2ls_mem_wen),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_mem_op    (lsu_io_pipe_in_bits_r_exe2ls_mem_op),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_is_irq    (lsu_io_pipe_in_bits_r_exe2ls_is_irq),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_irq_num   (lsu_io_pipe_in_bits_r_exe2ls_irq_num),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_exe2ls_csr_rdata (lsu_io_pipe_in_bits_r_exe2ls_csr_rdata),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_out_ready                (_wbu_io_pipe_in_ready),	// @[src/main/core/Core.scala:33:21]
    .io_pipe_out_valid                (_lsu_io_pipe_out_valid),
    .io_pipe_out_bits_ls2wb_reg_pc    (_lsu_io_pipe_out_bits_ls2wb_reg_pc),
    .io_pipe_out_bits_ls2wb_wb_addr   (_lsu_io_pipe_out_bits_ls2wb_wb_addr),
    .io_pipe_out_bits_ls2wb_rf_wen    (_lsu_io_pipe_out_bits_ls2wb_rf_wen),
    .io_pipe_out_bits_ls2wb_wb_data   (_lsu_io_pipe_out_bits_ls2wb_wb_data),
    .io_pipe_out_bits_ls2wb_csr_wdata (_lsu_io_pipe_out_bits_ls2wb_csr_wdata),
    .io_pipe_out_bits_ls2wb_csr_addr  (_lsu_io_pipe_out_bits_ls2wb_csr_addr),
    .io_pipe_out_bits_ls2wb_csr_cmd   (_lsu_io_pipe_out_bits_ls2wb_csr_cmd),
    .io_pipe_out_bits_ls2wb_is_irq    (_lsu_io_pipe_out_bits_ls2wb_is_irq),
    .io_pipe_out_bits_ls2wb_irq_num   (_lsu_io_pipe_out_bits_ls2wb_irq_num),
    .io_hazard_flush_flg              (is_irq)	// @[src/main/core/Core.scala:357:25]
  );
  WBU wbu (	// @[src/main/core/Core.scala:33:21]
    .clock                           (clock),
    .reset                           (reset),
    .io_gpr_wen                      (_wbu_io_gpr_wen),
    .io_gpr_addr                     (_wbu_io_gpr_addr),
    .io_gpr_wdata                    (_wbu_io_gpr_wdata),
    .io_csr_addr                     (_wbu_io_csr_addr),
    .io_csr_cmd                      (_wbu_io_csr_cmd),
    .io_csr_wdata                    (_wbu_io_csr_wdata),
    .io_is_irq                       (_wbu_io_is_irq),
    .io_irq_num                      (_wbu_io_irq_num),
    .io_irq_valid                    (_wbu_io_irq_valid),
    .io_pipe_in_ready                (_wbu_io_pipe_in_ready),
    .io_pipe_in_valid                (_GEN),	// @[src/main/core/Core.scala:399:{34,56}, :445:22]
    .io_pipe_in_bits_ls2wb_reg_pc    (wbu_io_pipe_in_bits_r_ls2wb_reg_pc),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_wb_addr   (wbu_io_pipe_in_bits_r_ls2wb_wb_addr),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_rf_wen    (wbu_io_pipe_in_bits_r_ls2wb_rf_wen),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_wb_data   (wbu_io_pipe_in_bits_r_ls2wb_wb_data),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_csr_wdata (wbu_io_pipe_in_bits_r_ls2wb_csr_wdata),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_csr_addr  (wbu_io_pipe_in_bits_r_ls2wb_csr_addr),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_csr_cmd   (wbu_io_pipe_in_bits_r_ls2wb_csr_cmd),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_is_irq    (wbu_io_pipe_in_bits_r_ls2wb_is_irq),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_in_bits_ls2wb_irq_num   (wbu_io_pipe_in_bits_r_ls2wb_irq_num),	// @[src/main/core/Core.scala:444:33]
    .io_pipe_out_ready               (1'h1),	// @[src/main/core/Core.scala:40:27]
    .io_pipe_out_valid               (/* unused */),
    .io_hazard_flush_flg             (is_irq)	// @[src/main/core/Core.scala:357:25]
  );
  iCache icache (	// @[src/main/core/Core.scala:59:24]
    .clock                                    (clock),
    .reset                                    (reset),
    .io_in_araddr                             (_ifu_io_imem_araddr),	// @[src/main/core/Core.scala:29:21]
    .io_in_arvalid                            (_ifu_io_imem_arvalid),	// @[src/main/core/Core.scala:29:21]
    .io_in_arready                            (_icache_io_in_arready),
    .io_in_rdata                              (_icache_io_in_rdata),
    .io_in_rvalid                             (_icache_io_in_rvalid),
    .io_in_rready                             (_ifu_io_imem_rready),	// @[src/main/core/Core.scala:29:21]
    .io_out_araddr                            (io_imem_araddr),
    .io_out_arvalid                           (io_imem_arvalid),
    .io_out_arready                           (io_imem_arready),
    .io_out_arid                              (io_imem_arid),
    .io_out_arlen                             (io_imem_arlen),
    .io_out_arsize                            (io_imem_arsize),
    .io_out_arburst                           (io_imem_arburst),
    .io_out_rdata                             (io_imem_rdata),
    .io_out_rvalid                            (io_imem_rvalid),
    .io_out_rready                            (io_imem_rready),
    .io_out_awaddr                            (io_imem_awaddr),
    .io_out_awvalid                           (io_imem_awvalid),
    .io_out_awid                              (io_imem_awid),
    .io_out_awlen                             (io_imem_awlen),
    .io_out_awsize                            (io_imem_awsize),
    .io_out_awburst                           (io_imem_awburst),
    .io_out_wdata                             (io_imem_wdata),
    .io_out_wstrb                             (io_imem_wstrb),
    .io_out_wvalid                            (io_imem_wvalid),
    .io_out_wlast                             (io_imem_wlast),
    .io_out_bready                            (io_imem_bready),
    .fencei_io_vr_is_fencei_io_ready          (_icache_fencei_io_vr_is_fencei_io_ready),
    .fencei_io_vr_is_fencei_io_valid          (_idu_fencei_io_vr_is_fencei_io_valid),	// @[src/main/core/Core.scala:30:21]
    .fencei_io_vr_is_fencei_io_bits_is_fencei
      (_idu_fencei_io_vr_is_fencei_io_bits_is_fencei)	// @[src/main/core/Core.scala:30:21]
  );
endmodule

