// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module EXU(	// @[src/main/core/exu/EXU.scala:47:7]
  input         clock,	// @[src/main/core/exu/EXU.scala:47:7]
                reset,	// @[src/main/core/exu/EXU.scala:47:7]
  output [31:0] io_dmem_araddr,	// @[src/main/core/exu/EXU.scala:48:16]
  output        io_dmem_arvalid,	// @[src/main/core/exu/EXU.scala:48:16]
  input         io_dmem_arready,	// @[src/main/core/exu/EXU.scala:48:16]
  output [2:0]  io_dmem_arsize,	// @[src/main/core/exu/EXU.scala:48:16]
  input  [31:0] io_dmem_rdata,	// @[src/main/core/exu/EXU.scala:48:16]
  input         io_dmem_rvalid,	// @[src/main/core/exu/EXU.scala:48:16]
  output        io_dmem_rready,	// @[src/main/core/exu/EXU.scala:48:16]
  output [31:0] io_dmem_awaddr,	// @[src/main/core/exu/EXU.scala:48:16]
  output        io_dmem_awvalid,	// @[src/main/core/exu/EXU.scala:48:16]
  input         io_dmem_awready,	// @[src/main/core/exu/EXU.scala:48:16]
  output [2:0]  io_dmem_awsize,	// @[src/main/core/exu/EXU.scala:48:16]
  output [31:0] io_dmem_wdata,	// @[src/main/core/exu/EXU.scala:48:16]
  output [3:0]  io_dmem_wstrb,	// @[src/main/core/exu/EXU.scala:48:16]
  output        io_dmem_wvalid,	// @[src/main/core/exu/EXU.scala:48:16]
  input         io_dmem_wready,	// @[src/main/core/exu/EXU.scala:48:16]
                io_dmem_bvalid,	// @[src/main/core/exu/EXU.scala:48:16]
  output        io_dmem_bready,	// @[src/main/core/exu/EXU.scala:48:16]
                io_bj_valid,	// @[src/main/core/exu/EXU.scala:49:19]
  output [31:0] io_bj_target,	// @[src/main/core/exu/EXU.scala:49:19]
  output        io_pipe_in_ready,	// @[src/main/core/exu/EXU.scala:50:21]
  input         io_pipe_in_valid,	// @[src/main/core/exu/EXU.scala:50:21]
  input  [1:0]  io_pipe_in_bits_is2exe_processunit,	// @[src/main/core/exu/EXU.scala:50:21]
  input  [3:0]  io_pipe_in_bits_is2exe_processtpe,	// @[src/main/core/exu/EXU.scala:50:21]
  input  [2:0]  io_pipe_in_bits_is2exe_bjtpe,	// @[src/main/core/exu/EXU.scala:50:21]
  input         io_pipe_in_bits_is2exe_rfwe,	// @[src/main/core/exu/EXU.scala:50:21]
  input  [3:0]  io_pipe_in_bits_is2exe_rd_addr,	// @[src/main/core/exu/EXU.scala:50:21]
  input  [31:0] io_pipe_in_bits_is2exe_ch1,	// @[src/main/core/exu/EXU.scala:50:21]
                io_pipe_in_bits_is2exe_ch2,	// @[src/main/core/exu/EXU.scala:50:21]
                io_pipe_in_bits_is2exe_ch3,	// @[src/main/core/exu/EXU.scala:50:21]
  input         io_pipe_out_ready,	// @[src/main/core/exu/EXU.scala:50:21]
  output        io_pipe_out_valid,	// @[src/main/core/exu/EXU.scala:50:21]
                io_pipe_out_bits_exe2wb_gpr_we,	// @[src/main/core/exu/EXU.scala:50:21]
  output [31:0] io_pipe_out_bits_exe2wb_gpr_wdata,	// @[src/main/core/exu/EXU.scala:50:21]
  output [3:0]  io_pipe_out_bits_exe2wb_gpr_waddr	// @[src/main/core/exu/EXU.scala:50:21]
);

  reg         in_ready;	// @[src/main/core/exu/EXU.scala:121:27]
  wire        _lsu_io_in_ready;	// @[src/main/core/exu/EXU.scala:94:21]
  wire        _lsu_io_out_valid;	// @[src/main/core/exu/EXU.scala:94:21]
  wire [31:0] _lsu_io_out_bits_gpr_wdata;	// @[src/main/core/exu/EXU.scala:94:21]
  wire        _alu_io_in_ready;	// @[src/main/core/exu/EXU.scala:80:21]
  wire        _alu_io_out_valid;	// @[src/main/core/exu/EXU.scala:80:21]
  wire [31:0] _alu_io_out_bits_alu_out;	// @[src/main/core/exu/EXU.scala:80:21]
  wire        _alu_io_bj_valid;	// @[src/main/core/exu/EXU.scala:80:21]
  wire        _csr_io_out_valid;	// @[src/main/core/exu/EXU.scala:67:21]
  wire [31:0] _csr_io_out_bits_csr_rdata;	// @[src/main/core/exu/EXU.scala:67:21]
  wire        _csr_io_bj_valid;	// @[src/main/core/exu/EXU.scala:67:21]
  wire [31:0] _csr_io_bj_target;	// @[src/main/core/exu/EXU.scala:67:21]
  wire        _n_state_T_1 = in_ready & io_pipe_in_valid;	// @[src/main/core/exu/EXU.scala:121:27, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _io_pipe_out_bits_exe2wb_gpr_wdata_T =
    io_pipe_in_bits_is2exe_processunit == 2'h1;	// @[src/main/core/exu/EXU.scala:68:55]
  wire        _io_pipe_out_bits_exe2wb_gpr_wdata_T_1 =
    io_pipe_in_bits_is2exe_processunit == 2'h2;	// @[src/main/core/exu/EXU.scala:95:55]
  reg         out_valid;	// @[src/main/core/exu/EXU.scala:122:28]
  reg         c_state;	// @[src/main/core/exu/EXU.scala:127:26]
  wire        n_state = c_state ? ~(io_pipe_out_ready & out_valid) : _n_state_T_1;	// @[src/main/core/exu/EXU.scala:104:50, :122:28, :127:26, :128:30, :133:51, :134:33, :135:33, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[src/main/core/exu/EXU.scala:47:7]
    if (reset) begin	// @[src/main/core/exu/EXU.scala:47:7]
      in_ready <= 1'h0;	// @[src/main/core/exu/EXU.scala:47:7, :121:27]
      out_valid <= 1'h0;	// @[src/main/core/exu/EXU.scala:47:7, :122:28]
      c_state <= 1'h0;	// @[src/main/core/exu/EXU.scala:47:7, :127:26]
    end
    else begin	// @[src/main/core/exu/EXU.scala:47:7]
      if (n_state)	// @[src/main/core/exu/EXU.scala:128:30]
        in_ready <= ~n_state & in_ready;	// @[src/main/core/exu/EXU.scala:121:27, :128:30, :138:20, :144:22]
      else	// @[src/main/core/exu/EXU.scala:128:30]
        in_ready <= _alu_io_in_ready & _lsu_io_in_ready;	// @[src/main/core/exu/EXU.scala:80:21, :94:21, :121:27, :140:60]
      out_valid <=
        n_state
        & (n_state
             ? _csr_io_out_valid | _alu_io_out_valid | _lsu_io_out_valid
             : out_valid);	// @[src/main/core/exu/EXU.scala:67:21, :80:21, :94:21, :106:54, :122:28, :128:30, :138:20, :141:23, :145:23]
      c_state <= n_state;	// @[src/main/core/exu/EXU.scala:127:26, :128:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/exu/EXU.scala:47:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/exu/EXU.scala:47:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/exu/EXU.scala:47:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/core/exu/EXU.scala:47:7]
    initial begin	// @[src/main/core/exu/EXU.scala:47:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/exu/EXU.scala:47:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/exu/EXU.scala:47:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/exu/EXU.scala:47:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/core/exu/EXU.scala:47:7]
        in_ready = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/core/exu/EXU.scala:47:7, :121:27]
        out_valid = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/core/exu/EXU.scala:47:7, :121:27, :122:28]
        c_state = _RANDOM[/*Zero width*/ 1'b0][2];	// @[src/main/core/exu/EXU.scala:47:7, :121:27, :127:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/exu/EXU.scala:47:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/exu/EXU.scala:47:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CSR csr (	// @[src/main/core/exu/EXU.scala:67:21]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (_n_state_T_1 & _io_pipe_out_bits_exe2wb_gpr_wdata_T),	// @[src/main/core/exu/EXU.scala:68:{40,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_in_bits_op1        (io_pipe_in_bits_is2exe_ch1),
    .io_in_bits_op2        (io_pipe_in_bits_is2exe_ch2),
    .io_in_bits_processtpe (io_pipe_in_bits_is2exe_processtpe),
    .io_out_valid          (_csr_io_out_valid),
    .io_out_bits_csr_rdata (_csr_io_out_bits_csr_rdata),
    .io_bj_valid           (_csr_io_bj_valid),
    .io_bj_target          (_csr_io_bj_target)
  );
  ALU alu (	// @[src/main/core/exu/EXU.scala:80:21]
    .io_in_ready           (_alu_io_in_ready),
    .io_in_valid           (_n_state_T_1 & io_pipe_in_bits_is2exe_processunit == 2'h0),	// @[src/main/core/exu/EXU.scala:81:{40,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_in_bits_op1        (io_pipe_in_bits_is2exe_ch1),
    .io_in_bits_op2        (io_pipe_in_bits_is2exe_ch2),
    .io_in_bits_processtpe (io_pipe_in_bits_is2exe_processtpe),
    .io_in_bits_bjtpe      (io_pipe_in_bits_is2exe_bjtpe),
    .io_out_ready          (io_pipe_out_ready),
    .io_out_valid          (_alu_io_out_valid),
    .io_out_bits_alu_out   (_alu_io_out_bits_alu_out),
    .io_bj_valid           (_alu_io_bj_valid)
  );
  LSU lsu (	// @[src/main/core/exu/EXU.scala:94:21]
    .clock                 (clock),
    .reset                 (reset),
    .io_dmem_dmem_araddr   (io_dmem_araddr),
    .io_dmem_dmem_arvalid  (io_dmem_arvalid),
    .io_dmem_dmem_arready  (io_dmem_arready),
    .io_dmem_dmem_arsize   (io_dmem_arsize),
    .io_dmem_dmem_rdata    (io_dmem_rdata),
    .io_dmem_dmem_rvalid   (io_dmem_rvalid),
    .io_dmem_dmem_rready   (io_dmem_rready),
    .io_dmem_dmem_awaddr   (io_dmem_awaddr),
    .io_dmem_dmem_awvalid  (io_dmem_awvalid),
    .io_dmem_dmem_awready  (io_dmem_awready),
    .io_dmem_dmem_awsize   (io_dmem_awsize),
    .io_dmem_dmem_wdata    (io_dmem_wdata),
    .io_dmem_dmem_wstrb    (io_dmem_wstrb),
    .io_dmem_dmem_wvalid   (io_dmem_wvalid),
    .io_dmem_dmem_wready   (io_dmem_wready),
    .io_dmem_dmem_bvalid   (io_dmem_bvalid),
    .io_dmem_dmem_bready   (io_dmem_bready),
    .io_in_ready           (_lsu_io_in_ready),
    .io_in_valid           (_n_state_T_1 & _io_pipe_out_bits_exe2wb_gpr_wdata_T_1),	// @[src/main/core/exu/EXU.scala:95:{40,55}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_in_bits_op1        (io_pipe_in_bits_is2exe_ch3),
    .io_in_bits_op2        (io_pipe_in_bits_is2exe_ch2),
    .io_in_bits_processtpe (io_pipe_in_bits_is2exe_processtpe),
    .io_out_ready          (io_pipe_out_ready),
    .io_out_valid          (_lsu_io_out_valid),
    .io_out_bits_gpr_wdata (_lsu_io_out_bits_gpr_wdata)
  );
  assign io_bj_valid = _alu_io_bj_valid | _csr_io_bj_valid;	// @[src/main/core/exu/EXU.scala:47:7, :67:21, :80:21, :103:36]
  assign io_bj_target =
    _alu_io_bj_valid
      ? io_pipe_in_bits_is2exe_ch3
      : _csr_io_bj_valid ? _csr_io_bj_target : 32'h0;	// @[src/main/core/exu/EXU.scala:47:7, :67:21, :80:21, :104:{24,50}]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/exu/EXU.scala:47:7, :121:27]
  assign io_pipe_out_valid = out_valid;	// @[src/main/core/exu/EXU.scala:47:7, :122:28]
  assign io_pipe_out_bits_exe2wb_gpr_we = io_pipe_in_bits_is2exe_rfwe;	// @[src/main/core/exu/EXU.scala:47:7]
  assign io_pipe_out_bits_exe2wb_gpr_wdata =
    _io_pipe_out_bits_exe2wb_gpr_wdata_T
      ? _csr_io_out_bits_csr_rdata
      : _io_pipe_out_bits_exe2wb_gpr_wdata_T_1
          ? _lsu_io_out_bits_gpr_wdata
          : _alu_io_out_bits_alu_out;	// @[src/main/core/exu/EXU.scala:47:7, :67:21, :68:55, :80:21, :94:21, :95:55, :109:{45,109}]
  assign io_pipe_out_bits_exe2wb_gpr_waddr = io_pipe_in_bits_is2exe_rd_addr;	// @[src/main/core/exu/EXU.scala:47:7]
endmodule

