// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module iCache(	// @[src/main/cache/iCache.scala:26:7]
  input         clock,	// @[src/main/cache/iCache.scala:26:7]
                reset,	// @[src/main/cache/iCache.scala:26:7]
  input  [31:0] io_in_araddr,	// @[src/main/cache/iCache.scala:27:16]
  input         io_in_arvalid,	// @[src/main/cache/iCache.scala:27:16]
  output        io_in_arready,	// @[src/main/cache/iCache.scala:27:16]
  output [31:0] io_in_rdata,	// @[src/main/cache/iCache.scala:27:16]
  output        io_in_rvalid,	// @[src/main/cache/iCache.scala:27:16]
  input         io_in_rready,	// @[src/main/cache/iCache.scala:27:16]
  output [31:0] io_out_araddr,	// @[src/main/cache/iCache.scala:27:16]
  output        io_out_arvalid,	// @[src/main/cache/iCache.scala:27:16]
  input         io_out_arready,	// @[src/main/cache/iCache.scala:27:16]
  output [2:0]  io_out_arsize,	// @[src/main/cache/iCache.scala:27:16]
  output [1:0]  io_out_arburst,	// @[src/main/cache/iCache.scala:27:16]
  input  [31:0] io_out_rdata,	// @[src/main/cache/iCache.scala:27:16]
  input         io_out_rvalid,	// @[src/main/cache/iCache.scala:27:16]
  output        io_out_rready	// @[src/main/cache/iCache.scala:27:16]
);

  wire        io_out_arvalid_0;	// @[src/main/cache/iCache.scala:95:20, :166:24]
  wire        io_in_rvalid_0;	// @[src/main/cache/iCache.scala:95:20, :97:26]
  wire        io_in_arready_0;	// @[src/main/cache/iCache.scala:95:20, :98:27]
  reg         count;	// @[src/main/cache/iCache.scala:37:24]
  wire [1:0]  req_index = io_in_araddr[3:2];	// @[src/main/cache/iCache.scala:38:33]
  wire [1:0]  req_offset = io_in_araddr[1:0];	// @[src/main/cache/iCache.scala:39:34]
  wire [27:0] req_tag = io_in_araddr[31:4];	// @[src/main/cache/iCache.scala:40:31]
  wire [31:0] addr_align = io_in_araddr - {30'h0, req_offset};	// @[src/main/cache/iCache.scala:39:34, :41:35]
  reg         icache_0_set_0_valid;	// @[src/main/cache/iCache.scala:48:25]
  reg  [27:0] icache_0_set_0_tag;	// @[src/main/cache/iCache.scala:48:25]
  reg  [31:0] icache_0_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25]
  reg         icache_1_set_0_valid;	// @[src/main/cache/iCache.scala:48:25]
  reg  [27:0] icache_1_set_0_tag;	// @[src/main/cache/iCache.scala:48:25]
  reg  [31:0] icache_1_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25]
  reg         icache_2_set_0_valid;	// @[src/main/cache/iCache.scala:48:25]
  reg  [27:0] icache_2_set_0_tag;	// @[src/main/cache/iCache.scala:48:25]
  reg  [31:0] icache_2_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25]
  reg         icache_3_set_0_valid;	// @[src/main/cache/iCache.scala:48:25]
  reg  [27:0] icache_3_set_0_tag;	// @[src/main/cache/iCache.scala:48:25]
  reg  [31:0] icache_3_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25]
  reg  [1:0]  c_state;	// @[src/main/cache/iCache.scala:53:26]
  reg         casez_tmp;	// @[src/main/cache/iCache.scala:60:43]
  always_comb begin	// @[src/main/cache/iCache.scala:60:43]
    casez (req_index)	// @[src/main/cache/iCache.scala:38:33, :60:43]
      2'b00:
        casez_tmp = icache_0_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      2'b01:
        casez_tmp = icache_1_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      2'b10:
        casez_tmp = icache_2_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      default:
        casez_tmp = icache_3_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :60:43]
    endcase	// @[src/main/cache/iCache.scala:38:33, :60:43]
  end // always_comb
  reg  [27:0] casez_tmp_0;	// @[src/main/cache/iCache.scala:60:43]
  always_comb begin	// @[src/main/cache/iCache.scala:60:43]
    casez (req_index)	// @[src/main/cache/iCache.scala:38:33, :60:43]
      2'b00:
        casez_tmp_0 = icache_0_set_0_tag;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      2'b01:
        casez_tmp_0 = icache_1_set_0_tag;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      2'b10:
        casez_tmp_0 = icache_2_set_0_tag;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      default:
        casez_tmp_0 = icache_3_set_0_tag;	// @[src/main/cache/iCache.scala:48:25, :60:43]
    endcase	// @[src/main/cache/iCache.scala:38:33, :60:43]
  end // always_comb
  reg  [31:0] casez_tmp_1;	// @[src/main/cache/iCache.scala:60:43]
  always_comb begin	// @[src/main/cache/iCache.scala:60:43]
    casez (req_index)	// @[src/main/cache/iCache.scala:38:33, :60:43]
      2'b00:
        casez_tmp_1 = icache_0_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      2'b01:
        casez_tmp_1 = icache_1_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      2'b10:
        casez_tmp_1 = icache_2_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25, :60:43]
      default:
        casez_tmp_1 = icache_3_set_0_data_0;	// @[src/main/cache/iCache.scala:48:25, :60:43]
    endcase	// @[src/main/cache/iCache.scala:38:33, :60:43]
  end // always_comb
  wire        hit = casez_tmp_0 == req_tag & casez_tmp;	// @[src/main/cache/iCache.scala:40:31, :60:{43,55}]
  wire        is_sdram_raddr = io_in_araddr > 32'h9FFFFFFF & io_in_araddr[31:30] != 2'h3;	// @[src/main/cache/iCache.scala:67:{40,70,86}, :91:33]
  wire        is_hit_handshake = hit & io_in_rready;	// @[src/main/cache/iCache.scala:60:55, :69:32]
  wire        is_ifu_r_fire = io_in_rvalid_0 & io_in_rready;	// @[src/main/cache/iCache.scala:71:38, :95:20, :97:26]
  reg  [31:0] send_rdata;	// @[src/main/cache/iCache.scala:74:25]
  wire        _n_state_T_5 = c_state == 2'h1;	// @[src/main/cache/iCache.scala:53:26, :88:42, :89:53]
  wire        _n_state_T_7 = c_state == 2'h2;	// @[src/main/cache/iCache.scala:53:26, :88:42, :89:53]
  reg  [1:0]  casez_tmp_2;	// @[src/main/cache/iCache.scala:88:42]
  always_comb begin	// @[src/main/cache/iCache.scala:88:42]
    casez (c_state)	// @[src/main/cache/iCache.scala:53:26, :88:42]
      2'b00:
        casez_tmp_2 =
          io_in_arvalid & io_in_arready_0 ? (is_sdram_raddr ? 2'h1 : 2'h2) : 2'h0;	// @[src/main/cache/iCache.scala:53:26, :67:70, :68:40, :88:42, :89:{33,53}, :95:20, :98:27]
      2'b01:
        casez_tmp_2 = {~is_hit_handshake, 1'h0};	// @[src/main/cache/iCache.scala:48:61, :69:32, :88:42, :90:33]
      2'b10:
        casez_tmp_2 = {1'h1, io_out_arvalid_0 & io_out_arready};	// @[src/main/cache/iCache.scala:37:24, :70:42, :88:42, :91:33, :95:20, :166:24]
      default:
        casez_tmp_2 = is_ifu_r_fire ? 2'h0 : 2'h3;	// @[src/main/cache/iCache.scala:53:26, :71:38, :88:42, :91:33, :92:33]
    endcase	// @[src/main/cache/iCache.scala:53:26, :88:42]
  end // always_comb
  wire [1:0]  n_state = casez_tmp_2;	// @[src/main/cache/iCache.scala:54:30, :88:42]
  wire        _GEN = _n_state_T_7 | (&c_state);	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:53:26, :88:42, :95:20, :165:23]
  reg  [31:0] casez_tmp_3;	// @[src/main/cache/iCache.scala:95:20, :165:23]
  always_comb begin	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:88:42, :95:20, :165:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:53:26, :88:42, :95:20, :165:23]
      2'b00:
        casez_tmp_3 = 32'h0;	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:48:61, :88:42, :95:20, :165:23]
      2'b01:
        casez_tmp_3 = 32'h0;	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:48:61, :88:42, :95:20, :165:23]
      2'b10:
        casez_tmp_3 = io_in_araddr;	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:88:42, :95:20, :165:23]
      default:
        casez_tmp_3 = io_in_araddr;	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:88:42, :95:20, :165:23]
    endcase	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:53:26, :88:42, :95:20, :165:23]
  end // always_comb
  assign io_in_arready_0 = ~_n_state_T_5 & (~_GEN | io_out_arready);	// @[src/main/bus/AXI.scala:90:25, :96:25, src/main/cache/iCache.scala:88:42, :95:20, :98:27, :151:23, :165:23]
  reg  [31:0] casez_tmp_4;	// @[src/main/cache/iCache.scala:80:17, :95:20]
  always_comb begin	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:80:17, :88:42, :95:20, :165:23]
    casez (c_state)	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:53:26, :80:17, :88:42, :95:20, :165:23]
      2'b00:
        casez_tmp_4 = send_rdata;	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:74:25, :80:17, :88:42, :95:20, :165:23]
      2'b01:
        casez_tmp_4 = send_rdata;	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:74:25, :80:17, :88:42, :95:20, :165:23]
      2'b10:
        casez_tmp_4 = io_out_rdata;	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:80:17, :88:42, :95:20, :165:23]
      default:
        casez_tmp_4 = io_out_rdata;	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:80:17, :88:42, :95:20, :165:23]
    endcase	// @[src/main/bus/AXI.scala:90:25, :100:24, src/main/cache/iCache.scala:53:26, :80:17, :88:42, :95:20, :165:23]
  end // always_comb
  assign io_in_rvalid_0 = _n_state_T_5 ? hit : _GEN & io_out_rvalid;	// @[src/main/bus/AXI.scala:90:25, :102:24, src/main/cache/iCache.scala:60:55, :88:42, :95:20, :97:26, :154:22, :165:23]
  assign io_out_arvalid_0 = ~_n_state_T_5 & _n_state_T_7;	// @[src/main/cache/iCache.scala:88:42, :95:20, :98:27, :166:24]
  wire        _GEN_0 = is_ifu_r_fire & is_sdram_raddr;	// @[src/main/cache/iCache.scala:67:70, :71:38, :129:24]
  wire        _GEN_1 = _GEN_0 & req_index == 2'h0;	// @[src/main/cache/iCache.scala:38:33, :48:25, :53:26, :129:{24,42}, :131:35, :133:35]
  wire        _GEN_2 = _GEN_0 & req_index == 2'h1;	// @[src/main/cache/iCache.scala:38:33, :48:25, :89:53, :129:{24,42}, :131:35, :133:35]
  wire        _GEN_3 = _GEN_0 & req_index == 2'h2;	// @[src/main/cache/iCache.scala:38:33, :48:25, :89:53, :129:{24,42}, :131:35, :133:35]
  wire        _GEN_4 = _GEN_0 & (&req_index);	// @[src/main/cache/iCache.scala:38:33, :48:25, :129:{24,42}, :131:35, :133:35]
  always @(posedge clock) begin	// @[src/main/cache/iCache.scala:26:7]
    if (reset) begin	// @[src/main/cache/iCache.scala:26:7]
      count <= 1'h1;	// @[src/main/cache/iCache.scala:37:24]
      icache_0_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_0_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_0_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_1_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_1_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_1_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_2_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_2_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_2_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_3_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_3_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      icache_3_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:48:{25,61}]
      c_state <= 2'h0;	// @[src/main/cache/iCache.scala:53:26]
    end
    else begin	// @[src/main/cache/iCache.scala:26:7]
      icache_0_set_0_valid <= _GEN_1 | icache_0_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
      if (_GEN_1) begin	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
        icache_0_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:40:31, :48:25]
        icache_0_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:48:25]
      end
      icache_1_set_0_valid <= _GEN_2 | icache_1_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
      if (_GEN_2) begin	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
        icache_1_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:40:31, :48:25]
        icache_1_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:48:25]
      end
      icache_2_set_0_valid <= _GEN_3 | icache_2_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
      if (_GEN_3) begin	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
        icache_2_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:40:31, :48:25]
        icache_2_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:48:25]
      end
      icache_3_set_0_valid <= _GEN_4 | icache_3_set_0_valid;	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
      if (_GEN_4) begin	// @[src/main/cache/iCache.scala:48:25, :129:42, :131:35]
        icache_3_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:40:31, :48:25]
        icache_3_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:48:25]
      end
      c_state <= n_state;	// @[src/main/cache/iCache.scala:53:26, :54:30]
    end
    send_rdata <= is_hit_handshake ? (hit ? casez_tmp_1 : 32'h0) : io_out_rdata;	// @[src/main/cache/iCache.scala:48:61, :60:{43,55}, :69:32, :73:24, :74:25, :75:27, :76:20, :78:20]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/cache/iCache.scala:26:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/cache/iCache.scala:26:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/cache/iCache.scala:26:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[src/main/cache/iCache.scala:26:7]
    initial begin	// @[src/main/cache/iCache.scala:26:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/cache/iCache.scala:26:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/cache/iCache.scala:26:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/cache/iCache.scala:26:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/cache/iCache.scala:26:7]
        end	// @[src/main/cache/iCache.scala:26:7]
        count = _RANDOM[4'h0][0];	// @[src/main/cache/iCache.scala:26:7, :37:24]
        icache_0_set_0_valid = _RANDOM[4'h0][1];	// @[src/main/cache/iCache.scala:26:7, :37:24, :48:25]
        icache_0_set_0_tag = _RANDOM[4'h0][29:2];	// @[src/main/cache/iCache.scala:26:7, :37:24, :48:25]
        icache_0_set_0_data_0 = {_RANDOM[4'h0][31:30], _RANDOM[4'h1][29:0]};	// @[src/main/cache/iCache.scala:26:7, :37:24, :48:25]
        icache_1_set_0_valid = _RANDOM[4'h1][30];	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_1_set_0_tag = {_RANDOM[4'h1][31], _RANDOM[4'h2][26:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_1_set_0_data_0 = {_RANDOM[4'h2][31:27], _RANDOM[4'h3][26:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_2_set_0_valid = _RANDOM[4'h3][27];	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_2_set_0_tag = {_RANDOM[4'h3][31:28], _RANDOM[4'h4][23:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_2_set_0_data_0 = {_RANDOM[4'h4][31:24], _RANDOM[4'h5][23:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_3_set_0_valid = _RANDOM[4'h5][24];	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_3_set_0_tag = {_RANDOM[4'h5][31:25], _RANDOM[4'h6][20:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25]
        icache_3_set_0_data_0 = {_RANDOM[4'h6][31:21], _RANDOM[4'h7][20:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25]
        c_state = _RANDOM[4'h7][22:21];	// @[src/main/cache/iCache.scala:26:7, :48:25, :53:26]
        send_rdata = {_RANDOM[4'h7][31:23], _RANDOM[4'h8][22:0]};	// @[src/main/cache/iCache.scala:26:7, :48:25, :74:25]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/cache/iCache.scala:26:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/cache/iCache.scala:26:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_arready = io_in_arready_0;	// @[src/main/cache/iCache.scala:26:7, :95:20, :98:27]
  assign io_in_rdata = casez_tmp_4;	// @[src/main/cache/iCache.scala:26:7, :80:17, :95:20]
  assign io_in_rvalid = io_in_rvalid_0;	// @[src/main/cache/iCache.scala:26:7, :95:20, :97:26]
  assign io_out_araddr = casez_tmp_3;	// @[src/main/cache/iCache.scala:26:7, :95:20, :165:23]
  assign io_out_arvalid = io_out_arvalid_0;	// @[src/main/cache/iCache.scala:26:7, :95:20, :166:24]
  assign io_out_arsize = _n_state_T_5 ? 3'h0 : {1'h0, _GEN, 1'h0};	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:26:7, :48:61, :88:42, :95:20, :106:27, :114:27, :165:23, :169:23]
  assign io_out_arburst = _n_state_T_5 ? 2'h0 : {1'h0, _GEN};	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:26:7, :48:61, :53:26, :88:42, :95:20, :104:28, :112:28, :165:23, :170:24]
  assign io_out_rready = ~_n_state_T_5 & _GEN & io_in_rready;	// @[src/main/bus/AXI.scala:90:25, src/main/cache/iCache.scala:26:7, :88:42, :95:20, :98:27, :165:23, :171:23]
endmodule

