// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module iCache(	// @[src/main/cache/iCache.scala:25:7]
  input         clock,	// @[src/main/cache/iCache.scala:25:7]
                reset,	// @[src/main/cache/iCache.scala:25:7]
  input  [31:0] io_in_araddr,	// @[src/main/cache/iCache.scala:26:16]
  input         io_in_arvalid,	// @[src/main/cache/iCache.scala:26:16]
  output        io_in_arready,	// @[src/main/cache/iCache.scala:26:16]
  output [31:0] io_in_rdata,	// @[src/main/cache/iCache.scala:26:16]
  output        io_in_rvalid,	// @[src/main/cache/iCache.scala:26:16]
  input         io_in_rready,	// @[src/main/cache/iCache.scala:26:16]
  output [31:0] io_out_araddr,	// @[src/main/cache/iCache.scala:26:16]
  output        io_out_arvalid,	// @[src/main/cache/iCache.scala:26:16]
  input         io_out_arready,	// @[src/main/cache/iCache.scala:26:16]
  output [2:0]  io_out_arsize,	// @[src/main/cache/iCache.scala:26:16]
  output [1:0]  io_out_arburst,	// @[src/main/cache/iCache.scala:26:16]
  input  [31:0] io_out_rdata,	// @[src/main/cache/iCache.scala:26:16]
  input         io_out_rvalid,	// @[src/main/cache/iCache.scala:26:16]
  output        io_out_rready	// @[src/main/cache/iCache.scala:26:16]
);

  wire        io_out_arvalid_0;	// @[src/main/cache/iCache.scala:106:20, :179:24]
  wire        io_in_arready_0;	// @[src/main/cache/iCache.scala:106:20, :111:27]
  wire        io_in_rvalid_0;	// @[src/main/cache/iCache.scala:106:20, :110:26]
  reg  [31:0] send_rdata;	// @[src/main/cache/iCache.scala:29:25]
  reg  [31:0] send_araddr;	// @[src/main/cache/iCache.scala:30:26]
  reg         count;	// @[src/main/cache/iCache.scala:40:24]
  wire [1:0]  req_index = send_araddr[3:2];	// @[src/main/cache/iCache.scala:30:26, :41:32]
  wire [1:0]  req_offset = send_araddr[1:0];	// @[src/main/cache/iCache.scala:30:26, :42:33]
  wire [27:0] req_tag = send_araddr[31:4];	// @[src/main/cache/iCache.scala:30:26, :43:30]
  wire [31:0] addr_align = send_araddr - {30'h0, req_offset};	// @[src/main/cache/iCache.scala:30:26, :42:33, :44:34]
  reg         icache_0_set_0_valid;	// @[src/main/cache/iCache.scala:51:25]
  reg  [27:0] icache_0_set_0_tag;	// @[src/main/cache/iCache.scala:51:25]
  reg  [31:0] icache_0_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25]
  reg         icache_1_set_0_valid;	// @[src/main/cache/iCache.scala:51:25]
  reg  [27:0] icache_1_set_0_tag;	// @[src/main/cache/iCache.scala:51:25]
  reg  [31:0] icache_1_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25]
  reg         icache_2_set_0_valid;	// @[src/main/cache/iCache.scala:51:25]
  reg  [27:0] icache_2_set_0_tag;	// @[src/main/cache/iCache.scala:51:25]
  reg  [31:0] icache_2_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25]
  reg         icache_3_set_0_valid;	// @[src/main/cache/iCache.scala:51:25]
  reg  [27:0] icache_3_set_0_tag;	// @[src/main/cache/iCache.scala:51:25]
  reg  [31:0] icache_3_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25]
  reg  [1:0]  c_state;	// @[src/main/cache/iCache.scala:56:26]
  reg         casez_tmp;	// @[src/main/cache/iCache.scala:63:43]
  always_comb begin	// @[src/main/cache/iCache.scala:63:43]
    casez (req_index)	// @[src/main/cache/iCache.scala:41:32, :63:43]
      2'b00:
        casez_tmp = icache_0_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      2'b01:
        casez_tmp = icache_1_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      2'b10:
        casez_tmp = icache_2_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      default:
        casez_tmp = icache_3_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :63:43]
    endcase	// @[src/main/cache/iCache.scala:41:32, :63:43]
  end // always_comb
  reg  [27:0] casez_tmp_0;	// @[src/main/cache/iCache.scala:63:43]
  always_comb begin	// @[src/main/cache/iCache.scala:63:43]
    casez (req_index)	// @[src/main/cache/iCache.scala:41:32, :63:43]
      2'b00:
        casez_tmp_0 = icache_0_set_0_tag;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      2'b01:
        casez_tmp_0 = icache_1_set_0_tag;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      2'b10:
        casez_tmp_0 = icache_2_set_0_tag;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      default:
        casez_tmp_0 = icache_3_set_0_tag;	// @[src/main/cache/iCache.scala:51:25, :63:43]
    endcase	// @[src/main/cache/iCache.scala:41:32, :63:43]
  end // always_comb
  reg  [31:0] casez_tmp_1;	// @[src/main/cache/iCache.scala:63:43]
  always_comb begin	// @[src/main/cache/iCache.scala:63:43]
    casez (req_index)	// @[src/main/cache/iCache.scala:41:32, :63:43]
      2'b00:
        casez_tmp_1 = icache_0_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      2'b01:
        casez_tmp_1 = icache_1_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      2'b10:
        casez_tmp_1 = icache_2_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25, :63:43]
      default:
        casez_tmp_1 = icache_3_set_0_data_0;	// @[src/main/cache/iCache.scala:51:25, :63:43]
    endcase	// @[src/main/cache/iCache.scala:41:32, :63:43]
  end // always_comb
  wire        hit = casez_tmp_0 == req_tag & casez_tmp;	// @[src/main/cache/iCache.scala:43:30, :63:{43,55}]
  wire        is_sdram_raddr = send_araddr > 32'h9FFFFFFF & send_araddr[31:30] != 2'h3;	// @[src/main/cache/iCache.scala:30:26, :70:{39,69,84}, :102:33]
  wire        is_ifu_ar_fire = io_in_arvalid & io_in_arready_0;	// @[src/main/cache/iCache.scala:71:40, :106:20, :111:27]
  wire        is_hit_handshake = hit & io_in_rready;	// @[src/main/cache/iCache.scala:63:55, :72:32]
  wire        is_ifu_r_fire = io_in_rvalid_0 & io_in_rready;	// @[src/main/cache/iCache.scala:74:38, :106:20, :110:26]
  wire        _n_state_T_5 = c_state == 2'h1;	// @[src/main/cache/iCache.scala:56:26, :99:42, :100:53]
  wire        _n_state_T_7 = c_state == 2'h2;	// @[src/main/cache/iCache.scala:56:26, :99:42, :100:53]
  reg  [1:0]  casez_tmp_2;	// @[src/main/cache/iCache.scala:99:42]
  always_comb begin	// @[src/main/cache/iCache.scala:99:42]
    casez (c_state)	// @[src/main/cache/iCache.scala:56:26, :99:42]
      2'b00:
        casez_tmp_2 = is_ifu_ar_fire ? (is_sdram_raddr ? 2'h1 : 2'h2) : 2'h0;	// @[src/main/cache/iCache.scala:56:26, :70:69, :71:40, :99:42, :100:{33,53}]
      2'b01:
        casez_tmp_2 = {~is_hit_handshake, 1'h0};	// @[src/main/cache/iCache.scala:51:61, :72:32, :99:42, :101:33]
      2'b10:
        casez_tmp_2 = {1'h1, io_out_arvalid_0 & io_out_arready};	// @[src/main/cache/iCache.scala:40:24, :73:42, :99:42, :102:33, :106:20, :179:24]
      default:
        casez_tmp_2 = is_ifu_r_fire ? 2'h0 : 2'h3;	// @[src/main/cache/iCache.scala:56:26, :74:38, :99:42, :102:33, :103:33]
    endcase	// @[src/main/cache/iCache.scala:56:26, :99:42]
  end // always_comb
  wire [1:0]  n_state = casez_tmp_2;	// @[src/main/cache/iCache.scala:57:30, :99:42]
  wire        _GEN = c_state == 2'h0;	// @[src/main/cache/iCache.scala:56:26, :106:20]
  wire        _GEN_0 = _n_state_T_7 | (&c_state);	// @[src/main/cache/iCache.scala:56:26, :99:42, :106:20, :182:23, :203:25]
  wire        _GEN_1 = _GEN | _n_state_T_5;	// @[src/main/cache/iCache.scala:99:42, :106:20, :182:23]
  assign io_in_rvalid_0 = ~_GEN & (_n_state_T_5 ? hit : _GEN_0 & io_out_rvalid);	// @[src/main/cache/iCache.scala:63:55, :95:18, :99:42, :106:20, :110:26, :116:26, :182:23, :203:25, :209:24]
  assign io_in_arready_0 = _GEN | ~(_n_state_T_5 | _n_state_T_7) & ~(&c_state);	// @[src/main/cache/iCache.scala:40:24, :51:61, :56:26, :94:19, :99:42, :106:20, :111:27, :117:27, :121:27, :126:27]
  assign io_out_arvalid_0 = ~_GEN_1 & _n_state_T_7;	// @[src/main/cache/iCache.scala:99:42, :106:20, :179:24, :182:23, :184:23]
  wire        _GEN_2 = is_ifu_r_fire & ~hit & is_sdram_raddr;	// @[src/main/cache/iCache.scala:63:55, :70:69, :74:38, :142:{27,32}]
  wire        _GEN_3 = _GEN_2 & req_index == 2'h0;	// @[src/main/cache/iCache.scala:41:32, :51:25, :56:26, :142:{32,50}, :144:35, :146:35]
  wire        _GEN_4 = _GEN_2 & req_index == 2'h1;	// @[src/main/cache/iCache.scala:41:32, :51:25, :100:53, :142:{32,50}, :144:35, :146:35]
  wire        _GEN_5 = _GEN_2 & req_index == 2'h2;	// @[src/main/cache/iCache.scala:41:32, :51:25, :100:53, :142:{32,50}, :144:35, :146:35]
  wire        _GEN_6 = _GEN_2 & (&req_index);	// @[src/main/cache/iCache.scala:41:32, :51:25, :142:{32,50}, :144:35, :146:35]
  always @(posedge clock) begin	// @[src/main/cache/iCache.scala:25:7]
    if (is_hit_handshake)	// @[src/main/cache/iCache.scala:72:32]
      send_rdata <= hit ? casez_tmp_1 : 32'h0;	// @[src/main/cache/iCache.scala:29:25, :51:61, :63:{43,55}, :76:24]
    else if (is_ifu_r_fire)	// @[src/main/cache/iCache.scala:74:38]
      send_rdata <= io_out_rdata;	// @[src/main/cache/iCache.scala:29:25]
    if (is_ifu_ar_fire)	// @[src/main/cache/iCache.scala:71:40]
      send_araddr <= io_in_araddr;	// @[src/main/cache/iCache.scala:30:26]
    if (reset) begin	// @[src/main/cache/iCache.scala:25:7]
      count <= 1'h1;	// @[src/main/cache/iCache.scala:40:24]
      icache_0_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_0_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_0_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_1_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_1_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_1_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_2_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_2_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_2_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_3_set_0_valid <= 1'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_3_set_0_tag <= 28'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      icache_3_set_0_data_0 <= 32'h0;	// @[src/main/cache/iCache.scala:51:{25,61}]
      c_state <= 2'h0;	// @[src/main/cache/iCache.scala:56:26]
    end
    else begin	// @[src/main/cache/iCache.scala:25:7]
      icache_0_set_0_valid <= _GEN_3 | icache_0_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
      if (_GEN_3) begin	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
        icache_0_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:43:30, :51:25]
        icache_0_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:51:25]
      end
      icache_1_set_0_valid <= _GEN_4 | icache_1_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
      if (_GEN_4) begin	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
        icache_1_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:43:30, :51:25]
        icache_1_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:51:25]
      end
      icache_2_set_0_valid <= _GEN_5 | icache_2_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
      if (_GEN_5) begin	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
        icache_2_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:43:30, :51:25]
        icache_2_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:51:25]
      end
      icache_3_set_0_valid <= _GEN_6 | icache_3_set_0_valid;	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
      if (_GEN_6) begin	// @[src/main/cache/iCache.scala:51:25, :142:50, :144:35]
        icache_3_set_0_tag <= req_tag;	// @[src/main/cache/iCache.scala:43:30, :51:25]
        icache_3_set_0_data_0 <= io_out_rdata;	// @[src/main/cache/iCache.scala:51:25]
      end
      c_state <= n_state;	// @[src/main/cache/iCache.scala:56:26, :57:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/cache/iCache.scala:25:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/cache/iCache.scala:25:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/cache/iCache.scala:25:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:9];	// @[src/main/cache/iCache.scala:25:7]
    initial begin	// @[src/main/cache/iCache.scala:25:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/cache/iCache.scala:25:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/cache/iCache.scala:25:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/cache/iCache.scala:25:7]
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/cache/iCache.scala:25:7]
        end	// @[src/main/cache/iCache.scala:25:7]
        send_rdata = _RANDOM[4'h0];	// @[src/main/cache/iCache.scala:25:7, :29:25]
        send_araddr = _RANDOM[4'h1];	// @[src/main/cache/iCache.scala:25:7, :30:26]
        count = _RANDOM[4'h2][0];	// @[src/main/cache/iCache.scala:25:7, :40:24]
        icache_0_set_0_valid = _RANDOM[4'h2][1];	// @[src/main/cache/iCache.scala:25:7, :40:24, :51:25]
        icache_0_set_0_tag = _RANDOM[4'h2][29:2];	// @[src/main/cache/iCache.scala:25:7, :40:24, :51:25]
        icache_0_set_0_data_0 = {_RANDOM[4'h2][31:30], _RANDOM[4'h3][29:0]};	// @[src/main/cache/iCache.scala:25:7, :40:24, :51:25]
        icache_1_set_0_valid = _RANDOM[4'h3][30];	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_1_set_0_tag = {_RANDOM[4'h3][31], _RANDOM[4'h4][26:0]};	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_1_set_0_data_0 = {_RANDOM[4'h4][31:27], _RANDOM[4'h5][26:0]};	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_2_set_0_valid = _RANDOM[4'h5][27];	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_2_set_0_tag = {_RANDOM[4'h5][31:28], _RANDOM[4'h6][23:0]};	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_2_set_0_data_0 = {_RANDOM[4'h6][31:24], _RANDOM[4'h7][23:0]};	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_3_set_0_valid = _RANDOM[4'h7][24];	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_3_set_0_tag = {_RANDOM[4'h7][31:25], _RANDOM[4'h8][20:0]};	// @[src/main/cache/iCache.scala:25:7, :51:25]
        icache_3_set_0_data_0 = {_RANDOM[4'h8][31:21], _RANDOM[4'h9][20:0]};	// @[src/main/cache/iCache.scala:25:7, :51:25]
        c_state = _RANDOM[4'h9][22:21];	// @[src/main/cache/iCache.scala:25:7, :51:25, :56:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/cache/iCache.scala:25:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/cache/iCache.scala:25:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_arready = io_in_arready_0;	// @[src/main/cache/iCache.scala:25:7, :106:20, :111:27]
  assign io_in_rdata = send_rdata;	// @[src/main/cache/iCache.scala:25:7, :29:25]
  assign io_in_rvalid = io_in_rvalid_0;	// @[src/main/cache/iCache.scala:25:7, :106:20, :110:26]
  assign io_out_araddr = send_araddr;	// @[src/main/cache/iCache.scala:25:7, :30:26]
  assign io_out_arvalid = io_out_arvalid_0;	// @[src/main/cache/iCache.scala:25:7, :106:20, :179:24]
  assign io_out_arsize = _GEN_1 ? 3'h0 : {1'h0, _GEN_0, 1'h0};	// @[src/main/cache/iCache.scala:25:7, :51:61, :106:20, :182:23, :203:25]
  assign io_out_arburst = _GEN_1 ? 2'h0 : {1'h0, _GEN_0};	// @[src/main/cache/iCache.scala:25:7, :51:61, :56:26, :106:20, :182:23, :183:24, :203:25, :204:25]
  assign io_out_rready = ~_GEN_1 & _GEN_0 & io_in_rready;	// @[src/main/cache/iCache.scala:25:7, :106:20, :182:23, :184:23, :203:25]
endmodule

