// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module LSU(	// @[src/main/core/lsu/LSU.scala:40:7]
  input         clock,	// @[src/main/core/lsu/LSU.scala:40:7]
                reset,	// @[src/main/core/lsu/LSU.scala:40:7]
  output [31:0] io_dmem_araddr,	// @[src/main/core/lsu/LSU.scala:41:16]
  output        io_dmem_arvalid,	// @[src/main/core/lsu/LSU.scala:41:16]
  input         io_dmem_arready,	// @[src/main/core/lsu/LSU.scala:41:16]
  output [2:0]  io_dmem_arsize,	// @[src/main/core/lsu/LSU.scala:41:16]
  input  [31:0] io_dmem_rdata,	// @[src/main/core/lsu/LSU.scala:41:16]
  input  [1:0]  io_dmem_rresp,	// @[src/main/core/lsu/LSU.scala:41:16]
  input         io_dmem_rvalid,	// @[src/main/core/lsu/LSU.scala:41:16]
  output        io_dmem_rready,	// @[src/main/core/lsu/LSU.scala:41:16]
  output [31:0] io_dmem_awaddr,	// @[src/main/core/lsu/LSU.scala:41:16]
  output        io_dmem_awvalid,	// @[src/main/core/lsu/LSU.scala:41:16]
  input         io_dmem_awready,	// @[src/main/core/lsu/LSU.scala:41:16]
  output [2:0]  io_dmem_awsize,	// @[src/main/core/lsu/LSU.scala:41:16]
  output [31:0] io_dmem_wdata,	// @[src/main/core/lsu/LSU.scala:41:16]
  output [3:0]  io_dmem_wstrb,	// @[src/main/core/lsu/LSU.scala:41:16]
  output        io_dmem_wvalid,	// @[src/main/core/lsu/LSU.scala:41:16]
  input         io_dmem_wready,	// @[src/main/core/lsu/LSU.scala:41:16]
  input  [1:0]  io_dmem_bresp,	// @[src/main/core/lsu/LSU.scala:41:16]
  input         io_dmem_bvalid,	// @[src/main/core/lsu/LSU.scala:41:16]
  output        io_dmem_bready,	// @[src/main/core/lsu/LSU.scala:41:16]
                io_pipe_in_ready,	// @[src/main/core/lsu/LSU.scala:42:21]
  input         io_pipe_in_valid,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [31:0] io_pipe_in_bits_exe2ls_reg_pc,	// @[src/main/core/lsu/LSU.scala:42:21]
                io_pipe_in_bits_exe2ls_op1_data,	// @[src/main/core/lsu/LSU.scala:42:21]
                io_pipe_in_bits_exe2ls_rs2_data,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [3:0]  io_pipe_in_bits_exe2ls_wb_addr,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [31:0] io_pipe_in_bits_exe2ls_alu_out,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [1:0]  io_pipe_in_bits_exe2ls_rf_wen,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [2:0]  io_pipe_in_bits_exe2ls_wb_sel,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [11:0] io_pipe_in_bits_exe2ls_csr_addr,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [2:0]  io_pipe_in_bits_exe2ls_csr_cmd,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [1:0]  io_pipe_in_bits_exe2ls_mem_wen,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [2:0]  io_pipe_in_bits_exe2ls_mem_op,	// @[src/main/core/lsu/LSU.scala:42:21]
  input         io_pipe_in_bits_exe2ls_is_irq,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [3:0]  io_pipe_in_bits_exe2ls_irq_num,	// @[src/main/core/lsu/LSU.scala:42:21]
  input  [31:0] io_pipe_in_bits_exe2ls_csr_rdata,	// @[src/main/core/lsu/LSU.scala:42:21]
  input         io_pipe_out_ready,	// @[src/main/core/lsu/LSU.scala:42:21]
  output        io_pipe_out_valid,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [31:0] io_pipe_out_bits_ls2wb_reg_pc,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [3:0]  io_pipe_out_bits_ls2wb_wb_addr,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [1:0]  io_pipe_out_bits_ls2wb_rf_wen,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [31:0] io_pipe_out_bits_ls2wb_wb_data,	// @[src/main/core/lsu/LSU.scala:42:21]
                io_pipe_out_bits_ls2wb_csr_wdata,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [11:0] io_pipe_out_bits_ls2wb_csr_addr,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [2:0]  io_pipe_out_bits_ls2wb_csr_cmd,	// @[src/main/core/lsu/LSU.scala:42:21]
  output        io_pipe_out_bits_ls2wb_is_irq,	// @[src/main/core/lsu/LSU.scala:42:21]
  output [3:0]  io_pipe_out_bits_ls2wb_irq_num,	// @[src/main/core/lsu/LSU.scala:42:21]
  input         io_hazard_flush_flg	// @[src/main/core/lsu/LSU.scala:44:23]
);

  wire [31:0] dmem_rdata_processed;	// @[src/main/core/lsu/LSU.scala:232:43, :234:34]
  wire        bready;	// @[src/main/core/lsu/LSU.scala:132:81]
  wire        rready;	// @[src/main/core/lsu/LSU.scala:131:81]
  wire        out_valid;	// @[src/main/core/lsu/LSU.scala:130:32]
  wire        in_ready;	// @[src/main/core/lsu/LSU.scala:129:28]
  wire        isS =
    ~(&io_pipe_in_bits_exe2ls_mem_op) & io_pipe_in_bits_exe2ls_mem_wen == 2'h1;	// @[src/main/core/lsu/LSU.scala:56:47, :57:{15,22,56}]
  wire        isL =
    ~(&io_pipe_in_bits_exe2ls_mem_op) & io_pipe_in_bits_exe2ls_mem_wen == 2'h0;	// @[src/main/core/lsu/LSU.scala:56:47, :57:15, :58:{22,56}]
  reg  [31:0] araddr;	// @[src/main/core/lsu/LSU.scala:68:25]
  reg         arvalid;	// @[src/main/core/lsu/LSU.scala:69:26]
  reg  [1:0]  arsize;	// @[src/main/core/lsu/LSU.scala:70:25]
  reg  [31:0] awaddr;	// @[src/main/core/lsu/LSU.scala:72:25]
  reg         awvalid;	// @[src/main/core/lsu/LSU.scala:73:26]
  reg  [1:0]  awsize;	// @[src/main/core/lsu/LSU.scala:74:25]
  reg  [62:0] wdata;	// @[src/main/core/lsu/LSU.scala:75:24]
  reg  [6:0]  wstrb;	// @[src/main/core/lsu/LSU.scala:76:24]
  reg         wvalid;	// @[src/main/core/lsu/LSU.scala:77:25]
  reg  [1:0]  c_state;	// @[src/main/core/lsu/LSU.scala:92:26]
  wire        AXI_RorB_fire = io_dmem_rvalid & rready | io_dmem_bvalid & bready;	// @[src/main/core/lsu/LSU.scala:97:{41,51,69}, :131:81, :132:81]
  reg  [1:0]  casez_tmp;	// @[src/main/core/lsu/LSU.scala:106:51]
  always_comb begin	// @[src/main/core/lsu/LSU.scala:106:51]
    casez (c_state)	// @[src/main/core/lsu/LSU.scala:92:26, :106:51]
      2'b00:
        casez_tmp =
          in_ready & io_pipe_in_valid & ~io_hazard_flush_flg
            ? {1'h0, ~(&io_pipe_in_bits_exe2ls_mem_op)}
            : 2'h0;	// @[src/main/core/lsu/LSU.scala:47:18, :56:47, :58:56, :66:38, :106:51, :107:{44,61,77}, :129:28]
      2'b01:
        casez_tmp =
          arvalid & io_dmem_arready | awvalid & io_dmem_awready & wvalid & io_dmem_wready
            ? 2'h2
            : 2'h1;	// @[src/main/core/lsu/LSU.scala:57:56, :69:26, :73:26, :77:25, :96:{37,56,87}, :106:51, :108:44]
      2'b10:
        casez_tmp =
          AXI_RorB_fire & ~io_hazard_flush_flg
            ? 2'h0
            : ~AXI_RorB_fire & io_hazard_flush_flg
                ? 2'h3
                : {~(AXI_RorB_fire & io_hazard_flush_flg), 1'h0};	// @[src/main/core/lsu/LSU.scala:47:18, :58:56, :66:38, :97:51, :100:40, :101:{27,42}, :102:38, :106:51, :109:{44,79,109}]
      default:
        casez_tmp = AXI_RorB_fire ? 2'h0 : 2'h3;	// @[src/main/core/lsu/LSU.scala:58:56, :97:51, :106:51, :109:79, :110:44]
    endcase	// @[src/main/core/lsu/LSU.scala:92:26, :106:51]
  end // always_comb
  wire [1:0]  n_state = casez_tmp;	// @[src/main/core/lsu/LSU.scala:93:30, :106:51]
  wire        _arsize_func_T_2 = io_pipe_in_bits_exe2ls_mem_op == 3'h4;	// @[src/main/core/lsu/LSU.scala:40:7, :116:68]
  wire        _awsize_func_T_2 = io_pipe_in_bits_exe2ls_mem_op == 3'h1;	// @[src/main/core/lsu/LSU.scala:40:7, :116:68]
  wire        _arsize_func_T_6 = io_pipe_in_bits_exe2ls_mem_op == 3'h5;	// @[src/main/core/lsu/LSU.scala:40:7, :116:68]
  wire        _awsize_func_T_4 = io_pipe_in_bits_exe2ls_mem_op == 3'h2;	// @[src/main/core/lsu/LSU.scala:40:7, :116:68]
  assign in_ready = ~out_valid | io_pipe_out_ready;	// @[src/main/core/lsu/LSU.scala:129:{17,28}, :130:32]
  assign out_valid = AXI_RorB_fire | (&io_pipe_in_bits_exe2ls_mem_op) & io_pipe_in_valid;	// @[src/main/core/lsu/LSU.scala:56:47, :97:51, :130:{32,42}]
  wire        _bready_T = c_state == 2'h2;	// @[src/main/core/lsu/LSU.scala:92:26, :108:44, :131:31]
  assign rready = (isL & _bready_T | (&c_state)) & io_pipe_out_ready;	// @[src/main/core/lsu/LSU.scala:58:22, :92:26, :131:{20,31,57,68,81}]
  assign bready = (isS & _bready_T | (&c_state)) & io_pipe_out_ready;	// @[src/main/core/lsu/LSU.scala:57:22, :92:26, :131:{31,68}, :132:{20,57,81}]
  reg  [1:0]  casez_tmp_0;	// @[src/main/core/lsu/LSU.scala:134:20, :145:20]
  wire [1:0]  arsize_func =
    _awsize_func_T_4
      ? 2'h2
      : _arsize_func_T_6 | _awsize_func_T_2
          ? 2'h1
          : {~(_arsize_func_T_2 | ~(|io_pipe_in_bits_exe2ls_mem_op)), 1'h0};	// @[src/main/core/lsu/LSU.scala:47:18, :57:56, :108:44, :116:68]
  always_comb begin	// @[src/main/core/lsu/LSU.scala:70:25, :134:20, :145:20, :154:20, :167:20, :184:20]
    casez (n_state)	// @[src/main/core/lsu/LSU.scala:70:25, :93:30, :134:20, :145:20, :154:20, :167:20, :184:20]
      2'b00:
        casez_tmp_0 = 2'h2;	// @[src/main/core/lsu/LSU.scala:70:25, :108:44, :134:20, :145:20, :154:20, :167:20, :184:20]
      2'b01:
        casez_tmp_0 = arsize_func;	// @[src/main/core/lsu/LSU.scala:70:25, :116:68, :134:20, :145:20, :154:20, :167:20, :184:20]
      2'b10:
        casez_tmp_0 = arsize_func;	// @[src/main/core/lsu/LSU.scala:70:25, :116:68, :134:20, :145:20, :154:20, :167:20, :184:20]
      default:
        casez_tmp_0 = 2'h2;	// @[src/main/core/lsu/LSU.scala:70:25, :108:44, :134:20, :145:20, :154:20, :167:20, :184:20]
    endcase	// @[src/main/core/lsu/LSU.scala:70:25, :93:30, :134:20, :145:20, :154:20, :167:20, :184:20]
  end // always_comb
  reg  [1:0]  casez_tmp_1;	// @[src/main/core/lsu/LSU.scala:134:20, :146:20]
  wire [1:0]  awsize_func =
    _awsize_func_T_4
      ? 2'h2
      : _awsize_func_T_2 ? 2'h1 : {|io_pipe_in_bits_exe2ls_mem_op, 1'h0};	// @[src/main/core/lsu/LSU.scala:47:18, :57:56, :108:44, :116:68, :123:68]
  always_comb begin	// @[src/main/core/lsu/LSU.scala:74:25, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
    casez (n_state)	// @[src/main/core/lsu/LSU.scala:74:25, :93:30, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
      2'b00:
        casez_tmp_1 = 2'h2;	// @[src/main/core/lsu/LSU.scala:74:25, :108:44, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
      2'b01:
        casez_tmp_1 = awsize_func;	// @[src/main/core/lsu/LSU.scala:74:25, :123:68, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
      2'b10:
        casez_tmp_1 = awsize_func;	// @[src/main/core/lsu/LSU.scala:74:25, :123:68, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
      default:
        casez_tmp_1 = 2'h2;	// @[src/main/core/lsu/LSU.scala:74:25, :108:44, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
    endcase	// @[src/main/core/lsu/LSU.scala:74:25, :93:30, :134:20, :146:20, :154:20, :157:20, :167:20, :170:20, :185:20]
  end // always_comb
  wire        _GEN = io_pipe_in_bits_exe2ls_mem_op == 3'h1;	// @[src/main/core/lsu/LSU.scala:40:7, :218:43]
  wire        _GEN_0 = io_pipe_in_bits_exe2ls_mem_op == 3'h2;	// @[src/main/core/lsu/LSU.scala:40:7, :218:43]
  wire [31:0] shift_rdata =
    io_dmem_rdata >> {27'h0, io_pipe_in_bits_exe2ls_alu_out[1:0], 3'h0};	// @[src/main/core/lsu/LSU.scala:40:7, :231:{37,71}]
  assign dmem_rdata_processed =
    (|io_pipe_in_bits_exe2ls_mem_op)
      ? (_GEN
           ? {{16{shift_rdata[15]}}, shift_rdata[15:0]}
           : _GEN_0
               ? shift_rdata
               : _arsize_func_T_2
                   ? {24'h0, shift_rdata[7:0]}
                   : _arsize_func_T_6 ? {16'h0, shift_rdata[15:0]} : 32'h0)
      : {{24{shift_rdata[7]}}, shift_rdata[7:0]};	// @[src/main/core/lsu/LSU.scala:116:68, :204:43, :218:43, :231:37, :232:43, :234:{34,40,45,61,78}, :237:{34,40,45,61,79}, :240:34, :243:{34,40,67}, :246:{34,40,67}]
  wire        is_laf = io_dmem_rvalid & (|io_dmem_rresp);	// @[src/main/core/lsu/LSU.scala:271:{33,50}]
  wire        is_saf = io_dmem_bvalid & (|io_dmem_bresp);	// @[src/main/core/lsu/LSU.scala:272:{33,50}]
  wire        _GEN_1 = n_state == 2'h1;	// @[src/main/core/lsu/LSU.scala:57:56, :93:30, :134:20]
  wire        _GEN_2 = n_state == 2'h2 | (&n_state);	// @[src/main/core/lsu/LSU.scala:69:26, :93:30, :108:44, :134:20, :166:21, :179:21]
  always @(posedge clock) begin	// @[src/main/core/lsu/LSU.scala:40:7]
    if (reset) begin	// @[src/main/core/lsu/LSU.scala:40:7]
      araddr <= 32'h0;	// @[src/main/core/lsu/LSU.scala:68:25, :204:43]
      arvalid <= 1'h0;	// @[src/main/core/lsu/LSU.scala:47:18, :69:26]
      arsize <= 2'h0;	// @[src/main/core/lsu/LSU.scala:58:56, :70:25]
      awaddr <= 32'h0;	// @[src/main/core/lsu/LSU.scala:72:25, :204:43]
      awvalid <= 1'h0;	// @[src/main/core/lsu/LSU.scala:47:18, :73:26]
      awsize <= 2'h0;	// @[src/main/core/lsu/LSU.scala:58:56, :74:25]
      wdata <= 63'h0;	// @[src/main/core/lsu/LSU.scala:75:24]
      wstrb <= 7'h0;	// @[src/main/core/lsu/LSU.scala:76:24]
      wvalid <= 1'h0;	// @[src/main/core/lsu/LSU.scala:47:18, :77:25]
      c_state <= 2'h0;	// @[src/main/core/lsu/LSU.scala:58:56, :92:26]
    end
    else begin	// @[src/main/core/lsu/LSU.scala:40:7]
      araddr <= io_pipe_in_bits_exe2ls_alu_out;	// @[src/main/core/lsu/LSU.scala:68:25]
      arvalid <= (|n_state) & (_GEN_1 ? isL : ~_GEN_2 & arvalid);	// @[src/main/core/lsu/LSU.scala:58:22, :69:26, :93:30, :134:20, :140:21, :153:21, :166:21, :179:21]
      arsize <= casez_tmp_0;	// @[src/main/core/lsu/LSU.scala:70:25, :134:20, :145:20]
      awaddr <= io_pipe_in_bits_exe2ls_alu_out;	// @[src/main/core/lsu/LSU.scala:72:25]
      awvalid <= (|n_state) & (_GEN_1 ? isS : ~_GEN_2 & awvalid);	// @[src/main/core/lsu/LSU.scala:57:22, :69:26, :73:26, :93:30, :134:20, :142:21, :156:21, :166:21, :169:21, :179:21, :181:21]
      awsize <= casez_tmp_1;	// @[src/main/core/lsu/LSU.scala:74:25, :134:20, :146:20]
      wdata <=
        {31'h0, io_pipe_in_bits_exe2ls_rs2_data}
        << {58'h0, io_pipe_in_bits_exe2ls_alu_out[1:0], 3'h0};	// @[src/main/core/lsu/LSU.scala:40:7, :68:25, :75:24, :231:71, :253:46]
      if (|io_pipe_in_bits_exe2ls_mem_op) begin	// @[src/main/core/lsu/LSU.scala:116:68]
        if (_GEN)	// @[src/main/core/lsu/LSU.scala:218:43]
          wstrb <= {2'h0, 5'h3 << io_pipe_in_bits_exe2ls_alu_out[1:0]};	// @[src/main/core/lsu/LSU.scala:58:56, :76:24, :218:43, :223:{19,36,69}]
        else if (_GEN_0)	// @[src/main/core/lsu/LSU.scala:218:43]
          wstrb <= 7'hF << io_pipe_in_bits_exe2ls_alu_out[1:0];	// @[src/main/core/lsu/LSU.scala:76:24, :226:{36,69}]
      end
      else	// @[src/main/core/lsu/LSU.scala:116:68]
        wstrb <= {3'h0, 4'h1 << io_pipe_in_bits_exe2ls_alu_out[1:0]};	// @[src/main/core/lsu/LSU.scala:40:7, :76:24, :218:43, :220:{19,36,69}]
      wvalid <= (|n_state) & (_GEN_1 ? isS : ~_GEN_2 & wvalid);	// @[src/main/core/lsu/LSU.scala:57:22, :69:26, :77:25, :93:30, :134:20, :143:20, :158:20, :166:21, :171:20, :179:21, :182:20]
      c_state <= n_state;	// @[src/main/core/lsu/LSU.scala:92:26, :93:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/lsu/LSU.scala:40:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/lsu/LSU.scala:40:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/lsu/LSU.scala:40:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// @[src/main/core/lsu/LSU.scala:40:7]
    initial begin	// @[src/main/core/lsu/LSU.scala:40:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/lsu/LSU.scala:40:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/lsu/LSU.scala:40:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/lsu/LSU.scala:40:7]
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/core/lsu/LSU.scala:40:7]
        end	// @[src/main/core/lsu/LSU.scala:40:7]
        araddr = _RANDOM[3'h0];	// @[src/main/core/lsu/LSU.scala:40:7, :68:25]
        arvalid = _RANDOM[3'h1][0];	// @[src/main/core/lsu/LSU.scala:40:7, :69:26]
        arsize = _RANDOM[3'h1][2:1];	// @[src/main/core/lsu/LSU.scala:40:7, :69:26, :70:25]
        awaddr = {_RANDOM[3'h1][31:3], _RANDOM[3'h2][2:0]};	// @[src/main/core/lsu/LSU.scala:40:7, :69:26, :72:25]
        awvalid = _RANDOM[3'h2][3];	// @[src/main/core/lsu/LSU.scala:40:7, :72:25, :73:26]
        awsize = _RANDOM[3'h2][5:4];	// @[src/main/core/lsu/LSU.scala:40:7, :72:25, :74:25]
        wdata = {_RANDOM[3'h2][31:6], _RANDOM[3'h3], _RANDOM[3'h4][4:0]};	// @[src/main/core/lsu/LSU.scala:40:7, :72:25, :75:24]
        wstrb = _RANDOM[3'h4][11:5];	// @[src/main/core/lsu/LSU.scala:40:7, :75:24, :76:24]
        wvalid = _RANDOM[3'h4][12];	// @[src/main/core/lsu/LSU.scala:40:7, :75:24, :77:25]
        c_state = _RANDOM[3'h4][14:13];	// @[src/main/core/lsu/LSU.scala:40:7, :75:24, :92:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/lsu/LSU.scala:40:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/lsu/LSU.scala:40:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_dmem_araddr = araddr;	// @[src/main/core/lsu/LSU.scala:40:7, :68:25]
  assign io_dmem_arvalid = arvalid;	// @[src/main/core/lsu/LSU.scala:40:7, :69:26]
  assign io_dmem_arsize = {1'h0, arsize};	// @[src/main/core/lsu/LSU.scala:40:7, :47:18, :70:25, :81:20]
  assign io_dmem_rready = rready;	// @[src/main/core/lsu/LSU.scala:40:7, :131:81]
  assign io_dmem_awaddr = awaddr;	// @[src/main/core/lsu/LSU.scala:40:7, :72:25]
  assign io_dmem_awvalid = awvalid;	// @[src/main/core/lsu/LSU.scala:40:7, :73:26]
  assign io_dmem_awsize = {1'h0, awsize};	// @[src/main/core/lsu/LSU.scala:40:7, :47:18, :74:25, :85:20]
  assign io_dmem_wdata = wdata[31:0];	// @[src/main/core/lsu/LSU.scala:40:7, :75:24, :86:21]
  assign io_dmem_wstrb = wstrb[3:0];	// @[src/main/core/lsu/LSU.scala:40:7, :76:24, :87:21]
  assign io_dmem_wvalid = wvalid;	// @[src/main/core/lsu/LSU.scala:40:7, :77:25]
  assign io_dmem_bready = bready;	// @[src/main/core/lsu/LSU.scala:40:7, :132:81]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/lsu/LSU.scala:40:7, :129:28]
  assign io_pipe_out_valid = out_valid & ~io_hazard_flush_flg;	// @[src/main/core/lsu/LSU.scala:40:7, :66:{36,38}, :130:32]
  assign io_pipe_out_bits_ls2wb_reg_pc = io_pipe_in_bits_exe2ls_reg_pc;	// @[src/main/core/lsu/LSU.scala:40:7]
  assign io_pipe_out_bits_ls2wb_wb_addr = io_pipe_in_bits_exe2ls_wb_addr;	// @[src/main/core/lsu/LSU.scala:40:7]
  assign io_pipe_out_bits_ls2wb_rf_wen = io_pipe_in_bits_exe2ls_rf_wen;	// @[src/main/core/lsu/LSU.scala:40:7]
  assign io_pipe_out_bits_ls2wb_wb_data =
    io_pipe_in_bits_exe2ls_wb_sel == 3'h1
      ? dmem_rdata_processed
      : io_pipe_in_bits_exe2ls_wb_sel == 3'h2
          ? io_pipe_in_bits_exe2ls_reg_pc + 32'h4
          : io_pipe_in_bits_exe2ls_wb_sel == 3'h3
              ? io_pipe_in_bits_exe2ls_csr_rdata
              : io_pipe_in_bits_exe2ls_alu_out;	// @[src/main/core/lsu/LSU.scala:40:7, :213:40, :214:{40,86}, :215:40, :232:43, :234:34, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_pipe_out_bits_ls2wb_csr_wdata =
    io_pipe_in_bits_exe2ls_csr_cmd == 3'h1
      ? io_pipe_in_bits_exe2ls_op1_data
      : io_pipe_in_bits_exe2ls_csr_cmd == 3'h2
          ? io_pipe_in_bits_exe2ls_csr_rdata | io_pipe_in_bits_exe2ls_op1_data
          : io_pipe_in_bits_exe2ls_csr_cmd == 3'h3
              ? io_pipe_in_bits_exe2ls_csr_rdata & ~io_pipe_in_bits_exe2ls_op1_data
              : io_pipe_in_bits_exe2ls_csr_cmd == 3'h4 ? 32'hB : 32'h0;	// @[src/main/core/lsu/LSU.scala:40:7, :204:43, :206:41, :207:{41,89}, :208:{41,89,91}, :209:41, src/main/scala/chisel3/util/Mux.scala:126:16]
  assign io_pipe_out_bits_ls2wb_csr_addr = io_pipe_in_bits_exe2ls_csr_addr;	// @[src/main/core/lsu/LSU.scala:40:7]
  assign io_pipe_out_bits_ls2wb_csr_cmd = io_pipe_in_bits_exe2ls_csr_cmd;	// @[src/main/core/lsu/LSU.scala:40:7]
  assign io_pipe_out_bits_ls2wb_is_irq = is_laf | is_saf | io_pipe_in_bits_exe2ls_is_irq;	// @[src/main/core/lsu/LSU.scala:40:7, :271:33, :272:33, :273:54]
  assign io_pipe_out_bits_ls2wb_irq_num =
    is_laf ? 4'h5 : is_saf ? 4'h7 : io_pipe_in_bits_exe2ls_irq_num;	// @[src/main/core/lsu/LSU.scala:40:7, :271:33, :272:33, :274:{42,67}]
endmodule

