// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Xbar(	// @[src/main/bus/Xbar.scala:21:7]
  input         clock,	// @[src/main/bus/Xbar.scala:21:7]
                reset,	// @[src/main/bus/Xbar.scala:21:7]
  input  [31:0] io_imem_araddr,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_imem_arvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_imem_arready,	// @[src/main/bus/Xbar.scala:22:16]
  input  [3:0]  io_imem_arid,	// @[src/main/bus/Xbar.scala:22:16]
  input  [7:0]  io_imem_arlen,	// @[src/main/bus/Xbar.scala:22:16]
  input  [2:0]  io_imem_arsize,	// @[src/main/bus/Xbar.scala:22:16]
  input  [1:0]  io_imem_arburst,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_imem_rdata,	// @[src/main/bus/Xbar.scala:22:16]
  output [1:0]  io_imem_rresp,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_imem_rvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_imem_rready,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_imem_awaddr,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_imem_awvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input  [3:0]  io_imem_awid,	// @[src/main/bus/Xbar.scala:22:16]
  input  [7:0]  io_imem_awlen,	// @[src/main/bus/Xbar.scala:22:16]
  input  [2:0]  io_imem_awsize,	// @[src/main/bus/Xbar.scala:22:16]
  input  [1:0]  io_imem_awburst,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_imem_wdata,	// @[src/main/bus/Xbar.scala:22:16]
  input  [3:0]  io_imem_wstrb,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_imem_wvalid,	// @[src/main/bus/Xbar.scala:22:16]
                io_imem_wlast,	// @[src/main/bus/Xbar.scala:22:16]
                io_imem_bready,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_dmem_araddr,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_dmem_arvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_dmem_arready,	// @[src/main/bus/Xbar.scala:22:16]
  input  [2:0]  io_dmem_arsize,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_dmem_rdata,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_dmem_rvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_dmem_rready,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_dmem_awaddr,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_dmem_awvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_dmem_awready,	// @[src/main/bus/Xbar.scala:22:16]
  input  [2:0]  io_dmem_awsize,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_dmem_wdata,	// @[src/main/bus/Xbar.scala:22:16]
  input  [3:0]  io_dmem_wstrb,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_dmem_wvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_dmem_wready,	// @[src/main/bus/Xbar.scala:22:16]
                io_dmem_bvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_dmem_bready,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_soc_araddr,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_soc_arvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_soc_arready,	// @[src/main/bus/Xbar.scala:22:16]
  output [3:0]  io_soc_arid,	// @[src/main/bus/Xbar.scala:22:16]
  output [7:0]  io_soc_arlen,	// @[src/main/bus/Xbar.scala:22:16]
  output [2:0]  io_soc_arsize,	// @[src/main/bus/Xbar.scala:22:16]
  output [1:0]  io_soc_arburst,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_soc_rdata,	// @[src/main/bus/Xbar.scala:22:16]
  input  [1:0]  io_soc_rresp,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_soc_rvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_soc_rready,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_soc_awaddr,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_soc_awvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_soc_awready,	// @[src/main/bus/Xbar.scala:22:16]
  output [3:0]  io_soc_awid,	// @[src/main/bus/Xbar.scala:22:16]
  output [7:0]  io_soc_awlen,	// @[src/main/bus/Xbar.scala:22:16]
  output [2:0]  io_soc_awsize,	// @[src/main/bus/Xbar.scala:22:16]
  output [1:0]  io_soc_awburst,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_soc_wdata,	// @[src/main/bus/Xbar.scala:22:16]
  output [3:0]  io_soc_wstrb,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_soc_wvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_soc_wready,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_soc_wlast,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_soc_bvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_soc_bready,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_clint_araddr,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_clint_arvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_clint_arready,	// @[src/main/bus/Xbar.scala:22:16]
  output [3:0]  io_clint_arid,	// @[src/main/bus/Xbar.scala:22:16]
  output [7:0]  io_clint_arlen,	// @[src/main/bus/Xbar.scala:22:16]
  output [2:0]  io_clint_arsize,	// @[src/main/bus/Xbar.scala:22:16]
  output [1:0]  io_clint_arburst,	// @[src/main/bus/Xbar.scala:22:16]
  input  [31:0] io_clint_rdata,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_clint_rvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_clint_rready,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_clint_awaddr,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_clint_awvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_clint_awready,	// @[src/main/bus/Xbar.scala:22:16]
  output [3:0]  io_clint_awid,	// @[src/main/bus/Xbar.scala:22:16]
  output [7:0]  io_clint_awlen,	// @[src/main/bus/Xbar.scala:22:16]
  output [2:0]  io_clint_awsize,	// @[src/main/bus/Xbar.scala:22:16]
  output [1:0]  io_clint_awburst,	// @[src/main/bus/Xbar.scala:22:16]
  output [31:0] io_clint_wdata,	// @[src/main/bus/Xbar.scala:22:16]
  output [3:0]  io_clint_wstrb,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_clint_wvalid,	// @[src/main/bus/Xbar.scala:22:16]
  input         io_clint_wready,	// @[src/main/bus/Xbar.scala:22:16]
                io_clint_bvalid,	// @[src/main/bus/Xbar.scala:22:16]
  output        io_clint_bready	// @[src/main/bus/Xbar.scala:22:16]
);

  wire        ready;	// @[src/main/bus/Xbar.scala:156:60]
  reg         imem_arready;	// @[src/main/bus/Xbar.scala:26:31]
  reg  [31:0] imem_rdata;	// @[src/main/bus/Xbar.scala:27:29]
  reg  [1:0]  imem_rresp;	// @[src/main/bus/Xbar.scala:28:29]
  reg         imem_rvalid;	// @[src/main/bus/Xbar.scala:29:30]
  reg         dmem_arready;	// @[src/main/bus/Xbar.scala:49:31]
  reg  [31:0] dmem_rdata;	// @[src/main/bus/Xbar.scala:50:29]
  reg         dmem_rvalid;	// @[src/main/bus/Xbar.scala:52:30]
  reg         dmem_awready;	// @[src/main/bus/Xbar.scala:55:31]
  reg         dmem_wready;	// @[src/main/bus/Xbar.scala:56:30]
  reg         dmem_bvalid;	// @[src/main/bus/Xbar.scala:58:30]
  reg  [31:0] soc_araddr;	// @[src/main/bus/Xbar.scala:76:29]
  reg         soc_arvalid;	// @[src/main/bus/Xbar.scala:77:30]
  reg  [3:0]  soc_arid;	// @[src/main/bus/Xbar.scala:78:27]
  reg  [7:0]  soc_arlen;	// @[src/main/bus/Xbar.scala:79:28]
  reg  [2:0]  soc_arsize;	// @[src/main/bus/Xbar.scala:80:29]
  reg  [1:0]  soc_arburst;	// @[src/main/bus/Xbar.scala:81:30]
  reg         soc_rready;	// @[src/main/bus/Xbar.scala:82:29]
  reg  [31:0] soc_awaddr;	// @[src/main/bus/Xbar.scala:83:29]
  reg         soc_awvalid;	// @[src/main/bus/Xbar.scala:84:30]
  reg  [3:0]  soc_awid;	// @[src/main/bus/Xbar.scala:85:27]
  reg  [7:0]  soc_awlen;	// @[src/main/bus/Xbar.scala:86:28]
  reg  [2:0]  soc_awsize;	// @[src/main/bus/Xbar.scala:87:29]
  reg  [1:0]  soc_awburst;	// @[src/main/bus/Xbar.scala:88:30]
  reg  [31:0] soc_wdata;	// @[src/main/bus/Xbar.scala:89:28]
  reg  [3:0]  soc_wstrb;	// @[src/main/bus/Xbar.scala:90:28]
  reg         soc_wvalid;	// @[src/main/bus/Xbar.scala:91:29]
  reg         soc_wlast;	// @[src/main/bus/Xbar.scala:92:28]
  reg         soc_bready;	// @[src/main/bus/Xbar.scala:93:29]
  reg  [31:0] clint_araddr;	// @[src/main/bus/Xbar.scala:113:31]
  reg         clint_arvalid;	// @[src/main/bus/Xbar.scala:114:32]
  reg  [3:0]  clint_arid;	// @[src/main/bus/Xbar.scala:115:29]
  reg  [7:0]  clint_arlen;	// @[src/main/bus/Xbar.scala:116:30]
  reg  [2:0]  clint_arsize;	// @[src/main/bus/Xbar.scala:117:31]
  reg  [1:0]  clint_arburst;	// @[src/main/bus/Xbar.scala:118:32]
  reg         clint_rready;	// @[src/main/bus/Xbar.scala:119:31]
  reg  [31:0] clint_awaddr;	// @[src/main/bus/Xbar.scala:120:31]
  reg         clint_awvalid;	// @[src/main/bus/Xbar.scala:121:32]
  reg  [3:0]  clint_awid;	// @[src/main/bus/Xbar.scala:122:29]
  reg  [7:0]  clint_awlen;	// @[src/main/bus/Xbar.scala:123:30]
  reg  [2:0]  clint_awsize;	// @[src/main/bus/Xbar.scala:124:31]
  reg  [1:0]  clint_awburst;	// @[src/main/bus/Xbar.scala:125:32]
  reg  [31:0] clint_wdata;	// @[src/main/bus/Xbar.scala:126:30]
  reg  [3:0]  clint_wstrb;	// @[src/main/bus/Xbar.scala:127:30]
  reg         clint_wvalid;	// @[src/main/bus/Xbar.scala:128:31]
  reg         clint_bready;	// @[src/main/bus/Xbar.scala:130:31]
  reg  [2:0]  c_state;	// @[src/main/bus/Xbar.scala:152:26]
  wire [2:0]  n_state;	// @[src/main/bus/Xbar.scala:153:30]
  assign ready = n_state == 3'h3 & ~(|c_state) | n_state == 3'h1 & ~(|c_state);	// @[src/main/bus/Xbar.scala:152:26, :153:30, :156:{23,37,48,60,72,86}]
  reg  [2:0]  casez_tmp;	// @[src/main/bus/Xbar.scala:176:42]
  wire        isclint_raddr = (|(io_dmem_araddr[31:25])) & io_dmem_araddr < 32'h2010000;	// @[src/main/bus/Xbar.scala:158:{41,65,83}]
  wire        isclint_waddr = (|(io_dmem_awaddr[31:25])) & io_dmem_awaddr < 32'h2010000;	// @[src/main/bus/Xbar.scala:158:83, :159:{41,65,83}]
  wire        isdmem_req_w = io_dmem_awvalid & io_dmem_wvalid;	// @[src/main/bus/Xbar.scala:163:40]
  wire        soc_i_done0 = io_soc_rvalid & soc_rready;	// @[src/main/bus/Xbar.scala:82:29, :167:37]
  wire        _clint_done1_T = dmem_rvalid & io_dmem_rready;	// @[src/main/bus/Xbar.scala:52:30, :171:36]
  wire        _clint_done1_T_1 = dmem_bvalid & io_dmem_bready;	// @[src/main/bus/Xbar.scala:58:30, :171:69]
  wire [2:0]  _n_state_T_10 =
    (|c_state)
      ? 3'h0
      : io_imem_arvalid
          ? 3'h1
          : io_dmem_arvalid & ~isclint_raddr | isdmem_req_w & ~isclint_waddr
              ? 3'h3
              : io_dmem_arvalid & isclint_raddr | isdmem_req_w & isclint_waddr
                  ? 3'h5
                  : 3'h0;	// @[src/main/bus/Xbar.scala:152:26, :156:{23,48,72}, :158:65, :159:65, :163:40, :164:{36,38,54,70,72}, :165:{37,54,70}, :176:42, src/main/scala/chisel3/util/Mux.scala:126:16]
  always_comb begin	// @[src/main/bus/Xbar.scala:176:42]
    casez (c_state)	// @[src/main/bus/Xbar.scala:152:26, :176:42]
      3'b000:
        casez_tmp = _n_state_T_10;	// @[src/main/bus/Xbar.scala:176:42]
      3'b001:
        casez_tmp = soc_i_done0 ? 3'h2 : 3'h1;	// @[src/main/bus/Xbar.scala:156:72, :167:37, :176:42, :182:29]
      3'b010:
        casez_tmp = {1'h0, ~(imem_rvalid & io_imem_rready), 1'h0};	// @[src/main/bus/Xbar.scala:27:29, :29:30, :170:35, :176:42, :183:29]
      3'b011:
        casez_tmp = soc_i_done0 | io_soc_bvalid & soc_bready ? 3'h4 : 3'h3;	// @[src/main/bus/Xbar.scala:93:29, :156:23, :167:37, :168:{52,69}, :176:42, :184:29]
      3'b100:
        casez_tmp = {~(_clint_done1_T | _clint_done1_T_1), 2'h0};	// @[src/main/bus/Xbar.scala:22:16, :171:{36,54,69}, :176:42, :185:29]
      3'b101:
        casez_tmp =
          io_clint_rvalid & clint_rready | io_clint_bvalid & clint_bready ? 3'h6 : 3'h5;	// @[src/main/bus/Xbar.scala:119:31, :130:31, :169:{40,56,75}, :176:42, :186:29, src/main/scala/chisel3/util/Mux.scala:126:16]
      3'b110:
        casez_tmp = _clint_done1_T | _clint_done1_T_1 ? 3'h0 : 3'h6;	// @[src/main/bus/Xbar.scala:152:26, :171:{36,69}, :172:54, :176:42, :186:29, :187:29]
      default:
        casez_tmp = _n_state_T_10;	// @[src/main/bus/Xbar.scala:176:42]
    endcase	// @[src/main/bus/Xbar.scala:152:26, :176:42]
  end // always_comb
  assign n_state = casez_tmp;	// @[src/main/bus/Xbar.scala:153:30, :176:42]
  reg  [1:0]  casez_tmp_0;	// @[src/main/bus/Xbar.scala:190:20, :347:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:26:31, :27:29, :28:29, :153:30, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b000:
        casez_tmp_0 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b001:
        casez_tmp_0 = io_soc_rresp;	// @[src/main/bus/Xbar.scala:26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b010:
        casez_tmp_0 = io_soc_rresp;	// @[src/main/bus/Xbar.scala:26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b011:
        casez_tmp_0 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b100:
        casez_tmp_0 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b101:
        casez_tmp_0 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      3'b110:
        casez_tmp_0 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
      default:
        casez_tmp_0 = imem_rresp;	// @[src/main/bus/Xbar.scala:26:31, :27:29, :28:29, :190:20, :247:20, :248:20, :345:22, :347:20]
    endcase	// @[src/main/bus/Xbar.scala:26:31, :27:29, :28:29, :153:30, :190:20, :247:20, :248:20, :345:22, :347:20]
  end // always_comb
  reg  [31:0] casez_tmp_1;	// @[src/main/bus/Xbar.scala:190:20, :373:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :153:30, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
      3'b000:
        casez_tmp_1 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20, :394:22]
      3'b001:
        casez_tmp_1 = io_imem_araddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
      3'b010:
        casez_tmp_1 = io_imem_araddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
      3'b011:
        casez_tmp_1 = io_dmem_araddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
      3'b100:
        casez_tmp_1 = io_dmem_araddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
      3'b101:
        casez_tmp_1 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20, :394:22]
      3'b110:
        casez_tmp_1 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20, :394:22]
      default:
        casez_tmp_1 = soc_araddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :49:31, :76:29, :153:30, :190:20, :247:20, :258:20, :279:22, :291:20, :312:22, :373:20]
  end // always_comb
  reg  [3:0]  casez_tmp_2;	// @[src/main/bus/Xbar.scala:190:20, :375:18]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :78:27, :153:30, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b000:
        casez_tmp_2 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b001:
        casez_tmp_2 = io_imem_arid;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b010:
        casez_tmp_2 = io_imem_arid;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b011:
        casez_tmp_2 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b100:
        casez_tmp_2 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b101:
        casez_tmp_2 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      3'b110:
        casez_tmp_2 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
      default:
        casez_tmp_2 = soc_arid;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :190:20, :247:20, :260:18, :293:18, :375:18]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :78:27, :153:30, :190:20, :247:20, :260:18, :293:18, :375:18]
  end // always_comb
  reg  [7:0]  casez_tmp_3;	// @[src/main/bus/Xbar.scala:190:20, :376:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :78:27, :79:28, :153:30, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b000:
        casez_tmp_3 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b001:
        casez_tmp_3 = io_imem_arlen;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b010:
        casez_tmp_3 = io_imem_arlen;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b011:
        casez_tmp_3 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b100:
        casez_tmp_3 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b101:
        casez_tmp_3 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      3'b110:
        casez_tmp_3 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
      default:
        casez_tmp_3 = soc_arlen;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :79:28, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :78:27, :79:28, :153:30, :190:20, :247:20, :261:19, :293:18, :294:19, :375:18, :376:19]
  end // always_comb
  reg  [2:0]  casez_tmp_4;	// @[src/main/bus/Xbar.scala:190:20, :377:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :153:30, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b000:
        casez_tmp_4 = 3'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :152:26, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b001:
        casez_tmp_4 = io_imem_arsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b010:
        casez_tmp_4 = io_imem_arsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b011:
        casez_tmp_4 = io_dmem_arsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b100:
        casez_tmp_4 = io_dmem_arsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b101:
        casez_tmp_4 = 3'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :152:26, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      3'b110:
        casez_tmp_4 = 3'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :152:26, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
      default:
        casez_tmp_4 = soc_arsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :49:31, :80:29, :153:30, :190:20, :247:20, :262:20, :279:22, :295:20, :312:22, :377:20]
  end // always_comb
  reg  [1:0]  casez_tmp_5;	// @[src/main/bus/Xbar.scala:190:20, :378:21]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :78:27, :81:30, :153:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b000:
        casez_tmp_5 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b001:
        casez_tmp_5 = io_imem_arburst;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b010:
        casez_tmp_5 = io_imem_arburst;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b011:
        casez_tmp_5 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b100:
        casez_tmp_5 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b101:
        casez_tmp_5 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      3'b110:
        casez_tmp_5 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
      default:
        casez_tmp_5 = soc_arburst;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :81:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :78:27, :81:30, :153:30, :190:20, :247:20, :263:21, :293:18, :296:21, :375:18, :378:21]
  end // always_comb
  reg  [31:0] casez_tmp_6;	// @[src/main/bus/Xbar.scala:190:20, :380:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :153:30, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
      3'b000:
        casez_tmp_6 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20, :394:22]
      3'b001:
        casez_tmp_6 = io_imem_awaddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
      3'b010:
        casez_tmp_6 = io_imem_awaddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
      3'b011:
        casez_tmp_6 = io_dmem_awaddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
      3'b100:
        casez_tmp_6 = io_dmem_awaddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
      3'b101:
        casez_tmp_6 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20, :394:22]
      3'b110:
        casez_tmp_6 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20, :394:22]
      default:
        casez_tmp_6 = soc_awaddr;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :49:31, :83:29, :153:30, :190:20, :247:20, :265:20, :279:22, :298:20, :312:22, :380:20]
  end // always_comb
  reg  [3:0]  casez_tmp_7;	// @[src/main/bus/Xbar.scala:190:20, :382:18]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :78:27, :85:27, :153:30, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b000:
        casez_tmp_7 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b001:
        casez_tmp_7 = io_imem_awid;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b010:
        casez_tmp_7 = io_imem_awid;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b011:
        casez_tmp_7 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b100:
        casez_tmp_7 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b101:
        casez_tmp_7 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      3'b110:
        casez_tmp_7 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
      default:
        casez_tmp_7 = soc_awid;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :85:27, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :78:27, :85:27, :153:30, :190:20, :247:20, :267:18, :293:18, :300:18, :375:18, :382:18]
  end // always_comb
  reg  [7:0]  casez_tmp_8;	// @[src/main/bus/Xbar.scala:190:20, :383:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :78:27, :86:28, :153:30, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b000:
        casez_tmp_8 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b001:
        casez_tmp_8 = io_imem_awlen;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b010:
        casez_tmp_8 = io_imem_awlen;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b011:
        casez_tmp_8 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b100:
        casez_tmp_8 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b101:
        casez_tmp_8 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      3'b110:
        casez_tmp_8 = 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
      default:
        casez_tmp_8 = soc_awlen;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :86:28, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :78:27, :86:28, :153:30, :190:20, :247:20, :268:19, :293:18, :301:19, :375:18, :383:19]
  end // always_comb
  reg  [2:0]  casez_tmp_9;	// @[src/main/bus/Xbar.scala:190:20, :384:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :153:30, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b000:
        casez_tmp_9 = 3'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :152:26, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b001:
        casez_tmp_9 = io_imem_awsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b010:
        casez_tmp_9 = io_imem_awsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b011:
        casez_tmp_9 = io_dmem_awsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b100:
        casez_tmp_9 = io_dmem_awsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b101:
        casez_tmp_9 = 3'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :152:26, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      3'b110:
        casez_tmp_9 = 3'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :152:26, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
      default:
        casez_tmp_9 = soc_awsize;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :49:31, :87:29, :153:30, :190:20, :247:20, :269:20, :279:22, :302:20, :312:22, :384:20]
  end // always_comb
  reg  [1:0]  casez_tmp_10;	// @[src/main/bus/Xbar.scala:190:20, :385:21]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :78:27, :88:30, :153:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b000:
        casez_tmp_10 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b001:
        casez_tmp_10 = io_imem_awburst;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b010:
        casez_tmp_10 = io_imem_awburst;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b011:
        casez_tmp_10 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b100:
        casez_tmp_10 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b101:
        casez_tmp_10 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      3'b110:
        casez_tmp_10 = 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
      default:
        casez_tmp_10 = soc_awburst;	// @[src/main/bus/Xbar.scala:27:29, :78:27, :88:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :78:27, :88:30, :153:30, :190:20, :247:20, :270:21, :293:18, :303:21, :375:18, :385:21]
  end // always_comb
  reg  [31:0] casez_tmp_11;	// @[src/main/bus/Xbar.scala:190:20, :386:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :153:30, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
      3'b000:
        casez_tmp_11 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19, :394:22]
      3'b001:
        casez_tmp_11 = io_imem_wdata;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
      3'b010:
        casez_tmp_11 = io_imem_wdata;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
      3'b011:
        casez_tmp_11 = io_dmem_wdata;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
      3'b100:
        casez_tmp_11 = io_dmem_wdata;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
      3'b101:
        casez_tmp_11 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19, :394:22]
      3'b110:
        casez_tmp_11 = 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19, :394:22]
      default:
        casez_tmp_11 = soc_wdata;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :49:31, :89:28, :153:30, :190:20, :247:20, :271:19, :279:22, :304:19, :312:22, :386:19]
  end // always_comb
  reg  [3:0]  casez_tmp_12;	// @[src/main/bus/Xbar.scala:190:20, :387:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :153:30, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b000:
        casez_tmp_12 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b001:
        casez_tmp_12 = io_imem_wstrb;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b010:
        casez_tmp_12 = io_imem_wstrb;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b011:
        casez_tmp_12 = io_dmem_wstrb;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b100:
        casez_tmp_12 = io_dmem_wstrb;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b101:
        casez_tmp_12 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      3'b110:
        casez_tmp_12 = 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
      default:
        casez_tmp_12 = soc_wstrb;	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
    endcase	// @[src/main/bus/Xbar.scala:27:29, :49:31, :90:28, :153:30, :190:20, :247:20, :272:19, :279:22, :305:19, :312:22, :387:19]
  end // always_comb
  wire        _GEN = n_state == 3'h0;	// @[src/main/bus/Xbar.scala:152:26, :153:30, :190:20]
  wire        _GEN_0 = n_state == 3'h1;	// @[src/main/bus/Xbar.scala:153:30, :156:72, :190:20]
  wire        _GEN_1 = n_state == 3'h2;	// @[src/main/bus/Xbar.scala:153:30, :182:29, :190:20]
  wire        _GEN_2 = _GEN_0 | _GEN_1;	// @[src/main/bus/Xbar.scala:27:29, :190:20, :247:20]
  wire        _GEN_3 = n_state == 3'h3;	// @[src/main/bus/Xbar.scala:153:30, :156:23, :190:20]
  wire        _GEN_4 = n_state == 3'h4;	// @[src/main/bus/Xbar.scala:153:30, :184:29, :190:20]
  wire        _GEN_5 = n_state == 3'h5;	// @[src/main/bus/Xbar.scala:153:30, :190:20, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_6 = n_state == 3'h6;	// @[src/main/bus/Xbar.scala:153:30, :186:29, :190:20]
  wire        _GEN_7 = _GEN_5 | _GEN_6;	// @[src/main/bus/Xbar.scala:49:31, :190:20, :312:22]
  wire        _GEN_8 = _GEN_3 | _GEN_4;	// @[src/main/bus/Xbar.scala:190:20, :279:22]
  wire        _GEN_9 = _GEN | _GEN_2;	// @[src/main/bus/Xbar.scala:27:29, :190:20, :247:20, :359:22]
  wire        _GEN_10 = _GEN | _GEN_0 | _GEN_1 | _GEN_8;	// @[src/main/bus/Xbar.scala:190:20, :279:22, :394:22]
  wire        _GEN_11 = _GEN_4 | _GEN_7;	// @[src/main/bus/Xbar.scala:26:31, :49:31, :190:20, :312:22, :345:22]
  wire        _GEN_12 = _GEN_3 | _GEN_11;	// @[src/main/bus/Xbar.scala:26:31, :190:20, :345:22]
  always @(posedge clock) begin	// @[src/main/bus/Xbar.scala:21:7]
    if (reset) begin	// @[src/main/bus/Xbar.scala:21:7]
      imem_arready <= 1'h1;	// @[src/main/bus/Xbar.scala:22:16, :26:31]
      imem_rdata <= 32'h0;	// @[src/main/bus/Xbar.scala:27:29, :190:20, :394:22]
      imem_rresp <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :28:29]
      imem_rvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :29:30]
      dmem_arready <= 1'h1;	// @[src/main/bus/Xbar.scala:22:16, :49:31]
      dmem_rdata <= 32'h0;	// @[src/main/bus/Xbar.scala:50:29, :190:20, :394:22]
      dmem_rvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :52:30]
      dmem_awready <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :55:31]
      dmem_wready <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :56:30]
      dmem_bvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :58:30]
      soc_araddr <= 32'h0;	// @[src/main/bus/Xbar.scala:76:29, :190:20, :394:22]
      soc_arvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :77:30]
      soc_arid <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :78:27]
      soc_arlen <= 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :79:28]
      soc_arsize <= 3'h0;	// @[src/main/bus/Xbar.scala:80:29, :152:26]
      soc_arburst <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :81:30]
      soc_rready <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :82:29]
      soc_awaddr <= 32'h0;	// @[src/main/bus/Xbar.scala:83:29, :190:20, :394:22]
      soc_awvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :84:30]
      soc_awid <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :85:27]
      soc_awlen <= 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :86:28]
      soc_awsize <= 3'h0;	// @[src/main/bus/Xbar.scala:87:29, :152:26]
      soc_awburst <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :88:30]
      soc_wdata <= 32'h0;	// @[src/main/bus/Xbar.scala:89:28, :190:20, :394:22]
      soc_wstrb <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :90:28]
      soc_wvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :91:29]
      soc_wlast <= 1'h1;	// @[src/main/bus/Xbar.scala:22:16, :92:28]
      soc_bready <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :93:29]
      clint_araddr <= 32'h0;	// @[src/main/bus/Xbar.scala:113:31, :190:20, :394:22]
      clint_arvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :114:32]
      clint_arid <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :115:29]
      clint_arlen <= 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :116:30]
      clint_arsize <= 3'h0;	// @[src/main/bus/Xbar.scala:117:31, :152:26]
      clint_arburst <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :118:32]
      clint_rready <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :119:31]
      clint_awaddr <= 32'h0;	// @[src/main/bus/Xbar.scala:120:31, :190:20, :394:22]
      clint_awvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :121:32]
      clint_awid <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :122:29]
      clint_awlen <= 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :123:30]
      clint_awsize <= 3'h0;	// @[src/main/bus/Xbar.scala:124:31, :152:26]
      clint_awburst <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :125:32]
      clint_wdata <= 32'h0;	// @[src/main/bus/Xbar.scala:126:30, :190:20, :394:22]
      clint_wstrb <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :127:30]
      clint_wvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :128:31]
      clint_bready <= 1'h0;	// @[src/main/bus/Xbar.scala:27:29, :130:31]
      c_state <= 3'h0;	// @[src/main/bus/Xbar.scala:152:26]
    end
    else begin	// @[src/main/bus/Xbar.scala:21:7]
      imem_arready <= _GEN | (_GEN_2 ? io_soc_arready : _GEN_12 | imem_arready);	// @[src/main/bus/Xbar.scala:26:31, :27:29, :190:20, :246:22, :247:20, :345:22]
      if (_GEN | ~_GEN_2) begin	// @[src/main/bus/Xbar.scala:27:29, :190:20, :247:20]
      end
      else	// @[src/main/bus/Xbar.scala:27:29, :190:20]
        imem_rdata <= io_soc_rdata;	// @[src/main/bus/Xbar.scala:27:29]
      imem_rresp <= casez_tmp_0;	// @[src/main/bus/Xbar.scala:28:29, :190:20, :347:20]
      imem_rvalid <= ~_GEN & (_GEN_2 ? io_soc_rvalid : ~_GEN_12 & imem_rvalid);	// @[src/main/bus/Xbar.scala:26:31, :27:29, :29:30, :190:20, :247:20, :249:21, :345:22, :348:21]
      dmem_arready <=
        _GEN_9 | (_GEN_8 ? io_soc_arready : _GEN_7 ? io_clint_arready : dmem_arready);	// @[src/main/bus/Xbar.scala:49:31, :190:20, :279:22, :312:22, :359:22]
      if (~_GEN_9) begin	// @[src/main/bus/Xbar.scala:190:20, :359:22, :362:21]
        if (_GEN_8)	// @[src/main/bus/Xbar.scala:190:20, :279:22]
          dmem_rdata <= io_soc_rdata;	// @[src/main/bus/Xbar.scala:50:29]
        else if (_GEN_7)	// @[src/main/bus/Xbar.scala:49:31, :190:20, :312:22]
          dmem_rdata <= io_clint_rdata;	// @[src/main/bus/Xbar.scala:50:29]
      end
      dmem_rvalid <=
        ~_GEN_9 & (_GEN_8 ? io_soc_rvalid : _GEN_7 ? io_clint_rvalid : dmem_rvalid);	// @[src/main/bus/Xbar.scala:49:31, :52:30, :190:20, :279:22, :282:21, :312:22, :315:21, :359:22, :362:21]
      dmem_awready <=
        _GEN_9 | (_GEN_8 ? io_soc_awready : _GEN_7 ? io_clint_awready : dmem_awready);	// @[src/main/bus/Xbar.scala:49:31, :55:31, :190:20, :279:22, :285:22, :312:22, :318:22, :359:22, :365:22]
      dmem_wready <=
        _GEN_9 | (_GEN_8 ? io_soc_wready : _GEN_7 ? io_clint_wready : dmem_wready);	// @[src/main/bus/Xbar.scala:49:31, :56:30, :190:20, :279:22, :286:21, :312:22, :319:21, :359:22, :366:21]
      dmem_bvalid <=
        ~_GEN_9 & (_GEN_8 ? io_soc_bvalid : _GEN_7 ? io_clint_bvalid : dmem_bvalid);	// @[src/main/bus/Xbar.scala:49:31, :58:30, :190:20, :279:22, :288:21, :312:22, :321:21, :359:22, :362:21, :368:21]
      soc_araddr <= casez_tmp_1;	// @[src/main/bus/Xbar.scala:76:29, :190:20, :373:20]
      soc_arvalid <=
        ~_GEN
        & (_GEN_0
             ? io_imem_arvalid
             : ~_GEN_1 & (_GEN_3 ? io_dmem_arvalid : ~_GEN_11 & soc_arvalid));	// @[src/main/bus/Xbar.scala:26:31, :77:30, :190:20, :206:25, :221:25, :259:21, :292:21, :345:22, :348:21, :374:21]
      soc_arid <= casez_tmp_2;	// @[src/main/bus/Xbar.scala:78:27, :190:20, :375:18]
      soc_arlen <= casez_tmp_3;	// @[src/main/bus/Xbar.scala:79:28, :190:20, :376:19]
      soc_arsize <= casez_tmp_4;	// @[src/main/bus/Xbar.scala:80:29, :190:20, :377:20]
      soc_arburst <= casez_tmp_5;	// @[src/main/bus/Xbar.scala:81:30, :190:20, :378:21]
      soc_rready <=
        ~_GEN
        & (_GEN_0
             ? io_imem_rready
             : ~_GEN_1 & (_GEN_3 ? io_dmem_rready : ~_GEN_11 & soc_rready));	// @[src/main/bus/Xbar.scala:26:31, :77:30, :82:29, :190:20, :206:25, :207:24, :221:25, :222:24, :264:20, :297:20, :345:22, :348:21, :374:21, :379:20]
      soc_awaddr <= casez_tmp_6;	// @[src/main/bus/Xbar.scala:83:29, :190:20, :380:20]
      soc_awvalid <=
        ~_GEN
        & (_GEN_0
             ? io_imem_awvalid
             : ~_GEN_1 & (_GEN_3 ? io_dmem_awvalid : ~_GEN_11 & soc_awvalid));	// @[src/main/bus/Xbar.scala:26:31, :77:30, :84:30, :190:20, :206:25, :208:25, :221:25, :223:25, :266:21, :299:21, :345:22, :348:21, :374:21, :381:21]
      soc_awid <= casez_tmp_7;	// @[src/main/bus/Xbar.scala:85:27, :190:20, :382:18]
      soc_awlen <= casez_tmp_8;	// @[src/main/bus/Xbar.scala:86:28, :190:20, :383:19]
      soc_awsize <= casez_tmp_9;	// @[src/main/bus/Xbar.scala:87:29, :190:20, :384:20]
      soc_awburst <= casez_tmp_10;	// @[src/main/bus/Xbar.scala:88:30, :190:20, :385:21]
      soc_wdata <= casez_tmp_11;	// @[src/main/bus/Xbar.scala:89:28, :190:20, :386:19]
      soc_wstrb <= casez_tmp_12;	// @[src/main/bus/Xbar.scala:90:28, :190:20, :387:19]
      soc_wvalid <=
        ~_GEN
        & (_GEN_0
             ? io_imem_wvalid
             : ~_GEN_1 & (_GEN_3 ? io_dmem_wvalid : ~_GEN_11 & soc_wvalid));	// @[src/main/bus/Xbar.scala:26:31, :77:30, :91:29, :190:20, :206:25, :209:24, :221:25, :224:24, :273:20, :306:20, :345:22, :348:21, :374:21, :388:20]
      soc_wlast <= _GEN | (_GEN_2 ? io_imem_wlast : _GEN_8 | _GEN_7 | soc_wlast);	// @[src/main/bus/Xbar.scala:27:29, :49:31, :92:28, :190:20, :247:20, :274:19, :279:22, :307:19, :312:22, :389:19]
      soc_bready <=
        ~_GEN
        & (_GEN_0
             ? io_imem_bready
             : ~_GEN_1 & (_GEN_3 ? io_dmem_bready : ~_GEN_11 & soc_bready));	// @[src/main/bus/Xbar.scala:26:31, :77:30, :93:29, :190:20, :206:25, :210:24, :221:25, :225:24, :275:20, :308:20, :345:22, :348:21, :374:21, :390:20]
      if (_GEN_10) begin	// @[src/main/bus/Xbar.scala:190:20, :394:22]
        clint_araddr <= 32'h0;	// @[src/main/bus/Xbar.scala:113:31, :190:20, :394:22]
        clint_arsize <= 3'h0;	// @[src/main/bus/Xbar.scala:117:31, :152:26]
        clint_awaddr <= 32'h0;	// @[src/main/bus/Xbar.scala:120:31, :190:20, :394:22]
        clint_awsize <= 3'h0;	// @[src/main/bus/Xbar.scala:124:31, :152:26]
        clint_wdata <= 32'h0;	// @[src/main/bus/Xbar.scala:126:30, :190:20, :394:22]
        clint_wstrb <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :127:30]
      end
      else if (_GEN_7) begin	// @[src/main/bus/Xbar.scala:49:31, :190:20, :312:22]
        clint_araddr <= io_dmem_araddr;	// @[src/main/bus/Xbar.scala:113:31]
        clint_arsize <= io_dmem_arsize;	// @[src/main/bus/Xbar.scala:117:31]
        clint_awaddr <= io_dmem_awaddr;	// @[src/main/bus/Xbar.scala:120:31]
        clint_awsize <= io_dmem_awsize;	// @[src/main/bus/Xbar.scala:124:31]
        clint_wdata <= io_dmem_wdata;	// @[src/main/bus/Xbar.scala:126:30]
        clint_wstrb <= io_dmem_wstrb;	// @[src/main/bus/Xbar.scala:127:30]
      end
      clint_arvalid <= ~_GEN_10 & (_GEN_5 ? io_dmem_arvalid : ~_GEN_6 & clint_arvalid);	// @[src/main/bus/Xbar.scala:114:32, :190:20, :236:27, :325:23, :394:22, :395:23]
      if (_GEN_10 | _GEN_7) begin	// @[src/main/bus/Xbar.scala:49:31, :115:29, :190:20, :312:22, :326:20, :394:22, :396:20]
        clint_arid <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :115:29]
        clint_arlen <= 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :116:30]
        clint_arburst <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :118:32]
        clint_awid <= 4'h0;	// @[src/main/bus/Xbar.scala:21:7, :122:29]
        clint_awlen <= 8'h0;	// @[src/main/bus/Xbar.scala:22:16, :123:30]
        clint_awburst <= 2'h0;	// @[src/main/bus/Xbar.scala:22:16, :125:32]
      end
      clint_rready <= ~_GEN_10 & (_GEN_5 ? io_dmem_rready : ~_GEN_6 & clint_rready);	// @[src/main/bus/Xbar.scala:114:32, :119:31, :190:20, :236:27, :237:26, :330:22, :394:22, :395:23, :400:22]
      clint_awvalid <= ~_GEN_10 & (_GEN_5 ? io_dmem_awvalid : ~_GEN_6 & clint_awvalid);	// @[src/main/bus/Xbar.scala:114:32, :121:32, :190:20, :236:27, :238:27, :332:23, :394:22, :395:23, :402:23]
      clint_wvalid <= ~_GEN_10 & (_GEN_5 ? io_dmem_wvalid : ~_GEN_6 & clint_wvalid);	// @[src/main/bus/Xbar.scala:114:32, :128:31, :190:20, :236:27, :239:26, :339:22, :394:22, :395:23, :409:22]
      clint_bready <= ~_GEN_10 & (_GEN_5 ? io_dmem_bready : ~_GEN_6 & clint_bready);	// @[src/main/bus/Xbar.scala:114:32, :130:31, :190:20, :236:27, :240:26, :341:22, :394:22, :395:23, :411:22]
      c_state <= n_state;	// @[src/main/bus/Xbar.scala:152:26, :153:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/bus/Xbar.scala:21:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar.scala:21:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar.scala:21:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:11];	// @[src/main/bus/Xbar.scala:21:7]
    initial begin	// @[src/main/bus/Xbar.scala:21:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar.scala:21:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar.scala:21:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/bus/Xbar.scala:21:7]
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/bus/Xbar.scala:21:7]
        end	// @[src/main/bus/Xbar.scala:21:7]
        imem_arready = _RANDOM[4'h0][0];	// @[src/main/bus/Xbar.scala:21:7, :26:31]
        imem_rdata = {_RANDOM[4'h0][31:1], _RANDOM[4'h1][0]};	// @[src/main/bus/Xbar.scala:21:7, :26:31, :27:29]
        imem_rresp = _RANDOM[4'h1][2:1];	// @[src/main/bus/Xbar.scala:21:7, :27:29, :28:29]
        imem_rvalid = _RANDOM[4'h1][3];	// @[src/main/bus/Xbar.scala:21:7, :27:29, :29:30]
        dmem_arready = _RANDOM[4'h1][18];	// @[src/main/bus/Xbar.scala:21:7, :27:29, :49:31]
        dmem_rdata = {_RANDOM[4'h1][31:19], _RANDOM[4'h2][18:0]};	// @[src/main/bus/Xbar.scala:21:7, :27:29, :50:29]
        dmem_rvalid = _RANDOM[4'h2][21];	// @[src/main/bus/Xbar.scala:21:7, :50:29, :52:30]
        dmem_awready = _RANDOM[4'h2][27];	// @[src/main/bus/Xbar.scala:21:7, :50:29, :55:31]
        dmem_wready = _RANDOM[4'h2][28];	// @[src/main/bus/Xbar.scala:21:7, :50:29, :56:30]
        dmem_bvalid = _RANDOM[4'h2][31];	// @[src/main/bus/Xbar.scala:21:7, :50:29, :58:30]
        soc_araddr = {_RANDOM[4'h3][31:4], _RANDOM[4'h4][3:0]};	// @[src/main/bus/Xbar.scala:21:7, :76:29]
        soc_arvalid = _RANDOM[4'h4][4];	// @[src/main/bus/Xbar.scala:21:7, :76:29, :77:30]
        soc_arid = _RANDOM[4'h4][8:5];	// @[src/main/bus/Xbar.scala:21:7, :76:29, :78:27]
        soc_arlen = _RANDOM[4'h4][16:9];	// @[src/main/bus/Xbar.scala:21:7, :76:29, :79:28]
        soc_arsize = _RANDOM[4'h4][19:17];	// @[src/main/bus/Xbar.scala:21:7, :76:29, :80:29]
        soc_arburst = _RANDOM[4'h4][21:20];	// @[src/main/bus/Xbar.scala:21:7, :76:29, :81:30]
        soc_rready = _RANDOM[4'h4][22];	// @[src/main/bus/Xbar.scala:21:7, :76:29, :82:29]
        soc_awaddr = {_RANDOM[4'h4][31:23], _RANDOM[4'h5][22:0]};	// @[src/main/bus/Xbar.scala:21:7, :76:29, :83:29]
        soc_awvalid = _RANDOM[4'h5][23];	// @[src/main/bus/Xbar.scala:21:7, :83:29, :84:30]
        soc_awid = _RANDOM[4'h5][27:24];	// @[src/main/bus/Xbar.scala:21:7, :83:29, :85:27]
        soc_awlen = {_RANDOM[4'h5][31:28], _RANDOM[4'h6][3:0]};	// @[src/main/bus/Xbar.scala:21:7, :83:29, :86:28]
        soc_awsize = _RANDOM[4'h6][6:4];	// @[src/main/bus/Xbar.scala:21:7, :86:28, :87:29]
        soc_awburst = _RANDOM[4'h6][8:7];	// @[src/main/bus/Xbar.scala:21:7, :86:28, :88:30]
        soc_wdata = {_RANDOM[4'h6][31:9], _RANDOM[4'h7][8:0]};	// @[src/main/bus/Xbar.scala:21:7, :86:28, :89:28]
        soc_wstrb = _RANDOM[4'h7][12:9];	// @[src/main/bus/Xbar.scala:21:7, :89:28, :90:28]
        soc_wvalid = _RANDOM[4'h7][13];	// @[src/main/bus/Xbar.scala:21:7, :89:28, :91:29]
        soc_wlast = _RANDOM[4'h7][14];	// @[src/main/bus/Xbar.scala:21:7, :89:28, :92:28]
        soc_bready = _RANDOM[4'h7][15];	// @[src/main/bus/Xbar.scala:21:7, :89:28, :93:29]
        clint_araddr = {_RANDOM[4'h7][31:16], _RANDOM[4'h8][15:0]};	// @[src/main/bus/Xbar.scala:21:7, :89:28, :113:31]
        clint_arvalid = _RANDOM[4'h8][16];	// @[src/main/bus/Xbar.scala:21:7, :113:31, :114:32]
        clint_arid = _RANDOM[4'h8][20:17];	// @[src/main/bus/Xbar.scala:21:7, :113:31, :115:29]
        clint_arlen = _RANDOM[4'h8][28:21];	// @[src/main/bus/Xbar.scala:21:7, :113:31, :116:30]
        clint_arsize = _RANDOM[4'h8][31:29];	// @[src/main/bus/Xbar.scala:21:7, :113:31, :117:31]
        clint_arburst = _RANDOM[4'h9][1:0];	// @[src/main/bus/Xbar.scala:21:7, :118:32]
        clint_rready = _RANDOM[4'h9][2];	// @[src/main/bus/Xbar.scala:21:7, :118:32, :119:31]
        clint_awaddr = {_RANDOM[4'h9][31:3], _RANDOM[4'hA][2:0]};	// @[src/main/bus/Xbar.scala:21:7, :118:32, :120:31]
        clint_awvalid = _RANDOM[4'hA][3];	// @[src/main/bus/Xbar.scala:21:7, :120:31, :121:32]
        clint_awid = _RANDOM[4'hA][7:4];	// @[src/main/bus/Xbar.scala:21:7, :120:31, :122:29]
        clint_awlen = _RANDOM[4'hA][15:8];	// @[src/main/bus/Xbar.scala:21:7, :120:31, :123:30]
        clint_awsize = _RANDOM[4'hA][18:16];	// @[src/main/bus/Xbar.scala:21:7, :120:31, :124:31]
        clint_awburst = _RANDOM[4'hA][20:19];	// @[src/main/bus/Xbar.scala:21:7, :120:31, :125:32]
        clint_wdata = {_RANDOM[4'hA][31:21], _RANDOM[4'hB][20:0]};	// @[src/main/bus/Xbar.scala:21:7, :120:31, :126:30]
        clint_wstrb = _RANDOM[4'hB][24:21];	// @[src/main/bus/Xbar.scala:21:7, :126:30, :127:30]
        clint_wvalid = _RANDOM[4'hB][25];	// @[src/main/bus/Xbar.scala:21:7, :126:30, :128:31]
        clint_bready = _RANDOM[4'hB][27];	// @[src/main/bus/Xbar.scala:21:7, :126:30, :130:31]
        c_state = _RANDOM[4'hB][30:28];	// @[src/main/bus/Xbar.scala:21:7, :126:30, :152:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar.scala:21:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar.scala:21:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_imem_arready = ready & imem_arready;	// @[src/main/bus/Xbar.scala:21:7, :26:31, :37:27, :156:60]
  assign io_imem_rdata = imem_rdata;	// @[src/main/bus/Xbar.scala:21:7, :27:29]
  assign io_imem_rresp = imem_rresp;	// @[src/main/bus/Xbar.scala:21:7, :28:29]
  assign io_imem_rvalid = imem_rvalid;	// @[src/main/bus/Xbar.scala:21:7, :29:30]
  assign io_dmem_arready = ready & dmem_arready;	// @[src/main/bus/Xbar.scala:21:7, :49:31, :60:27, :156:60]
  assign io_dmem_rdata = dmem_rdata;	// @[src/main/bus/Xbar.scala:21:7, :50:29]
  assign io_dmem_rvalid = dmem_rvalid;	// @[src/main/bus/Xbar.scala:21:7, :52:30]
  assign io_dmem_awready = ready & dmem_awready;	// @[src/main/bus/Xbar.scala:21:7, :55:31, :66:27, :156:60]
  assign io_dmem_wready = dmem_wready;	// @[src/main/bus/Xbar.scala:21:7, :56:30]
  assign io_dmem_bvalid = dmem_bvalid;	// @[src/main/bus/Xbar.scala:21:7, :58:30]
  assign io_soc_araddr = soc_araddr;	// @[src/main/bus/Xbar.scala:21:7, :76:29]
  assign io_soc_arvalid = soc_arvalid;	// @[src/main/bus/Xbar.scala:21:7, :77:30]
  assign io_soc_arid = soc_arid;	// @[src/main/bus/Xbar.scala:21:7, :78:27]
  assign io_soc_arlen = soc_arlen;	// @[src/main/bus/Xbar.scala:21:7, :79:28]
  assign io_soc_arsize = soc_arsize;	// @[src/main/bus/Xbar.scala:21:7, :80:29]
  assign io_soc_arburst = soc_arburst;	// @[src/main/bus/Xbar.scala:21:7, :81:30]
  assign io_soc_rready = soc_rready;	// @[src/main/bus/Xbar.scala:21:7, :82:29]
  assign io_soc_awaddr = soc_awaddr;	// @[src/main/bus/Xbar.scala:21:7, :83:29]
  assign io_soc_awvalid = soc_awvalid;	// @[src/main/bus/Xbar.scala:21:7, :84:30]
  assign io_soc_awid = soc_awid;	// @[src/main/bus/Xbar.scala:21:7, :85:27]
  assign io_soc_awlen = soc_awlen;	// @[src/main/bus/Xbar.scala:21:7, :86:28]
  assign io_soc_awsize = soc_awsize;	// @[src/main/bus/Xbar.scala:21:7, :87:29]
  assign io_soc_awburst = soc_awburst;	// @[src/main/bus/Xbar.scala:21:7, :88:30]
  assign io_soc_wdata = soc_wdata;	// @[src/main/bus/Xbar.scala:21:7, :89:28]
  assign io_soc_wstrb = soc_wstrb;	// @[src/main/bus/Xbar.scala:21:7, :90:28]
  assign io_soc_wvalid = soc_wvalid;	// @[src/main/bus/Xbar.scala:21:7, :91:29]
  assign io_soc_wlast = soc_wlast;	// @[src/main/bus/Xbar.scala:21:7, :92:28]
  assign io_soc_bready = soc_bready;	// @[src/main/bus/Xbar.scala:21:7, :93:29]
  assign io_clint_araddr = clint_araddr;	// @[src/main/bus/Xbar.scala:21:7, :113:31]
  assign io_clint_arvalid = clint_arvalid;	// @[src/main/bus/Xbar.scala:21:7, :114:32]
  assign io_clint_arid = clint_arid;	// @[src/main/bus/Xbar.scala:21:7, :115:29]
  assign io_clint_arlen = clint_arlen;	// @[src/main/bus/Xbar.scala:21:7, :116:30]
  assign io_clint_arsize = clint_arsize;	// @[src/main/bus/Xbar.scala:21:7, :117:31]
  assign io_clint_arburst = clint_arburst;	// @[src/main/bus/Xbar.scala:21:7, :118:32]
  assign io_clint_rready = clint_rready;	// @[src/main/bus/Xbar.scala:21:7, :119:31]
  assign io_clint_awaddr = clint_awaddr;	// @[src/main/bus/Xbar.scala:21:7, :120:31]
  assign io_clint_awvalid = clint_awvalid;	// @[src/main/bus/Xbar.scala:21:7, :121:32]
  assign io_clint_awid = clint_awid;	// @[src/main/bus/Xbar.scala:21:7, :122:29]
  assign io_clint_awlen = clint_awlen;	// @[src/main/bus/Xbar.scala:21:7, :123:30]
  assign io_clint_awsize = clint_awsize;	// @[src/main/bus/Xbar.scala:21:7, :124:31]
  assign io_clint_awburst = clint_awburst;	// @[src/main/bus/Xbar.scala:21:7, :125:32]
  assign io_clint_wdata = clint_wdata;	// @[src/main/bus/Xbar.scala:21:7, :126:30]
  assign io_clint_wstrb = clint_wstrb;	// @[src/main/bus/Xbar.scala:21:7, :127:30]
  assign io_clint_wvalid = clint_wvalid;	// @[src/main/bus/Xbar.scala:21:7, :128:31]
  assign io_clint_bready = clint_bready;	// @[src/main/bus/Xbar.scala:21:7, :130:31]
endmodule

