// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Xbar(	// @[src/main/bus/Xbar.scala:434:7]
  input         clock,	// @[src/main/bus/Xbar.scala:434:7]
                reset,	// @[src/main/bus/Xbar.scala:434:7]
  input  [31:0] io_imem_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_imem_arready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_imem_arid,	// @[src/main/bus/Xbar.scala:435:16]
  input  [7:0]  io_imem_arlen,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_imem_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [1:0]  io_imem_arburst,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_imem_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  output [1:0]  io_imem_rresp,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_imem_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_rready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_imem_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_imem_awid,	// @[src/main/bus/Xbar.scala:435:16]
  input  [7:0]  io_imem_awlen,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_imem_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [1:0]  io_imem_awburst,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_imem_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_imem_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
                io_imem_wlast,	// @[src/main/bus/Xbar.scala:435:16]
                io_imem_bready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_dmem_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_arready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_dmem_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_dmem_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_rready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_dmem_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_awready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_dmem_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_dmem_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_dmem_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_wready,	// @[src/main/bus/Xbar.scala:435:16]
                io_dmem_bvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_bready,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_soc_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_arready,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_soc_arid,	// @[src/main/bus/Xbar.scala:435:16]
  output [7:0]  io_soc_arlen,	// @[src/main/bus/Xbar.scala:435:16]
  output [2:0]  io_soc_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [1:0]  io_soc_arburst,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_soc_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  input  [1:0]  io_soc_rresp,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_rready,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_soc_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_awready,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_soc_awid,	// @[src/main/bus/Xbar.scala:435:16]
  output [7:0]  io_soc_awlen,	// @[src/main/bus/Xbar.scala:435:16]
  output [2:0]  io_soc_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [1:0]  io_soc_awburst,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_soc_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_soc_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_wready,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_wlast,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_bvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_bready	// @[src/main/bus/Xbar.scala:435:16]
);

  reg  [31:0] soc_araddr;	// @[src/main/bus/Xbar.scala:438:29]
  reg         soc_arvalid;	// @[src/main/bus/Xbar.scala:439:30]
  reg  [3:0]  soc_arid;	// @[src/main/bus/Xbar.scala:440:27]
  reg  [7:0]  soc_arlen;	// @[src/main/bus/Xbar.scala:441:28]
  reg  [2:0]  soc_arsize;	// @[src/main/bus/Xbar.scala:442:29]
  reg  [1:0]  soc_arburst;	// @[src/main/bus/Xbar.scala:443:30]
  reg         soc_rready;	// @[src/main/bus/Xbar.scala:444:29]
  reg  [31:0] soc_awaddr;	// @[src/main/bus/Xbar.scala:445:29]
  reg         soc_awvalid;	// @[src/main/bus/Xbar.scala:446:30]
  reg  [3:0]  soc_awid;	// @[src/main/bus/Xbar.scala:447:27]
  reg  [7:0]  soc_awlen;	// @[src/main/bus/Xbar.scala:448:28]
  reg  [2:0]  soc_awsize;	// @[src/main/bus/Xbar.scala:449:29]
  reg  [1:0]  soc_awburst;	// @[src/main/bus/Xbar.scala:450:30]
  reg  [31:0] soc_wdata;	// @[src/main/bus/Xbar.scala:451:28]
  reg  [3:0]  soc_wstrb;	// @[src/main/bus/Xbar.scala:452:28]
  reg         soc_wvalid;	// @[src/main/bus/Xbar.scala:453:29]
  reg         soc_wlast;	// @[src/main/bus/Xbar.scala:454:28]
  reg         soc_bready;	// @[src/main/bus/Xbar.scala:455:29]
  reg         soc_rvalid_r;	// @[src/main/bus/Xbar.scala:474:31]
  reg         soc_bvalid_r;	// @[src/main/bus/Xbar.scala:476:31]
  reg  [7:0]  burstCnt;	// @[src/main/bus/Xbar.scala:483:37]
  reg  [1:0]  c_state;	// @[src/main/bus/Xbar.scala:486:26]
  reg  [1:0]  casez_tmp;	// @[src/main/bus/Xbar.scala:505:42]
  wire        isclint_raddr = (|(io_dmem_araddr[31:25])) & io_dmem_araddr < 32'h2010000;	// @[src/main/bus/Xbar.scala:490:{41,65,83}]
  wire        isclint_waddr = (|(io_dmem_awaddr[31:25])) & io_dmem_awaddr < 32'h2010000;	// @[src/main/bus/Xbar.scala:490:83, :491:{41,65,83}]
  always_comb begin	// @[src/main/bus/Xbar.scala:505:42]
    casez (c_state)	// @[src/main/bus/Xbar.scala:486:26, :505:42]
      2'b00:
        casez_tmp =
          io_imem_arvalid
            ? 2'h1
            : io_dmem_arvalid & ~isclint_raddr | io_dmem_awvalid & ~isclint_waddr
                ? 2'h2
                : {2{io_dmem_arvalid & isclint_raddr | io_dmem_awvalid & isclint_waddr}};	// @[src/main/bus/Xbar.scala:490:65, :491:65, :496:{40,42,58,74,76}, :497:{42,59,75}, :505:42, src/main/scala/chisel3/util/Mux.scala:126:16]
      2'b01:
        casez_tmp =
          ~io_soc_rvalid & soc_rvalid_r & soc_rready & ~(|burstCnt)
            ? {1'h0, io_imem_arvalid}
            : 2'h1;	// @[src/main/bus/Xbar.scala:438:29, :444:29, :474:31, :483:37, :499:{22,65,76}, :505:42, :511:{27,43}, src/main/scala/chisel3/util/Mux.scala:126:16]
      2'b10:
        casez_tmp =
          {~(~io_soc_rvalid & soc_rvalid_r & soc_rready | ~io_soc_bvalid & soc_bvalid_r
             & soc_bready),
           1'h0};	// @[src/main/bus/Xbar.scala:438:29, :444:29, :455:29, :474:31, :476:31, :499:22, :500:{53,67,70,100}, :505:42, :512:27]
      default:
        casez_tmp = 2'h3;	// @[src/main/bus/Xbar.scala:505:42, src/main/scala/chisel3/util/Mux.scala:126:16]
    endcase	// @[src/main/bus/Xbar.scala:486:26, :505:42]
  end // always_comb
  wire [1:0]  n_state = casez_tmp;	// @[src/main/bus/Xbar.scala:487:30, :505:42]
  reg  [31:0] imem_araddr;	// @[src/main/bus/Xbar.scala:521:32]
  reg  [1:0]  imem_arburst;	// @[src/main/bus/Xbar.scala:522:33]
  reg  [7:0]  imem_arlen;	// @[src/main/bus/Xbar.scala:523:31]
  reg  [2:0]  imem_arsize;	// @[src/main/bus/Xbar.scala:524:32]
  reg  [31:0] dmem_araddr;	// @[src/main/bus/Xbar.scala:525:32]
  reg  [31:0] dmem_awaddr;	// @[src/main/bus/Xbar.scala:526:32]
  wire        _GEN = n_state == 2'h0;	// @[src/main/bus/Xbar.scala:435:16, :487:30, :528:20, :618:21, :625:21, :700:21, :707:21]
  wire        _GEN_0 = n_state == 2'h1;	// @[src/main/bus/Xbar.scala:487:30, :528:20, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_1 = _GEN | ~_GEN_0;	// @[src/main/bus/Xbar.scala:528:20, :568:25, :667:25, :669:23]
  wire        _GEN_2 = soc_arvalid & io_soc_arready;	// @[src/main/bus/Xbar.scala:439:30, :533:33]
  wire        _GEN_3 = soc_arvalid & ~io_soc_arready;	// @[src/main/bus/Xbar.scala:439:30, :535:{39,41}]
  wire        _GEN_4 = _GEN_2 | ~_GEN_3;	// @[src/main/bus/Xbar.scala:533:{33,50}, :535:{39,57}, :580:20]
  wire        _GEN_5 = n_state == 2'h2;	// @[src/main/bus/Xbar.scala:487:30, :528:20, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_6 = _GEN | _GEN_0;	// @[src/main/bus/Xbar.scala:528:20, :681:25]
  reg  [2:0]  casez_tmp_0;	// @[src/main/bus/Xbar.scala:528:20, :699:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:528:20, :533:50, :617:20, :699:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:487:30, :528:20, :533:50, :617:20, :699:20]
      2'b00:
        casez_tmp_0 = 3'h0;	// @[src/main/bus/Xbar.scala:528:20, :533:50, :617:20, :699:20, :720:25]
      2'b01:
        casez_tmp_0 = _GEN_4 ? io_imem_arsize : imem_arsize;	// @[src/main/bus/Xbar.scala:524:32, :528:20, :533:50, :535:57, :580:20, :584:20, :617:20, :699:20]
      2'b10:
        casez_tmp_0 = io_dmem_arsize;	// @[src/main/bus/Xbar.scala:528:20, :533:50, :617:20, :699:20]
      default:
        casez_tmp_0 = 3'h0;	// @[src/main/bus/Xbar.scala:528:20, :533:50, :617:20, :699:20, :720:25]
    endcase	// @[src/main/bus/Xbar.scala:487:30, :528:20, :533:50, :617:20, :699:20]
  end // always_comb
  reg  [2:0]  casez_tmp_1;	// @[src/main/bus/Xbar.scala:528:20, :706:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:528:20, :591:20, :624:20, :706:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:487:30, :528:20, :591:20, :624:20, :706:20]
      2'b00:
        casez_tmp_1 = 3'h0;	// @[src/main/bus/Xbar.scala:528:20, :591:20, :624:20, :706:20, :720:25]
      2'b01:
        casez_tmp_1 = io_imem_awsize;	// @[src/main/bus/Xbar.scala:528:20, :591:20, :624:20, :706:20]
      2'b10:
        casez_tmp_1 = io_dmem_awsize;	// @[src/main/bus/Xbar.scala:528:20, :591:20, :624:20, :706:20]
      default:
        casez_tmp_1 = 3'h0;	// @[src/main/bus/Xbar.scala:528:20, :591:20, :624:20, :706:20, :720:25]
    endcase	// @[src/main/bus/Xbar.scala:487:30, :528:20, :591:20, :624:20, :706:20]
  end // always_comb
  reg  [31:0] casez_tmp_2;	// @[src/main/bus/Xbar.scala:528:20, :708:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:528:20, :593:19, :626:19, :708:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:487:30, :528:20, :593:19, :626:19, :708:19]
      2'b00:
        casez_tmp_2 = 32'h0;	// @[src/main/bus/Xbar.scala:528:20, :593:19, :626:19, :708:19, :716:25]
      2'b01:
        casez_tmp_2 = io_imem_wdata;	// @[src/main/bus/Xbar.scala:528:20, :593:19, :626:19, :708:19]
      2'b10:
        casez_tmp_2 = io_dmem_wdata;	// @[src/main/bus/Xbar.scala:528:20, :593:19, :626:19, :708:19]
      default:
        casez_tmp_2 = 32'h0;	// @[src/main/bus/Xbar.scala:528:20, :593:19, :626:19, :708:19, :716:25]
    endcase	// @[src/main/bus/Xbar.scala:487:30, :528:20, :593:19, :626:19, :708:19]
  end // always_comb
  reg  [3:0]  casez_tmp_3;	// @[src/main/bus/Xbar.scala:528:20, :709:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:528:20, :594:19, :627:19, :709:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:487:30, :528:20, :594:19, :627:19, :709:19]
      2'b00:
        casez_tmp_3 = 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :594:19, :627:19, :709:19]
      2'b01:
        casez_tmp_3 = io_imem_wstrb;	// @[src/main/bus/Xbar.scala:528:20, :594:19, :627:19, :709:19]
      2'b10:
        casez_tmp_3 = io_dmem_wstrb;	// @[src/main/bus/Xbar.scala:528:20, :594:19, :627:19, :709:19]
      default:
        casez_tmp_3 = 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :594:19, :627:19, :709:19]
    endcase	// @[src/main/bus/Xbar.scala:487:30, :528:20, :594:19, :627:19, :709:19]
  end // always_comb
  reg  [31:0] casez_tmp_4;	// @[src/main/bus/Xbar.scala:528:20, :695:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:528:20, :533:50, :545:50, :695:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:487:30, :528:20, :533:50, :545:50, :695:20]
      2'b00:
        casez_tmp_4 = 32'h0;	// @[src/main/bus/Xbar.scala:528:20, :533:50, :545:50, :695:20, :716:25]
      2'b01:
        casez_tmp_4 = _GEN_4 ? io_imem_araddr : imem_araddr;	// @[src/main/bus/Xbar.scala:521:32, :528:20, :533:50, :535:57, :545:50, :580:20, :695:20]
      2'b10:
        casez_tmp_4 = _GEN_4 ? io_dmem_araddr : dmem_araddr;	// @[src/main/bus/Xbar.scala:525:32, :528:20, :533:50, :535:57, :545:50, :547:57, :580:20, :613:20, :695:20]
      default:
        casez_tmp_4 = 32'h0;	// @[src/main/bus/Xbar.scala:528:20, :533:50, :545:50, :695:20, :716:25]
    endcase	// @[src/main/bus/Xbar.scala:487:30, :528:20, :533:50, :545:50, :695:20]
  end // always_comb
  wire        _GEN_7 = soc_awvalid & io_soc_awready;	// @[src/main/bus/Xbar.scala:446:30, :551:33]
  wire        _GEN_8 = soc_awvalid & ~io_soc_awready;	// @[src/main/bus/Xbar.scala:446:30, :553:{39,41}]
  reg  [31:0] casez_tmp_5;	// @[src/main/bus/Xbar.scala:528:20, :702:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:528:20, :551:50, :587:20, :702:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:487:30, :528:20, :551:50, :587:20, :702:20]
      2'b00:
        casez_tmp_5 = 32'h0;	// @[src/main/bus/Xbar.scala:528:20, :551:50, :587:20, :702:20, :716:25]
      2'b01:
        casez_tmp_5 = io_imem_awaddr;	// @[src/main/bus/Xbar.scala:528:20, :551:50, :587:20, :702:20]
      2'b10:
        casez_tmp_5 = _GEN_7 | ~_GEN_8 ? io_dmem_awaddr : dmem_awaddr;	// @[src/main/bus/Xbar.scala:526:32, :528:20, :551:{33,50}, :553:{39,57}, :587:20, :620:20, :702:20]
      default:
        casez_tmp_5 = 32'h0;	// @[src/main/bus/Xbar.scala:528:20, :551:50, :587:20, :702:20, :716:25]
    endcase	// @[src/main/bus/Xbar.scala:487:30, :528:20, :551:50, :587:20, :702:20]
  end // always_comb
  always @(posedge clock) begin	// @[src/main/bus/Xbar.scala:434:7]
    if (reset) begin	// @[src/main/bus/Xbar.scala:434:7]
      soc_araddr <= 32'h0;	// @[src/main/bus/Xbar.scala:438:29, :716:25]
      soc_arvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:438:29, :439:30]
      soc_arid <= 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :440:27]
      soc_arlen <= 8'h0;	// @[src/main/bus/Xbar.scala:435:16, :441:28, :528:20, :616:19, :623:19, :698:19, :705:19]
      soc_arsize <= 3'h0;	// @[src/main/bus/Xbar.scala:442:29, :720:25]
      soc_arburst <= 2'h0;	// @[src/main/bus/Xbar.scala:435:16, :443:30, :528:20, :618:21, :625:21, :700:21, :707:21]
      soc_rready <= 1'h0;	// @[src/main/bus/Xbar.scala:438:29, :444:29]
      soc_awaddr <= 32'h0;	// @[src/main/bus/Xbar.scala:445:29, :716:25]
      soc_awvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:438:29, :446:30]
      soc_awid <= 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :447:27]
      soc_awlen <= 8'h0;	// @[src/main/bus/Xbar.scala:435:16, :448:28, :528:20, :616:19, :623:19, :698:19, :705:19]
      soc_awsize <= 3'h0;	// @[src/main/bus/Xbar.scala:449:29, :720:25]
      soc_awburst <= 2'h0;	// @[src/main/bus/Xbar.scala:435:16, :450:30, :528:20, :618:21, :625:21, :700:21, :707:21]
      soc_wdata <= 32'h0;	// @[src/main/bus/Xbar.scala:451:28, :716:25]
      soc_wstrb <= 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :452:28]
      soc_wvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:438:29, :453:29]
      soc_wlast <= 1'h1;	// @[src/main/bus/Xbar.scala:435:16, :454:28, :528:20, :629:19, :711:19]
      soc_bready <= 1'h0;	// @[src/main/bus/Xbar.scala:438:29, :455:29]
      burstCnt <= 8'h0;	// @[src/main/bus/Xbar.scala:435:16, :483:37, :528:20, :616:19, :623:19, :698:19, :705:19]
      c_state <= 2'h0;	// @[src/main/bus/Xbar.scala:435:16, :486:26, :528:20, :618:21, :625:21, :700:21, :707:21]
    end
    else begin	// @[src/main/bus/Xbar.scala:434:7]
      soc_araddr <= casez_tmp_4;	// @[src/main/bus/Xbar.scala:438:29, :528:20, :695:20]
      soc_arvalid <=
        ~_GEN
        & (_GEN_0
             ? ~_GEN_2 & (_GEN_3 | io_imem_arvalid)
             : _GEN_5 & ~_GEN_2 & (_GEN_3 | io_dmem_arvalid));	// @[src/main/bus/Xbar.scala:439:30, :528:20, :533:{33,50}, :534:29, :535:{39,57}, :536:29, :545:50, :547:57, :548:29, :581:21, :614:21, :670:24, :696:21]
      soc_arid <= _GEN_1 ? 4'h0 : io_imem_arid;	// @[src/main/bus/Xbar.scala:434:7, :440:27, :528:20, :669:23, :697:18]
      soc_arlen <= _GEN_1 ? 8'h0 : _GEN_4 ? io_imem_arlen : imem_arlen;	// @[src/main/bus/Xbar.scala:435:16, :441:28, :523:31, :528:20, :533:50, :535:57, :580:20, :583:19, :616:19, :623:19, :669:23, :698:19, :705:19]
      soc_arsize <= casez_tmp_0;	// @[src/main/bus/Xbar.scala:442:29, :528:20, :699:20]
      soc_arburst <= _GEN_1 ? 2'h0 : _GEN_4 ? io_imem_arburst : imem_arburst;	// @[src/main/bus/Xbar.scala:435:16, :443:30, :522:33, :528:20, :533:50, :535:57, :580:20, :585:21, :618:21, :625:21, :669:23, :700:21, :707:21]
      soc_rready <= ~_GEN & (_GEN_0 ? io_imem_rready : _GEN_5 & io_dmem_rready);	// @[src/main/bus/Xbar.scala:444:29, :528:20, :586:20, :619:20, :670:24, :701:20]
      soc_awaddr <= casez_tmp_5;	// @[src/main/bus/Xbar.scala:445:29, :528:20, :702:20]
      soc_awvalid <=
        ~_GEN
        & (_GEN_0 ? io_imem_awvalid : _GEN_5 & ~_GEN_7 & (_GEN_8 | io_dmem_awvalid));	// @[src/main/bus/Xbar.scala:446:30, :528:20, :551:{33,50}, :552:29, :553:{39,57}, :554:29, :588:21, :621:21, :670:24, :703:21]
      soc_awid <= _GEN_1 ? 4'h0 : io_imem_awid;	// @[src/main/bus/Xbar.scala:434:7, :447:27, :528:20, :669:23, :704:18]
      soc_awlen <= _GEN_1 ? 8'h0 : io_imem_awlen;	// @[src/main/bus/Xbar.scala:435:16, :448:28, :528:20, :616:19, :623:19, :669:23, :698:19, :705:19]
      soc_awsize <= casez_tmp_1;	// @[src/main/bus/Xbar.scala:449:29, :528:20, :706:20]
      soc_awburst <= _GEN_1 ? 2'h0 : io_imem_awburst;	// @[src/main/bus/Xbar.scala:435:16, :450:30, :528:20, :618:21, :625:21, :669:23, :700:21, :707:21]
      soc_wdata <= casez_tmp_2;	// @[src/main/bus/Xbar.scala:451:28, :528:20, :708:19]
      soc_wstrb <= casez_tmp_3;	// @[src/main/bus/Xbar.scala:452:28, :528:20, :709:19]
      soc_wvalid <= ~_GEN & (_GEN_0 ? io_imem_wvalid : _GEN_5 & io_dmem_wvalid);	// @[src/main/bus/Xbar.scala:453:29, :528:20, :595:20, :628:20, :670:24, :710:20]
      soc_wlast <= _GEN | ~_GEN_0 | io_imem_wlast;	// @[src/main/bus/Xbar.scala:454:28, :528:20, :568:25, :667:25, :711:19]
      soc_bready <= ~_GEN & (_GEN_0 ? io_imem_bready : _GEN_5 & io_dmem_bready);	// @[src/main/bus/Xbar.scala:455:29, :528:20, :597:20, :630:20, :670:24, :712:20]
      if (_GEN_2)	// @[src/main/bus/Xbar.scala:533:33]
        burstCnt <= soc_arlen + 8'h1;	// @[src/main/bus/Xbar.scala:441:28, :483:37, :561:34]
      else if ((|burstCnt) & soc_rready & io_soc_rvalid)	// @[src/main/bus/Xbar.scala:444:29, :483:37, :499:76, :562:49]
        burstCnt <= burstCnt - 8'h1;	// @[src/main/bus/Xbar.scala:483:37, :563:30]
      c_state <= n_state;	// @[src/main/bus/Xbar.scala:486:26, :487:30]
    end
    soc_rvalid_r <= io_soc_rvalid;	// @[src/main/bus/Xbar.scala:474:31]
    soc_bvalid_r <= io_soc_bvalid;	// @[src/main/bus/Xbar.scala:476:31]
    if (io_imem_arvalid) begin	// @[src/main/bus/Xbar.scala:435:16]
      imem_araddr <= io_imem_araddr;	// @[src/main/bus/Xbar.scala:521:32]
      imem_arburst <= io_imem_arburst;	// @[src/main/bus/Xbar.scala:522:33]
      imem_arlen <= io_imem_arlen;	// @[src/main/bus/Xbar.scala:523:31]
      imem_arsize <= io_imem_arsize;	// @[src/main/bus/Xbar.scala:524:32]
    end
    if (io_dmem_arvalid)	// @[src/main/bus/Xbar.scala:435:16]
      dmem_araddr <= io_dmem_araddr;	// @[src/main/bus/Xbar.scala:525:32]
    if (io_dmem_awvalid)	// @[src/main/bus/Xbar.scala:435:16]
      dmem_awaddr <= io_dmem_awaddr;	// @[src/main/bus/Xbar.scala:526:32]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/bus/Xbar.scala:434:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:8];	// @[src/main/bus/Xbar.scala:434:7]
    initial begin	// @[src/main/bus/Xbar.scala:434:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar.scala:434:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar.scala:434:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/bus/Xbar.scala:434:7]
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/bus/Xbar.scala:434:7]
        end	// @[src/main/bus/Xbar.scala:434:7]
        soc_araddr = _RANDOM[4'h0];	// @[src/main/bus/Xbar.scala:434:7, :438:29]
        soc_arvalid = _RANDOM[4'h1][0];	// @[src/main/bus/Xbar.scala:434:7, :439:30]
        soc_arid = _RANDOM[4'h1][4:1];	// @[src/main/bus/Xbar.scala:434:7, :439:30, :440:27]
        soc_arlen = _RANDOM[4'h1][12:5];	// @[src/main/bus/Xbar.scala:434:7, :439:30, :441:28]
        soc_arsize = _RANDOM[4'h1][15:13];	// @[src/main/bus/Xbar.scala:434:7, :439:30, :442:29]
        soc_arburst = _RANDOM[4'h1][17:16];	// @[src/main/bus/Xbar.scala:434:7, :439:30, :443:30]
        soc_rready = _RANDOM[4'h1][18];	// @[src/main/bus/Xbar.scala:434:7, :439:30, :444:29]
        soc_awaddr = {_RANDOM[4'h1][31:19], _RANDOM[4'h2][18:0]};	// @[src/main/bus/Xbar.scala:434:7, :439:30, :445:29]
        soc_awvalid = _RANDOM[4'h2][19];	// @[src/main/bus/Xbar.scala:434:7, :445:29, :446:30]
        soc_awid = _RANDOM[4'h2][23:20];	// @[src/main/bus/Xbar.scala:434:7, :445:29, :447:27]
        soc_awlen = _RANDOM[4'h2][31:24];	// @[src/main/bus/Xbar.scala:434:7, :445:29, :448:28]
        soc_awsize = _RANDOM[4'h3][2:0];	// @[src/main/bus/Xbar.scala:434:7, :449:29]
        soc_awburst = _RANDOM[4'h3][4:3];	// @[src/main/bus/Xbar.scala:434:7, :449:29, :450:30]
        soc_wdata = {_RANDOM[4'h3][31:5], _RANDOM[4'h4][4:0]};	// @[src/main/bus/Xbar.scala:434:7, :449:29, :451:28]
        soc_wstrb = _RANDOM[4'h4][8:5];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :452:28]
        soc_wvalid = _RANDOM[4'h4][9];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :453:29]
        soc_wlast = _RANDOM[4'h4][10];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :454:28]
        soc_bready = _RANDOM[4'h4][11];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :455:29]
        soc_rvalid_r = _RANDOM[4'h4][12];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :474:31]
        soc_bvalid_r = _RANDOM[4'h4][14];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :476:31]
        burstCnt = _RANDOM[4'h4][27:20];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :483:37]
        c_state = _RANDOM[4'h4][29:28];	// @[src/main/bus/Xbar.scala:434:7, :451:28, :486:26]
        imem_araddr = {_RANDOM[4'h4][31:30], _RANDOM[4'h5][29:0]};	// @[src/main/bus/Xbar.scala:434:7, :451:28, :521:32]
        imem_arburst = _RANDOM[4'h5][31:30];	// @[src/main/bus/Xbar.scala:434:7, :521:32, :522:33]
        imem_arlen = _RANDOM[4'h6][7:0];	// @[src/main/bus/Xbar.scala:434:7, :523:31]
        imem_arsize = _RANDOM[4'h6][10:8];	// @[src/main/bus/Xbar.scala:434:7, :523:31, :524:32]
        dmem_araddr = {_RANDOM[4'h6][31:11], _RANDOM[4'h7][10:0]};	// @[src/main/bus/Xbar.scala:434:7, :523:31, :525:32]
        dmem_awaddr = {_RANDOM[4'h7][31:11], _RANDOM[4'h8][10:0]};	// @[src/main/bus/Xbar.scala:434:7, :525:32, :526:32]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_imem_arready = _GEN | ~_GEN_0 | io_soc_arready;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :568:25, :667:25]
  assign io_imem_rdata = io_soc_rdata;	// @[src/main/bus/Xbar.scala:434:7]
  assign io_imem_rresp = _GEN_1 ? 2'h0 : io_soc_rresp;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :528:20, :618:21, :625:21, :669:23, :700:21, :707:21]
  assign io_imem_rvalid = ~_GEN & _GEN_0 & io_soc_rvalid;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :670:24]
  assign io_dmem_arready = _GEN_6 | ~_GEN_5 | io_soc_arready;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :601:25, :681:25]
  assign io_dmem_rdata = io_soc_rdata;	// @[src/main/bus/Xbar.scala:434:7]
  assign io_dmem_rvalid = ~_GEN_6 & _GEN_5 & io_soc_rvalid;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :681:25, :684:24]
  assign io_dmem_awready = _GEN_6 | ~_GEN_5 | io_soc_awready;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :601:25, :681:25, :687:25]
  assign io_dmem_wready = _GEN_6 | ~_GEN_5 | io_soc_wready;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :601:25, :681:25, :688:24]
  assign io_dmem_bvalid = ~_GEN_6 & _GEN_5 & io_soc_bvalid;	// @[src/main/bus/Xbar.scala:434:7, :528:20, :681:25, :684:24, :690:24]
  assign io_soc_araddr = soc_araddr;	// @[src/main/bus/Xbar.scala:434:7, :438:29]
  assign io_soc_arvalid = soc_arvalid;	// @[src/main/bus/Xbar.scala:434:7, :439:30]
  assign io_soc_arid = soc_arid;	// @[src/main/bus/Xbar.scala:434:7, :440:27]
  assign io_soc_arlen = soc_arlen;	// @[src/main/bus/Xbar.scala:434:7, :441:28]
  assign io_soc_arsize = soc_arsize;	// @[src/main/bus/Xbar.scala:434:7, :442:29]
  assign io_soc_arburst = soc_arburst;	// @[src/main/bus/Xbar.scala:434:7, :443:30]
  assign io_soc_rready = soc_rready;	// @[src/main/bus/Xbar.scala:434:7, :444:29]
  assign io_soc_awaddr = soc_awaddr;	// @[src/main/bus/Xbar.scala:434:7, :445:29]
  assign io_soc_awvalid = soc_awvalid;	// @[src/main/bus/Xbar.scala:434:7, :446:30]
  assign io_soc_awid = soc_awid;	// @[src/main/bus/Xbar.scala:434:7, :447:27]
  assign io_soc_awlen = soc_awlen;	// @[src/main/bus/Xbar.scala:434:7, :448:28]
  assign io_soc_awsize = soc_awsize;	// @[src/main/bus/Xbar.scala:434:7, :449:29]
  assign io_soc_awburst = soc_awburst;	// @[src/main/bus/Xbar.scala:434:7, :450:30]
  assign io_soc_wdata = soc_wdata;	// @[src/main/bus/Xbar.scala:434:7, :451:28]
  assign io_soc_wstrb = soc_wstrb;	// @[src/main/bus/Xbar.scala:434:7, :452:28]
  assign io_soc_wvalid = soc_wvalid;	// @[src/main/bus/Xbar.scala:434:7, :453:29]
  assign io_soc_wlast = soc_wlast;	// @[src/main/bus/Xbar.scala:434:7, :454:28]
  assign io_soc_bready = soc_bready;	// @[src/main/bus/Xbar.scala:434:7, :455:29]
endmodule

