// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Xbar(	// @[src/main/bus/Xbar.scala:434:7]
  input         clock,	// @[src/main/bus/Xbar.scala:434:7]
                reset,	// @[src/main/bus/Xbar.scala:434:7]
  input  [31:0] io_imem_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_imem_arready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_imem_arid,	// @[src/main/bus/Xbar.scala:435:16]
  input  [7:0]  io_imem_arlen,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_imem_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [1:0]  io_imem_arburst,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_imem_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  output [1:0]  io_imem_rresp,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_imem_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_rready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_imem_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_imem_awid,	// @[src/main/bus/Xbar.scala:435:16]
  input  [7:0]  io_imem_awlen,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_imem_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [1:0]  io_imem_awburst,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_imem_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_imem_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_imem_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
                io_imem_wlast,	// @[src/main/bus/Xbar.scala:435:16]
                io_imem_bready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_dmem_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_arready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_dmem_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_dmem_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_rready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_dmem_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_awready,	// @[src/main/bus/Xbar.scala:435:16]
  input  [2:0]  io_dmem_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_dmem_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  input  [3:0]  io_dmem_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_dmem_wready,	// @[src/main/bus/Xbar.scala:435:16]
                io_dmem_bvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_dmem_bready,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_soc_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_arready,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_soc_arid,	// @[src/main/bus/Xbar.scala:435:16]
  output [7:0]  io_soc_arlen,	// @[src/main/bus/Xbar.scala:435:16]
  output [2:0]  io_soc_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [1:0]  io_soc_arburst,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_soc_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  input  [1:0]  io_soc_rresp,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_rready,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_soc_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_awready,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_soc_awid,	// @[src/main/bus/Xbar.scala:435:16]
  output [7:0]  io_soc_awlen,	// @[src/main/bus/Xbar.scala:435:16]
  output [2:0]  io_soc_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [1:0]  io_soc_awburst,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_soc_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_soc_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_wready,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_wlast,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_soc_bvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_soc_bready,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_clint_araddr,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_clint_arvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_clint_arready,	// @[src/main/bus/Xbar.scala:435:16]
  output [2:0]  io_clint_arsize,	// @[src/main/bus/Xbar.scala:435:16]
  input  [31:0] io_clint_rdata,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_clint_rvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_clint_rready,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_clint_awaddr,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_clint_awvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_clint_awready,	// @[src/main/bus/Xbar.scala:435:16]
  output [2:0]  io_clint_awsize,	// @[src/main/bus/Xbar.scala:435:16]
  output [31:0] io_clint_wdata,	// @[src/main/bus/Xbar.scala:435:16]
  output [3:0]  io_clint_wstrb,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_clint_wvalid,	// @[src/main/bus/Xbar.scala:435:16]
  input         io_clint_wready,	// @[src/main/bus/Xbar.scala:435:16]
                io_clint_bvalid,	// @[src/main/bus/Xbar.scala:435:16]
  output        io_clint_bready	// @[src/main/bus/Xbar.scala:435:16]
);

  reg  [31:0] soc_araddr;	// @[src/main/bus/Xbar.scala:441:29]
  reg         soc_arvalid;	// @[src/main/bus/Xbar.scala:442:30]
  reg  [3:0]  soc_arid;	// @[src/main/bus/Xbar.scala:443:27]
  reg  [7:0]  soc_arlen;	// @[src/main/bus/Xbar.scala:444:28]
  reg  [2:0]  soc_arsize;	// @[src/main/bus/Xbar.scala:445:29]
  reg  [1:0]  soc_arburst;	// @[src/main/bus/Xbar.scala:446:30]
  reg         soc_rready;	// @[src/main/bus/Xbar.scala:447:29]
  reg  [31:0] soc_awaddr;	// @[src/main/bus/Xbar.scala:448:29]
  reg         soc_awvalid;	// @[src/main/bus/Xbar.scala:449:30]
  reg  [3:0]  soc_awid;	// @[src/main/bus/Xbar.scala:450:27]
  reg  [7:0]  soc_awlen;	// @[src/main/bus/Xbar.scala:451:28]
  reg  [2:0]  soc_awsize;	// @[src/main/bus/Xbar.scala:452:29]
  reg  [1:0]  soc_awburst;	// @[src/main/bus/Xbar.scala:453:30]
  reg  [31:0] soc_wdata;	// @[src/main/bus/Xbar.scala:454:28]
  reg  [3:0]  soc_wstrb;	// @[src/main/bus/Xbar.scala:455:28]
  reg         soc_wvalid;	// @[src/main/bus/Xbar.scala:456:29]
  reg         soc_wlast;	// @[src/main/bus/Xbar.scala:457:28]
  reg         soc_bready;	// @[src/main/bus/Xbar.scala:458:29]
  reg         soc_rvalid_r;	// @[src/main/bus/Xbar.scala:477:31]
  reg         soc_bvalid_r;	// @[src/main/bus/Xbar.scala:479:31]
  reg         clint_rvalid_r;	// @[src/main/bus/Xbar.scala:481:33]
  reg         clint_bvalid_r;	// @[src/main/bus/Xbar.scala:483:33]
  reg  [7:0]  burstCnt;	// @[src/main/bus/Xbar.scala:486:37]
  reg  [1:0]  c_state;	// @[src/main/bus/Xbar.scala:489:26]
  reg  [1:0]  casez_tmp;	// @[src/main/bus/Xbar.scala:508:42]
  wire        isclint_raddr = (|(io_dmem_araddr[31:25])) & io_dmem_araddr < 32'h2010000;	// @[src/main/bus/Xbar.scala:493:{41,65,83}]
  wire        isclint_waddr = (|(io_dmem_awaddr[31:25])) & io_dmem_awaddr < 32'h2010000;	// @[src/main/bus/Xbar.scala:493:83, :494:{41,65,83}]
  always_comb begin	// @[src/main/bus/Xbar.scala:508:42]
    casez (c_state)	// @[src/main/bus/Xbar.scala:489:26, :508:42]
      2'b00:
        casez_tmp =
          io_imem_arvalid
            ? 2'h1
            : io_dmem_arvalid & ~isclint_raddr | io_dmem_awvalid & ~isclint_waddr
                ? 2'h2
                : {2{io_dmem_arvalid & isclint_raddr | io_dmem_awvalid & isclint_waddr}};	// @[src/main/bus/Xbar.scala:493:65, :494:65, :499:{40,42,58,74,76}, :500:{42,59,75}, :508:42, src/main/scala/chisel3/util/Mux.scala:126:16]
      2'b01:
        casez_tmp =
          ~io_soc_rvalid & soc_rvalid_r & soc_rready & ~(|burstCnt)
            ? {1'h0, io_imem_arvalid}
            : 2'h1;	// @[src/main/bus/Xbar.scala:437:29, :447:29, :477:31, :486:37, :502:{22,65,76}, :508:42, :514:{27,43}, src/main/scala/chisel3/util/Mux.scala:126:16]
      2'b10:
        casez_tmp =
          {~(~io_soc_rvalid & soc_rvalid_r & soc_rready | ~io_soc_bvalid & soc_bvalid_r
             & soc_bready),
           1'h0};	// @[src/main/bus/Xbar.scala:437:29, :447:29, :458:29, :477:31, :479:31, :502:22, :503:{53,67,70,100}, :508:42, :515:27]
      default:
        casez_tmp =
          ~io_clint_rvalid & clint_rvalid_r | ~io_clint_bvalid & clint_bvalid_r
            ? 2'h0
            : 2'h3;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :481:33, :483:33, :504:{25,42,60,63,80}, :508:42, :516:27, :531:20, :626:21, :633:21, :708:21, :715:21, src/main/scala/chisel3/util/Mux.scala:126:16]
    endcase	// @[src/main/bus/Xbar.scala:489:26, :508:42]
  end // always_comb
  wire [1:0]  n_state = casez_tmp;	// @[src/main/bus/Xbar.scala:490:30, :508:42]
  reg  [31:0] imem_araddr;	// @[src/main/bus/Xbar.scala:524:32]
  reg  [1:0]  imem_arburst;	// @[src/main/bus/Xbar.scala:525:33]
  reg  [7:0]  imem_arlen;	// @[src/main/bus/Xbar.scala:526:31]
  reg  [2:0]  imem_arsize;	// @[src/main/bus/Xbar.scala:527:32]
  reg  [31:0] dmem_araddr;	// @[src/main/bus/Xbar.scala:528:32]
  reg  [31:0] dmem_awaddr;	// @[src/main/bus/Xbar.scala:529:32]
  wire        _GEN = n_state == 2'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :490:30, :531:20, :626:21, :633:21, :708:21, :715:21]
  wire        _GEN_0 = n_state == 2'h1;	// @[src/main/bus/Xbar.scala:490:30, :531:20, src/main/scala/chisel3/util/Mux.scala:126:16]
  wire        _GEN_1 = _GEN | ~_GEN_0;	// @[src/main/bus/Xbar.scala:531:20, :576:25, :675:25, :677:23]
  wire        _GEN_2 = soc_arvalid & io_soc_arready;	// @[src/main/bus/Xbar.scala:442:30, :536:33]
  wire        _GEN_3 = soc_arvalid & ~io_soc_arready;	// @[src/main/bus/Xbar.scala:442:30, :538:{39,41}]
  wire        _GEN_4 = _GEN_2 | ~_GEN_3;	// @[src/main/bus/Xbar.scala:536:{33,50}, :538:{39,57}, :588:20]
  wire        _GEN_5 = n_state == 2'h2;	// @[src/main/bus/Xbar.scala:490:30, :531:20, src/main/scala/chisel3/util/Mux.scala:126:16]
  reg  [2:0]  casez_tmp_0;	// @[src/main/bus/Xbar.scala:531:20, :707:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:531:20, :536:50, :625:20, :707:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:490:30, :531:20, :536:50, :625:20, :707:20]
      2'b00:
        casez_tmp_0 = 3'h0;	// @[src/main/bus/Xbar.scala:531:20, :536:50, :625:20, :707:20, :728:25]
      2'b01:
        casez_tmp_0 = _GEN_4 ? io_imem_arsize : imem_arsize;	// @[src/main/bus/Xbar.scala:527:32, :531:20, :536:50, :538:57, :588:20, :592:20, :625:20, :707:20]
      2'b10:
        casez_tmp_0 = io_dmem_arsize;	// @[src/main/bus/Xbar.scala:531:20, :536:50, :625:20, :707:20]
      default:
        casez_tmp_0 = 3'h0;	// @[src/main/bus/Xbar.scala:531:20, :536:50, :625:20, :707:20, :728:25]
    endcase	// @[src/main/bus/Xbar.scala:490:30, :531:20, :536:50, :625:20, :707:20]
  end // always_comb
  reg  [2:0]  casez_tmp_1;	// @[src/main/bus/Xbar.scala:531:20, :714:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:531:20, :599:20, :632:20, :714:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:490:30, :531:20, :599:20, :632:20, :714:20]
      2'b00:
        casez_tmp_1 = 3'h0;	// @[src/main/bus/Xbar.scala:531:20, :599:20, :632:20, :714:20, :728:25]
      2'b01:
        casez_tmp_1 = io_imem_awsize;	// @[src/main/bus/Xbar.scala:531:20, :599:20, :632:20, :714:20]
      2'b10:
        casez_tmp_1 = io_dmem_awsize;	// @[src/main/bus/Xbar.scala:531:20, :599:20, :632:20, :714:20]
      default:
        casez_tmp_1 = 3'h0;	// @[src/main/bus/Xbar.scala:531:20, :599:20, :632:20, :714:20, :728:25]
    endcase	// @[src/main/bus/Xbar.scala:490:30, :531:20, :599:20, :632:20, :714:20]
  end // always_comb
  reg  [31:0] casez_tmp_2;	// @[src/main/bus/Xbar.scala:531:20, :716:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:531:20, :601:19, :634:19, :716:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:490:30, :531:20, :601:19, :634:19, :716:19]
      2'b00:
        casez_tmp_2 = 32'h0;	// @[src/main/bus/Xbar.scala:531:20, :601:19, :634:19, :716:19, :724:25]
      2'b01:
        casez_tmp_2 = io_imem_wdata;	// @[src/main/bus/Xbar.scala:531:20, :601:19, :634:19, :716:19]
      2'b10:
        casez_tmp_2 = io_dmem_wdata;	// @[src/main/bus/Xbar.scala:531:20, :601:19, :634:19, :716:19]
      default:
        casez_tmp_2 = 32'h0;	// @[src/main/bus/Xbar.scala:531:20, :601:19, :634:19, :716:19, :724:25]
    endcase	// @[src/main/bus/Xbar.scala:490:30, :531:20, :601:19, :634:19, :716:19]
  end // always_comb
  reg  [3:0]  casez_tmp_3;	// @[src/main/bus/Xbar.scala:531:20, :717:19]
  always_comb begin	// @[src/main/bus/Xbar.scala:531:20, :602:19, :635:19, :717:19]
    casez (n_state)	// @[src/main/bus/Xbar.scala:490:30, :531:20, :602:19, :635:19, :717:19]
      2'b00:
        casez_tmp_3 = 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :602:19, :635:19, :717:19]
      2'b01:
        casez_tmp_3 = io_imem_wstrb;	// @[src/main/bus/Xbar.scala:531:20, :602:19, :635:19, :717:19]
      2'b10:
        casez_tmp_3 = io_dmem_wstrb;	// @[src/main/bus/Xbar.scala:531:20, :602:19, :635:19, :717:19]
      default:
        casez_tmp_3 = 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :602:19, :635:19, :717:19]
    endcase	// @[src/main/bus/Xbar.scala:490:30, :531:20, :602:19, :635:19, :717:19]
  end // always_comb
  reg  [31:0] casez_tmp_4;	// @[src/main/bus/Xbar.scala:531:20, :703:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:531:20, :536:50, :549:50, :703:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:490:30, :531:20, :536:50, :549:50, :703:20]
      2'b00:
        casez_tmp_4 = 32'h0;	// @[src/main/bus/Xbar.scala:531:20, :536:50, :549:50, :703:20, :724:25]
      2'b01:
        casez_tmp_4 = _GEN_4 ? io_imem_araddr : imem_araddr;	// @[src/main/bus/Xbar.scala:524:32, :531:20, :536:50, :538:57, :549:50, :588:20, :703:20]
      2'b10:
        casez_tmp_4 = _GEN_4 ? io_dmem_araddr : dmem_araddr;	// @[src/main/bus/Xbar.scala:528:32, :531:20, :536:50, :538:57, :549:50, :551:57, :588:20, :621:20, :703:20]
      default:
        casez_tmp_4 = 32'h0;	// @[src/main/bus/Xbar.scala:531:20, :536:50, :549:50, :703:20, :724:25]
    endcase	// @[src/main/bus/Xbar.scala:490:30, :531:20, :536:50, :549:50, :703:20]
  end // always_comb
  wire        _GEN_6 = soc_awvalid & io_soc_awready;	// @[src/main/bus/Xbar.scala:449:30, :555:33]
  wire        _GEN_7 = soc_awvalid & ~io_soc_awready;	// @[src/main/bus/Xbar.scala:449:30, :557:{39,41}]
  reg  [31:0] casez_tmp_5;	// @[src/main/bus/Xbar.scala:531:20, :710:20]
  always_comb begin	// @[src/main/bus/Xbar.scala:531:20, :555:50, :595:20, :710:20]
    casez (n_state)	// @[src/main/bus/Xbar.scala:490:30, :531:20, :555:50, :595:20, :710:20]
      2'b00:
        casez_tmp_5 = 32'h0;	// @[src/main/bus/Xbar.scala:531:20, :555:50, :595:20, :710:20, :724:25]
      2'b01:
        casez_tmp_5 = io_imem_awaddr;	// @[src/main/bus/Xbar.scala:531:20, :555:50, :595:20, :710:20]
      2'b10:
        casez_tmp_5 = _GEN_6 | ~_GEN_7 ? io_dmem_awaddr : dmem_awaddr;	// @[src/main/bus/Xbar.scala:529:32, :531:20, :555:{33,50}, :557:{39,57}, :595:20, :628:20, :710:20]
      default:
        casez_tmp_5 = 32'h0;	// @[src/main/bus/Xbar.scala:531:20, :555:50, :595:20, :710:20, :724:25]
    endcase	// @[src/main/bus/Xbar.scala:490:30, :531:20, :555:50, :595:20, :710:20]
  end // always_comb
  wire        _GEN_8 = _GEN | _GEN_0;	// @[src/main/bus/Xbar.scala:531:20, :689:25]
  wire        _GEN_9 = _GEN | _GEN_0 | _GEN_5;	// @[src/main/bus/Xbar.scala:531:20, :724:25]
  wire        _GEN_10 = _GEN_9 | ~(&n_state);	// @[src/main/bus/Xbar.scala:490:30, :531:20, :642:25, :689:25, :724:25]
  always @(posedge clock) begin	// @[src/main/bus/Xbar.scala:434:7]
    if (reset) begin	// @[src/main/bus/Xbar.scala:434:7]
      soc_araddr <= 32'h0;	// @[src/main/bus/Xbar.scala:441:29, :724:25]
      soc_arvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:437:29, :442:30]
      soc_arid <= 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :443:27]
      soc_arlen <= 8'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :444:28, :531:20, :624:19, :631:19, :706:19, :713:19]
      soc_arsize <= 3'h0;	// @[src/main/bus/Xbar.scala:445:29, :728:25]
      soc_arburst <= 2'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :446:30, :531:20, :626:21, :633:21, :708:21, :715:21]
      soc_rready <= 1'h0;	// @[src/main/bus/Xbar.scala:437:29, :447:29]
      soc_awaddr <= 32'h0;	// @[src/main/bus/Xbar.scala:448:29, :724:25]
      soc_awvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:437:29, :449:30]
      soc_awid <= 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :450:27]
      soc_awlen <= 8'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :451:28, :531:20, :624:19, :631:19, :706:19, :713:19]
      soc_awsize <= 3'h0;	// @[src/main/bus/Xbar.scala:452:29, :728:25]
      soc_awburst <= 2'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :453:30, :531:20, :626:21, :633:21, :708:21, :715:21]
      soc_wdata <= 32'h0;	// @[src/main/bus/Xbar.scala:454:28, :724:25]
      soc_wstrb <= 4'h0;	// @[src/main/bus/Xbar.scala:434:7, :455:28]
      soc_wvalid <= 1'h0;	// @[src/main/bus/Xbar.scala:437:29, :456:29]
      soc_wlast <= 1'h1;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :457:28, :531:20, :637:19, :719:19]
      soc_bready <= 1'h0;	// @[src/main/bus/Xbar.scala:437:29, :458:29]
      burstCnt <= 8'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :486:37, :531:20, :624:19, :631:19, :706:19, :713:19]
      c_state <= 2'h0;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :489:26, :531:20, :626:21, :633:21, :708:21, :715:21]
    end
    else begin	// @[src/main/bus/Xbar.scala:434:7]
      soc_araddr <= casez_tmp_4;	// @[src/main/bus/Xbar.scala:441:29, :531:20, :703:20]
      soc_arvalid <=
        ~_GEN
        & (_GEN_0
             ? ~_GEN_2 & (_GEN_3 | io_imem_arvalid)
             : _GEN_5 & ~_GEN_2 & (_GEN_3 | io_dmem_arvalid));	// @[src/main/bus/Xbar.scala:442:30, :531:20, :536:{33,50}, :537:29, :538:{39,57}, :539:29, :549:50, :551:57, :552:29, :589:21, :622:21, :678:24, :704:21]
      soc_arid <= _GEN_1 ? 4'h0 : io_imem_arid;	// @[src/main/bus/Xbar.scala:434:7, :443:27, :531:20, :677:23, :705:18]
      soc_arlen <= _GEN_1 ? 8'h0 : _GEN_4 ? io_imem_arlen : imem_arlen;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :444:28, :526:31, :531:20, :536:50, :538:57, :588:20, :591:19, :624:19, :631:19, :677:23, :706:19, :713:19]
      soc_arsize <= casez_tmp_0;	// @[src/main/bus/Xbar.scala:445:29, :531:20, :707:20]
      soc_arburst <= _GEN_1 ? 2'h0 : _GEN_4 ? io_imem_arburst : imem_arburst;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :446:30, :525:33, :531:20, :536:50, :538:57, :588:20, :593:21, :626:21, :633:21, :677:23, :708:21, :715:21]
      soc_rready <= ~_GEN & (_GEN_0 ? io_imem_rready : _GEN_5 & io_dmem_rready);	// @[src/main/bus/Xbar.scala:447:29, :531:20, :594:20, :627:20, :678:24, :709:20]
      soc_awaddr <= casez_tmp_5;	// @[src/main/bus/Xbar.scala:448:29, :531:20, :710:20]
      soc_awvalid <=
        ~_GEN
        & (_GEN_0 ? io_imem_awvalid : _GEN_5 & ~_GEN_6 & (_GEN_7 | io_dmem_awvalid));	// @[src/main/bus/Xbar.scala:449:30, :531:20, :555:{33,50}, :556:29, :557:{39,57}, :558:29, :596:21, :629:21, :678:24, :711:21]
      soc_awid <= _GEN_1 ? 4'h0 : io_imem_awid;	// @[src/main/bus/Xbar.scala:434:7, :450:27, :531:20, :677:23, :712:18]
      soc_awlen <= _GEN_1 ? 8'h0 : io_imem_awlen;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :451:28, :531:20, :624:19, :631:19, :677:23, :706:19, :713:19]
      soc_awsize <= casez_tmp_1;	// @[src/main/bus/Xbar.scala:452:29, :531:20, :714:20]
      soc_awburst <= _GEN_1 ? 2'h0 : io_imem_awburst;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :453:30, :531:20, :626:21, :633:21, :677:23, :708:21, :715:21]
      soc_wdata <= casez_tmp_2;	// @[src/main/bus/Xbar.scala:454:28, :531:20, :716:19]
      soc_wstrb <= casez_tmp_3;	// @[src/main/bus/Xbar.scala:455:28, :531:20, :717:19]
      soc_wvalid <= ~_GEN & (_GEN_0 ? io_imem_wvalid : _GEN_5 & io_dmem_wvalid);	// @[src/main/bus/Xbar.scala:456:29, :531:20, :603:20, :636:20, :678:24, :718:20]
      soc_wlast <= _GEN | ~_GEN_0 | io_imem_wlast;	// @[src/main/bus/Xbar.scala:457:28, :531:20, :576:25, :675:25, :719:19]
      soc_bready <= ~_GEN & (_GEN_0 ? io_imem_bready : _GEN_5 & io_dmem_bready);	// @[src/main/bus/Xbar.scala:458:29, :531:20, :605:20, :638:20, :678:24, :720:20]
      if (_GEN_2)	// @[src/main/bus/Xbar.scala:536:33]
        burstCnt <= soc_arlen + 8'h1;	// @[src/main/bus/Xbar.scala:444:28, :486:37, :569:34]
      else if ((|burstCnt) & soc_rready & io_soc_rvalid)	// @[src/main/bus/Xbar.scala:447:29, :486:37, :502:76, :570:49]
        burstCnt <= burstCnt - 8'h1;	// @[src/main/bus/Xbar.scala:486:37, :571:30]
      c_state <= n_state;	// @[src/main/bus/Xbar.scala:489:26, :490:30]
    end
    soc_rvalid_r <= io_soc_rvalid;	// @[src/main/bus/Xbar.scala:477:31]
    soc_bvalid_r <= io_soc_bvalid;	// @[src/main/bus/Xbar.scala:479:31]
    clint_rvalid_r <= io_clint_rvalid;	// @[src/main/bus/Xbar.scala:481:33]
    clint_bvalid_r <= io_clint_bvalid;	// @[src/main/bus/Xbar.scala:483:33]
    if (io_imem_arvalid) begin	// @[src/main/bus/Xbar.scala:435:16]
      imem_araddr <= io_imem_araddr;	// @[src/main/bus/Xbar.scala:524:32]
      imem_arburst <= io_imem_arburst;	// @[src/main/bus/Xbar.scala:525:33]
      imem_arlen <= io_imem_arlen;	// @[src/main/bus/Xbar.scala:526:31]
      imem_arsize <= io_imem_arsize;	// @[src/main/bus/Xbar.scala:527:32]
    end
    if (io_dmem_arvalid)	// @[src/main/bus/Xbar.scala:435:16]
      dmem_araddr <= io_dmem_araddr;	// @[src/main/bus/Xbar.scala:528:32]
    if (io_dmem_awvalid)	// @[src/main/bus/Xbar.scala:435:16]
      dmem_awaddr <= io_dmem_awaddr;	// @[src/main/bus/Xbar.scala:529:32]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/bus/Xbar.scala:434:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:10];	// @[src/main/bus/Xbar.scala:434:7]
    initial begin	// @[src/main/bus/Xbar.scala:434:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar.scala:434:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/bus/Xbar.scala:434:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/bus/Xbar.scala:434:7]
        for (logic [3:0] i = 4'h0; i < 4'hB; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/bus/Xbar.scala:434:7]
        end	// @[src/main/bus/Xbar.scala:434:7]
        soc_araddr = _RANDOM[4'h2];	// @[src/main/bus/Xbar.scala:434:7, :441:29]
        soc_arvalid = _RANDOM[4'h3][0];	// @[src/main/bus/Xbar.scala:434:7, :442:30]
        soc_arid = _RANDOM[4'h3][4:1];	// @[src/main/bus/Xbar.scala:434:7, :442:30, :443:27]
        soc_arlen = _RANDOM[4'h3][12:5];	// @[src/main/bus/Xbar.scala:434:7, :442:30, :444:28]
        soc_arsize = _RANDOM[4'h3][15:13];	// @[src/main/bus/Xbar.scala:434:7, :442:30, :445:29]
        soc_arburst = _RANDOM[4'h3][17:16];	// @[src/main/bus/Xbar.scala:434:7, :442:30, :446:30]
        soc_rready = _RANDOM[4'h3][18];	// @[src/main/bus/Xbar.scala:434:7, :442:30, :447:29]
        soc_awaddr = {_RANDOM[4'h3][31:19], _RANDOM[4'h4][18:0]};	// @[src/main/bus/Xbar.scala:434:7, :442:30, :448:29]
        soc_awvalid = _RANDOM[4'h4][19];	// @[src/main/bus/Xbar.scala:434:7, :448:29, :449:30]
        soc_awid = _RANDOM[4'h4][23:20];	// @[src/main/bus/Xbar.scala:434:7, :448:29, :450:27]
        soc_awlen = _RANDOM[4'h4][31:24];	// @[src/main/bus/Xbar.scala:434:7, :448:29, :451:28]
        soc_awsize = _RANDOM[4'h5][2:0];	// @[src/main/bus/Xbar.scala:434:7, :452:29]
        soc_awburst = _RANDOM[4'h5][4:3];	// @[src/main/bus/Xbar.scala:434:7, :452:29, :453:30]
        soc_wdata = {_RANDOM[4'h5][31:5], _RANDOM[4'h6][4:0]};	// @[src/main/bus/Xbar.scala:434:7, :452:29, :454:28]
        soc_wstrb = _RANDOM[4'h6][8:5];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :455:28]
        soc_wvalid = _RANDOM[4'h6][9];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :456:29]
        soc_wlast = _RANDOM[4'h6][10];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :457:28]
        soc_bready = _RANDOM[4'h6][11];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :458:29]
        soc_rvalid_r = _RANDOM[4'h6][12];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :477:31]
        soc_bvalid_r = _RANDOM[4'h6][14];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :479:31]
        clint_rvalid_r = _RANDOM[4'h6][16];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :481:33]
        clint_bvalid_r = _RANDOM[4'h6][18];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :483:33]
        burstCnt = _RANDOM[4'h6][27:20];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :486:37]
        c_state = _RANDOM[4'h6][29:28];	// @[src/main/bus/Xbar.scala:434:7, :454:28, :489:26]
        imem_araddr = {_RANDOM[4'h6][31:30], _RANDOM[4'h7][29:0]};	// @[src/main/bus/Xbar.scala:434:7, :454:28, :524:32]
        imem_arburst = _RANDOM[4'h7][31:30];	// @[src/main/bus/Xbar.scala:434:7, :524:32, :525:33]
        imem_arlen = _RANDOM[4'h8][7:0];	// @[src/main/bus/Xbar.scala:434:7, :526:31]
        imem_arsize = _RANDOM[4'h8][10:8];	// @[src/main/bus/Xbar.scala:434:7, :526:31, :527:32]
        dmem_araddr = {_RANDOM[4'h8][31:11], _RANDOM[4'h9][10:0]};	// @[src/main/bus/Xbar.scala:434:7, :526:31, :528:32]
        dmem_awaddr = {_RANDOM[4'h9][31:11], _RANDOM[4'hA][10:0]};	// @[src/main/bus/Xbar.scala:434:7, :528:32, :529:32]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/bus/Xbar.scala:434:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_imem_arready = _GEN | ~_GEN_0 | io_soc_arready;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :576:25, :675:25]
  assign io_imem_rdata = io_soc_rdata;	// @[src/main/bus/Xbar.scala:434:7]
  assign io_imem_rresp = _GEN_1 ? 2'h0 : io_soc_rresp;	// @[src/main/bus/Xbar.scala:434:7, :435:16, :531:20, :626:21, :633:21, :677:23, :708:21, :715:21]
  assign io_imem_rvalid = ~_GEN & _GEN_0 & io_soc_rvalid;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :678:24]
  assign io_dmem_arready =
    _GEN_8 | (_GEN_5 ? io_soc_arready : ~(&n_state) | io_clint_arready);	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :609:25, :642:25, :689:25]
  assign io_dmem_rdata = _GEN_5 ? io_soc_rdata : io_clint_rdata;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :610:23]
  assign io_dmem_rvalid =
    ~_GEN_8 & (_GEN_5 ? io_soc_rvalid : (&n_state) & io_clint_rvalid);	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :612:24, :645:24, :689:25, :692:24]
  assign io_dmem_awready =
    _GEN_8 | (_GEN_5 ? io_soc_awready : ~(&n_state) | io_clint_awready);	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :615:25, :642:25, :648:25, :689:25, :695:25]
  assign io_dmem_wready =
    _GEN_8 | (_GEN_5 ? io_soc_wready : ~(&n_state) | io_clint_wready);	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :616:24, :642:25, :649:24, :689:25, :696:24]
  assign io_dmem_bvalid =
    ~_GEN_8 & (_GEN_5 ? io_soc_bvalid : (&n_state) & io_clint_bvalid);	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :618:24, :651:24, :689:25, :692:24, :698:24]
  assign io_soc_araddr = soc_araddr;	// @[src/main/bus/Xbar.scala:434:7, :441:29]
  assign io_soc_arvalid = soc_arvalid;	// @[src/main/bus/Xbar.scala:434:7, :442:30]
  assign io_soc_arid = soc_arid;	// @[src/main/bus/Xbar.scala:434:7, :443:27]
  assign io_soc_arlen = soc_arlen;	// @[src/main/bus/Xbar.scala:434:7, :444:28]
  assign io_soc_arsize = soc_arsize;	// @[src/main/bus/Xbar.scala:434:7, :445:29]
  assign io_soc_arburst = soc_arburst;	// @[src/main/bus/Xbar.scala:434:7, :446:30]
  assign io_soc_rready = soc_rready;	// @[src/main/bus/Xbar.scala:434:7, :447:29]
  assign io_soc_awaddr = soc_awaddr;	// @[src/main/bus/Xbar.scala:434:7, :448:29]
  assign io_soc_awvalid = soc_awvalid;	// @[src/main/bus/Xbar.scala:434:7, :449:30]
  assign io_soc_awid = soc_awid;	// @[src/main/bus/Xbar.scala:434:7, :450:27]
  assign io_soc_awlen = soc_awlen;	// @[src/main/bus/Xbar.scala:434:7, :451:28]
  assign io_soc_awsize = soc_awsize;	// @[src/main/bus/Xbar.scala:434:7, :452:29]
  assign io_soc_awburst = soc_awburst;	// @[src/main/bus/Xbar.scala:434:7, :453:30]
  assign io_soc_wdata = soc_wdata;	// @[src/main/bus/Xbar.scala:434:7, :454:28]
  assign io_soc_wstrb = soc_wstrb;	// @[src/main/bus/Xbar.scala:434:7, :455:28]
  assign io_soc_wvalid = soc_wvalid;	// @[src/main/bus/Xbar.scala:434:7, :456:29]
  assign io_soc_wlast = soc_wlast;	// @[src/main/bus/Xbar.scala:434:7, :457:28]
  assign io_soc_bready = soc_bready;	// @[src/main/bus/Xbar.scala:434:7, :458:29]
  assign io_clint_araddr = _GEN_10 ? 32'h0 : io_dmem_araddr;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :724:25]
  assign io_clint_arvalid = ~_GEN_9 & (&n_state) & io_dmem_arvalid;	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :724:25, :725:26]
  assign io_clint_arsize = _GEN_10 ? 3'h0 : io_dmem_arsize;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :724:25, :728:25]
  assign io_clint_rready = ~_GEN_9 & (&n_state) & io_dmem_rready;	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :724:25, :725:26, :730:25]
  assign io_clint_awaddr = _GEN_10 ? 32'h0 : io_dmem_awaddr;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :724:25, :731:25]
  assign io_clint_awvalid = ~_GEN_9 & (&n_state) & io_dmem_awvalid;	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :724:25, :725:26, :732:26]
  assign io_clint_awsize = _GEN_10 ? 3'h0 : io_dmem_awsize;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :724:25, :728:25, :735:25]
  assign io_clint_wdata = _GEN_10 ? 32'h0 : io_dmem_wdata;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :724:25, :737:24]
  assign io_clint_wstrb = _GEN_10 ? 4'h0 : io_dmem_wstrb;	// @[src/main/bus/Xbar.scala:434:7, :531:20, :724:25, :738:24]
  assign io_clint_wvalid = ~_GEN_9 & (&n_state) & io_dmem_wvalid;	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :724:25, :725:26, :739:25]
  assign io_clint_bready = ~_GEN_9 & (&n_state) & io_dmem_bready;	// @[src/main/bus/Xbar.scala:434:7, :490:30, :531:20, :724:25, :725:26, :741:25]
endmodule

