// Generated by CIRCT firtool-1.131.0
module ysyx_24080032(	// @[src/main/NPC.scala:16:7]
  input         clock,	// @[src/main/NPC.scala:16:7]
                reset,	// @[src/main/NPC.scala:16:7]
                io_interrupt,	// @[src/main/NPC.scala:20:20]
  output [31:0] io_master_araddr,	// @[src/main/NPC.scala:20:20]
  output        io_master_arvalid,	// @[src/main/NPC.scala:20:20]
  input         io_master_arready,	// @[src/main/NPC.scala:20:20]
  output [3:0]  io_master_arid,	// @[src/main/NPC.scala:20:20]
  output [7:0]  io_master_arlen,	// @[src/main/NPC.scala:20:20]
  output [2:0]  io_master_arsize,	// @[src/main/NPC.scala:20:20]
  output [1:0]  io_master_arburst,	// @[src/main/NPC.scala:20:20]
  input  [31:0] io_master_rdata,	// @[src/main/NPC.scala:20:20]
  input  [1:0]  io_master_rresp,	// @[src/main/NPC.scala:20:20]
  input         io_master_rvalid,	// @[src/main/NPC.scala:20:20]
  output        io_master_rready,	// @[src/main/NPC.scala:20:20]
  input         io_master_rlast,	// @[src/main/NPC.scala:20:20]
  input  [3:0]  io_master_rid,	// @[src/main/NPC.scala:20:20]
  output [31:0] io_master_awaddr,	// @[src/main/NPC.scala:20:20]
  output        io_master_awvalid,	// @[src/main/NPC.scala:20:20]
  input         io_master_awready,	// @[src/main/NPC.scala:20:20]
  output [3:0]  io_master_awid,	// @[src/main/NPC.scala:20:20]
  output [7:0]  io_master_awlen,	// @[src/main/NPC.scala:20:20]
  output [2:0]  io_master_awsize,	// @[src/main/NPC.scala:20:20]
  output [1:0]  io_master_awburst,	// @[src/main/NPC.scala:20:20]
  output [31:0] io_master_wdata,	// @[src/main/NPC.scala:20:20]
  output [3:0]  io_master_wstrb,	// @[src/main/NPC.scala:20:20]
  output        io_master_wvalid,	// @[src/main/NPC.scala:20:20]
  input         io_master_wready,	// @[src/main/NPC.scala:20:20]
  output        io_master_wlast,	// @[src/main/NPC.scala:20:20]
  input  [1:0]  io_master_bresp,	// @[src/main/NPC.scala:20:20]
  input         io_master_bvalid,	// @[src/main/NPC.scala:20:20]
  output        io_master_bready,	// @[src/main/NPC.scala:20:20]
  input  [3:0]  io_master_bid,	// @[src/main/NPC.scala:20:20]
  input  [31:0] io_slave_araddr,	// @[src/main/NPC.scala:20:20]
  input         io_slave_arvalid,	// @[src/main/NPC.scala:20:20]
  output        io_slave_arready,	// @[src/main/NPC.scala:20:20]
  input  [3:0]  io_slave_arid,	// @[src/main/NPC.scala:20:20]
  input  [7:0]  io_slave_arlen,	// @[src/main/NPC.scala:20:20]
  input  [2:0]  io_slave_arsize,	// @[src/main/NPC.scala:20:20]
  input  [1:0]  io_slave_arburst,	// @[src/main/NPC.scala:20:20]
  output [31:0] io_slave_rdata,	// @[src/main/NPC.scala:20:20]
  output [1:0]  io_slave_rresp,	// @[src/main/NPC.scala:20:20]
  output        io_slave_rvalid,	// @[src/main/NPC.scala:20:20]
  input         io_slave_rready,	// @[src/main/NPC.scala:20:20]
  output        io_slave_rlast,	// @[src/main/NPC.scala:20:20]
  output [3:0]  io_slave_rid,	// @[src/main/NPC.scala:20:20]
  input  [31:0] io_slave_awaddr,	// @[src/main/NPC.scala:20:20]
  input         io_slave_awvalid,	// @[src/main/NPC.scala:20:20]
  output        io_slave_awready,	// @[src/main/NPC.scala:20:20]
  input  [3:0]  io_slave_awid,	// @[src/main/NPC.scala:20:20]
  input  [7:0]  io_slave_awlen,	// @[src/main/NPC.scala:20:20]
  input  [2:0]  io_slave_awsize,	// @[src/main/NPC.scala:20:20]
  input  [1:0]  io_slave_awburst,	// @[src/main/NPC.scala:20:20]
  input  [31:0] io_slave_wdata,	// @[src/main/NPC.scala:20:20]
  input  [3:0]  io_slave_wstrb,	// @[src/main/NPC.scala:20:20]
  input         io_slave_wvalid,	// @[src/main/NPC.scala:20:20]
  output        io_slave_wready,	// @[src/main/NPC.scala:20:20]
  input         io_slave_wlast,	// @[src/main/NPC.scala:20:20]
  output [1:0]  io_slave_bresp,	// @[src/main/NPC.scala:20:20]
  output        io_slave_bvalid,	// @[src/main/NPC.scala:20:20]
  input         io_slave_bready,	// @[src/main/NPC.scala:20:20]
  output [3:0]  io_slave_bid	// @[src/main/NPC.scala:20:20]
);

  wire        _clint_io_axi4_arready;	// @[src/main/NPC.scala:60:27]
  wire [31:0] _clint_io_axi4_rdata;	// @[src/main/NPC.scala:60:27]
  wire        _clint_io_axi4_rvalid;	// @[src/main/NPC.scala:60:27]
  wire        _xbar_io_imem_arready;	// @[src/main/NPC.scala:59:26]
  wire [31:0] _xbar_io_imem_rdata;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_imem_rvalid;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_imem_rlast;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_dmem_arready;	// @[src/main/NPC.scala:59:26]
  wire [31:0] _xbar_io_dmem_rdata;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_dmem_rvalid;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_dmem_awready;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_dmem_wready;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_dmem_bvalid;	// @[src/main/NPC.scala:59:26]
  wire [31:0] _xbar_io_clint_araddr;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_clint_arvalid;	// @[src/main/NPC.scala:59:26]
  wire        _xbar_io_clint_rready;	// @[src/main/NPC.scala:59:26]
  wire [31:0] _core_io_imem_araddr;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_imem_arvalid;	// @[src/main/NPC.scala:58:26]
  wire [2:0]  _core_io_imem_arsize;	// @[src/main/NPC.scala:58:26]
  wire [1:0]  _core_io_imem_arburst;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_imem_rready;	// @[src/main/NPC.scala:58:26]
  wire [31:0] _core_io_dmem_araddr;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_dmem_arvalid;	// @[src/main/NPC.scala:58:26]
  wire [2:0]  _core_io_dmem_arsize;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_dmem_rready;	// @[src/main/NPC.scala:58:26]
  wire [31:0] _core_io_dmem_awaddr;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_dmem_awvalid;	// @[src/main/NPC.scala:58:26]
  wire [2:0]  _core_io_dmem_awsize;	// @[src/main/NPC.scala:58:26]
  wire [31:0] _core_io_dmem_wdata;	// @[src/main/NPC.scala:58:26]
  wire [3:0]  _core_io_dmem_wstrb;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_dmem_wvalid;	// @[src/main/NPC.scala:58:26]
  wire        _core_io_dmem_bready;	// @[src/main/NPC.scala:58:26]
  ysyx_24080032_Core core (	// @[src/main/NPC.scala:58:26]
    .clock           (clock),
    .reset           (reset),
    .io_imem_araddr  (_core_io_imem_araddr),
    .io_imem_arvalid (_core_io_imem_arvalid),
    .io_imem_arready (_xbar_io_imem_arready),	// @[src/main/NPC.scala:59:26]
    .io_imem_arsize  (_core_io_imem_arsize),
    .io_imem_arburst (_core_io_imem_arburst),
    .io_imem_rdata   (_xbar_io_imem_rdata),	// @[src/main/NPC.scala:59:26]
    .io_imem_rvalid  (_xbar_io_imem_rvalid),	// @[src/main/NPC.scala:59:26]
    .io_imem_rready  (_core_io_imem_rready),
    .io_imem_rlast   (_xbar_io_imem_rlast),	// @[src/main/NPC.scala:59:26]
    .io_dmem_araddr  (_core_io_dmem_araddr),
    .io_dmem_arvalid (_core_io_dmem_arvalid),
    .io_dmem_arready (_xbar_io_dmem_arready),	// @[src/main/NPC.scala:59:26]
    .io_dmem_arsize  (_core_io_dmem_arsize),
    .io_dmem_rdata   (_xbar_io_dmem_rdata),	// @[src/main/NPC.scala:59:26]
    .io_dmem_rvalid  (_xbar_io_dmem_rvalid),	// @[src/main/NPC.scala:59:26]
    .io_dmem_rready  (_core_io_dmem_rready),
    .io_dmem_awaddr  (_core_io_dmem_awaddr),
    .io_dmem_awvalid (_core_io_dmem_awvalid),
    .io_dmem_awready (_xbar_io_dmem_awready),	// @[src/main/NPC.scala:59:26]
    .io_dmem_awsize  (_core_io_dmem_awsize),
    .io_dmem_wdata   (_core_io_dmem_wdata),
    .io_dmem_wstrb   (_core_io_dmem_wstrb),
    .io_dmem_wvalid  (_core_io_dmem_wvalid),
    .io_dmem_wready  (_xbar_io_dmem_wready),	// @[src/main/NPC.scala:59:26]
    .io_dmem_bvalid  (_xbar_io_dmem_bvalid),	// @[src/main/NPC.scala:59:26]
    .io_dmem_bready  (_core_io_dmem_bready)
  );	// @[src/main/NPC.scala:58:26]
  ysyx_24080032_Xbar xbar (	// @[src/main/NPC.scala:59:26]
    .clock            (clock),
    .reset            (reset),
    .io_imem_araddr   (_core_io_imem_araddr),	// @[src/main/NPC.scala:58:26]
    .io_imem_arvalid  (_core_io_imem_arvalid),	// @[src/main/NPC.scala:58:26]
    .io_imem_arready  (_xbar_io_imem_arready),
    .io_imem_arsize   (_core_io_imem_arsize),	// @[src/main/NPC.scala:58:26]
    .io_imem_arburst  (_core_io_imem_arburst),	// @[src/main/NPC.scala:58:26]
    .io_imem_rdata    (_xbar_io_imem_rdata),
    .io_imem_rvalid   (_xbar_io_imem_rvalid),
    .io_imem_rready   (_core_io_imem_rready),	// @[src/main/NPC.scala:58:26]
    .io_imem_rlast    (_xbar_io_imem_rlast),
    .io_dmem_araddr   (_core_io_dmem_araddr),	// @[src/main/NPC.scala:58:26]
    .io_dmem_arvalid  (_core_io_dmem_arvalid),	// @[src/main/NPC.scala:58:26]
    .io_dmem_arready  (_xbar_io_dmem_arready),
    .io_dmem_arsize   (_core_io_dmem_arsize),	// @[src/main/NPC.scala:58:26]
    .io_dmem_rdata    (_xbar_io_dmem_rdata),
    .io_dmem_rvalid   (_xbar_io_dmem_rvalid),
    .io_dmem_rready   (_core_io_dmem_rready),	// @[src/main/NPC.scala:58:26]
    .io_dmem_awaddr   (_core_io_dmem_awaddr),	// @[src/main/NPC.scala:58:26]
    .io_dmem_awvalid  (_core_io_dmem_awvalid),	// @[src/main/NPC.scala:58:26]
    .io_dmem_awready  (_xbar_io_dmem_awready),
    .io_dmem_awsize   (_core_io_dmem_awsize),	// @[src/main/NPC.scala:58:26]
    .io_dmem_wdata    (_core_io_dmem_wdata),	// @[src/main/NPC.scala:58:26]
    .io_dmem_wstrb    (_core_io_dmem_wstrb),	// @[src/main/NPC.scala:58:26]
    .io_dmem_wvalid   (_core_io_dmem_wvalid),	// @[src/main/NPC.scala:58:26]
    .io_dmem_wready   (_xbar_io_dmem_wready),
    .io_dmem_bvalid   (_xbar_io_dmem_bvalid),
    .io_dmem_bready   (_core_io_dmem_bready),	// @[src/main/NPC.scala:58:26]
    .io_soc_araddr    (io_master_araddr),
    .io_soc_arvalid   (io_master_arvalid),
    .io_soc_arready   (io_master_arready),
    .io_soc_arsize    (io_master_arsize),
    .io_soc_arburst   (io_master_arburst),
    .io_soc_rdata     (io_master_rdata),
    .io_soc_rvalid    (io_master_rvalid),
    .io_soc_rready    (io_master_rready),
    .io_soc_rlast     (io_master_rlast),
    .io_soc_awaddr    (io_master_awaddr),
    .io_soc_awvalid   (io_master_awvalid),
    .io_soc_awready   (io_master_awready),
    .io_soc_awsize    (io_master_awsize),
    .io_soc_wdata     (io_master_wdata),
    .io_soc_wstrb     (io_master_wstrb),
    .io_soc_wvalid    (io_master_wvalid),
    .io_soc_wready    (io_master_wready),
    .io_soc_wlast     (io_master_wlast),
    .io_soc_bvalid    (io_master_bvalid),
    .io_soc_bready    (io_master_bready),
    .io_clint_araddr  (_xbar_io_clint_araddr),
    .io_clint_arvalid (_xbar_io_clint_arvalid),
    .io_clint_arready (_clint_io_axi4_arready),	// @[src/main/NPC.scala:60:27]
    .io_clint_rdata   (_clint_io_axi4_rdata),	// @[src/main/NPC.scala:60:27]
    .io_clint_rvalid  (_clint_io_axi4_rvalid),	// @[src/main/NPC.scala:60:27]
    .io_clint_rready  (_xbar_io_clint_rready)
  );	// @[src/main/NPC.scala:59:26]
  ysyx_24080032_Clint clint (	// @[src/main/NPC.scala:60:27]
    .clock           (clock),
    .reset           (reset),
    .io_axi4_araddr  (_xbar_io_clint_araddr),	// @[src/main/NPC.scala:59:26]
    .io_axi4_arvalid (_xbar_io_clint_arvalid),	// @[src/main/NPC.scala:59:26]
    .io_axi4_arready (_clint_io_axi4_arready),
    .io_axi4_rdata   (_clint_io_axi4_rdata),
    .io_axi4_rvalid  (_clint_io_axi4_rvalid),
    .io_axi4_rready  (_xbar_io_clint_rready)	// @[src/main/NPC.scala:59:26]
  );	// @[src/main/NPC.scala:60:27]
  assign io_master_arid = 4'h0;	// @[src/main/NPC.scala:16:7]
  assign io_master_arlen = 8'h0;	// @[src/main/NPC.scala:16:7, :58:26, :59:26, :60:27]
  assign io_master_awid = 4'h0;	// @[src/main/NPC.scala:16:7]
  assign io_master_awlen = 8'h0;	// @[src/main/NPC.scala:16:7, :58:26, :59:26, :60:27]
  assign io_master_awburst = 2'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_arready = 1'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_rdata = 32'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_rresp = 2'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_rvalid = 1'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_rlast = 1'h1;	// @[src/main/NPC.scala:16:7]
  assign io_slave_rid = 4'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_awready = 1'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_wready = 1'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_bresp = 2'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_bvalid = 1'h0;	// @[src/main/NPC.scala:16:7]
  assign io_slave_bid = 4'h0;	// @[src/main/NPC.scala:16:7]
endmodule

