// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module IFU(	// @[src/main/core/ifu/IFU.scala:49:7]
  input         clock,	// @[src/main/core/ifu/IFU.scala:49:7]
                reset,	// @[src/main/core/ifu/IFU.scala:49:7]
  output [31:0] io_imem_araddr,	// @[src/main/core/ifu/IFU.scala:50:16]
  output        io_imem_arvalid,	// @[src/main/core/ifu/IFU.scala:50:16]
  input         io_imem_arready,	// @[src/main/core/ifu/IFU.scala:50:16]
  input  [31:0] io_imem_rdata,	// @[src/main/core/ifu/IFU.scala:50:16]
  input         io_imem_rvalid,	// @[src/main/core/ifu/IFU.scala:50:16]
  output        io_imem_rready,	// @[src/main/core/ifu/IFU.scala:50:16]
                io_pipe_in_ready,	// @[src/main/core/ifu/IFU.scala:51:21]
  input         io_pipe_in_valid,	// @[src/main/core/ifu/IFU.scala:51:21]
                io_pipe_out_ready,	// @[src/main/core/ifu/IFU.scala:51:21]
  output        io_pipe_out_valid,	// @[src/main/core/ifu/IFU.scala:51:21]
  output [31:0] io_pipe_out_bits_if2id_reg_pc,	// @[src/main/core/ifu/IFU.scala:51:21]
                io_pipe_out_bits_if2id_inst,	// @[src/main/core/ifu/IFU.scala:51:21]
  input         io_bj_valid,	// @[src/main/core/ifu/IFU.scala:52:19]
  input  [31:0] io_bj_target	// @[src/main/core/ifu/IFU.scala:52:19]
);

  reg  [31:0] reg_pc;	// @[src/main/core/ifu/IFU.scala:67:18]
  wire [31:0] pc_next = io_bj_valid ? io_bj_target : reg_pc + 32'h4;	// @[src/main/core/ifu/IFU.scala:63:23, :67:18, :70:27, :72:19]
  reg         in_ready;	// @[src/main/core/ifu/IFU.scala:110:27]
  reg         out_valid;	// @[src/main/core/ifu/IFU.scala:111:28]
  reg         arvalid;	// @[src/main/core/ifu/IFU.scala:115:26]
  reg         rready;	// @[src/main/core/ifu/IFU.scala:116:25]
  reg  [2:0]  c_state;	// @[src/main/core/ifu/IFU.scala:122:26]
  wire        AXI_R_fire = io_imem_rvalid & rready;	// @[src/main/core/ifu/IFU.scala:116:25, :127:37]
  wire [2:0]  n_state =
    c_state == 3'h4
      ? {~AXI_R_fire, 2'h0}
      : c_state == 3'h3
          ? (io_pipe_out_ready & out_valid | io_bj_valid ? 3'h0 : 3'h3)
          : c_state == 3'h2
              ? (AXI_R_fire & ~io_bj_valid
                   ? 3'h3
                   : ~AXI_R_fire & io_bj_valid
                       ? 3'h4
                       : {1'h0, ~(AXI_R_fire & io_bj_valid), 1'h0})
              : c_state == 3'h1
                  ? (arvalid & io_imem_arready ? 3'h2 : 3'h1)
                  : {2'h0,
                     c_state == 3'h0 & io_pipe_in_valid & io_imem_arready & ~io_bj_valid};	// @[src/main/core/ifu/IFU.scala:49:7, :111:28, :115:26, :122:26, :123:30, :126:31, :127:37, :129:57, :131:36, :132:{26,38}, :133:35, :137:51, :138:38, :139:38, :140:{38,72,101}, :141:{38,56}, :142:38, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock or posedge reset) begin	// @[src/main/core/ifu/IFU.scala:49:7]
    if (reset)	// @[src/main/core/ifu/IFU.scala:49:7]
      reg_pc <= 32'h30000000;	// @[src/main/core/ifu/IFU.scala:67:18]
    else if (in_ready & io_pipe_in_valid | io_bj_valid)	// @[src/main/core/ifu/IFU.scala:67:56, :110:27, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      reg_pc <= pc_next;	// @[src/main/core/ifu/IFU.scala:63:23, :67:18]
  end // always @(posedge, posedge)
  wire        _GEN = n_state == 3'h0;	// @[src/main/core/ifu/IFU.scala:123:30, :138:38, :145:20]
  wire        _GEN_0 = n_state == 3'h1;	// @[src/main/core/ifu/IFU.scala:122:26, :123:30, :145:20]
  wire        _GEN_1 = n_state == 3'h2;	// @[src/main/core/ifu/IFU.scala:123:30, :139:38, :145:20]
  wire        _GEN_2 = n_state == 3'h3;	// @[src/main/core/ifu/IFU.scala:123:30, :140:38, :145:20]
  wire        _GEN_3 = n_state == 3'h4;	// @[src/main/core/ifu/IFU.scala:123:30, :140:72, :145:20]
  wire        _GEN_4 = _GEN_1 | _GEN_2 | _GEN_3;	// @[src/main/core/ifu/IFU.scala:110:27, :145:20, :164:22, :172:22, :180:22]
  always @(posedge clock) begin	// @[src/main/core/ifu/IFU.scala:49:7]
    if (reset) begin	// @[src/main/core/ifu/IFU.scala:49:7]
      in_ready <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :110:27]
      out_valid <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :111:28]
      arvalid <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :115:26]
      rready <= 1'h0;	// @[src/main/core/ifu/IFU.scala:49:7, :116:25]
      c_state <= 3'h1;	// @[src/main/core/ifu/IFU.scala:122:26]
    end
    else begin	// @[src/main/core/ifu/IFU.scala:49:7]
      in_ready <= _GEN | ~(_GEN_0 | _GEN_4) & in_ready;	// @[src/main/core/ifu/IFU.scala:110:27, :145:20, :148:22, :156:22, :164:22, :172:22, :180:22]
      out_valid <=
        ~(_GEN | _GEN_0 | _GEN_1) & (_GEN_2 ? ~io_bj_valid : ~_GEN_3 & out_valid);	// @[src/main/core/ifu/IFU.scala:111:28, :129:57, :145:20, :149:23, :157:23, :165:23, :173:23, :181:23]
      arvalid <= ~_GEN & (_GEN_0 | ~_GEN_4 & arvalid);	// @[src/main/core/ifu/IFU.scala:110:27, :115:26, :145:20, :151:21, :159:21, :164:22, :167:21, :172:22, :175:21, :180:22, :183:21]
      rready <= ~(_GEN | _GEN_0) & (_GEN_1 | ~_GEN_2 & (_GEN_3 | rready));	// @[src/main/core/ifu/IFU.scala:116:25, :145:20, :152:20, :160:20, :168:20, :176:20, :184:20]
      c_state <= n_state;	// @[src/main/core/ifu/IFU.scala:122:26, :123:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/core/ifu/IFU.scala:49:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[src/main/core/ifu/IFU.scala:49:7]
    initial begin	// @[src/main/core/ifu/IFU.scala:49:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/core/ifu/IFU.scala:49:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/core/ifu/IFU.scala:49:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/core/ifu/IFU.scala:49:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[src/main/core/ifu/IFU.scala:49:7]
        end	// @[src/main/core/ifu/IFU.scala:49:7]
        reg_pc = _RANDOM[1'h0];	// @[src/main/core/ifu/IFU.scala:49:7, :67:18]
        in_ready = _RANDOM[1'h1][0];	// @[src/main/core/ifu/IFU.scala:49:7, :110:27]
        out_valid = _RANDOM[1'h1][1];	// @[src/main/core/ifu/IFU.scala:49:7, :110:27, :111:28]
        arvalid = _RANDOM[1'h1][2];	// @[src/main/core/ifu/IFU.scala:49:7, :110:27, :115:26]
        rready = _RANDOM[1'h1][3];	// @[src/main/core/ifu/IFU.scala:49:7, :110:27, :116:25]
        c_state = _RANDOM[1'h1][6:4];	// @[src/main/core/ifu/IFU.scala:49:7, :110:27, :122:26]
      `endif // RANDOMIZE_REG_INIT
      if (reset)	// @[src/main/core/ifu/IFU.scala:49:7]
        reg_pc = 32'h30000000;	// @[src/main/core/ifu/IFU.scala:67:18]
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/core/ifu/IFU.scala:49:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_imem_araddr = reg_pc;	// @[src/main/core/ifu/IFU.scala:49:7, :67:18]
  assign io_imem_arvalid = arvalid;	// @[src/main/core/ifu/IFU.scala:49:7, :115:26]
  assign io_imem_rready = rready;	// @[src/main/core/ifu/IFU.scala:49:7, :116:25]
  assign io_pipe_in_ready = in_ready;	// @[src/main/core/ifu/IFU.scala:49:7, :110:27]
  assign io_pipe_out_valid = out_valid;	// @[src/main/core/ifu/IFU.scala:49:7, :111:28]
  assign io_pipe_out_bits_if2id_reg_pc = reg_pc;	// @[src/main/core/ifu/IFU.scala:49:7, :67:18]
  assign io_pipe_out_bits_if2id_inst = io_imem_rdata;	// @[src/main/core/ifu/IFU.scala:49:7]
endmodule

