// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module NPC(	// @[src/main/NPC.scala:12:7]
  input clock,	// @[src/main/NPC.scala:12:7]
        reset	// @[src/main/NPC.scala:12:7]
);

  wire        _clint_arready;	// @[src/main/NPC.scala:20:23]
  wire [31:0] _clint_rdata;	// @[src/main/NPC.scala:20:23]
  wire [1:0]  _clint_rresp;	// @[src/main/NPC.scala:20:23]
  wire        _clint_rvalid;	// @[src/main/NPC.scala:20:23]
  wire        _clint_awready;	// @[src/main/NPC.scala:20:23]
  wire        _clint_wready;	// @[src/main/NPC.scala:20:23]
  wire        _clint_bvalid;	// @[src/main/NPC.scala:20:23]
  wire        _uart_arready;	// @[src/main/NPC.scala:19:22]
  wire [31:0] _uart_rdata;	// @[src/main/NPC.scala:19:22]
  wire [1:0]  _uart_rresp;	// @[src/main/NPC.scala:19:22]
  wire        _uart_rvalid;	// @[src/main/NPC.scala:19:22]
  wire        _uart_awready;	// @[src/main/NPC.scala:19:22]
  wire        _uart_wready;	// @[src/main/NPC.scala:19:22]
  wire        _uart_bvalid;	// @[src/main/NPC.scala:19:22]
  wire        _mem_arready;	// @[src/main/NPC.scala:18:21]
  wire [31:0] _mem_rdata;	// @[src/main/NPC.scala:18:21]
  wire [1:0]  _mem_rresp;	// @[src/main/NPC.scala:18:21]
  wire        _mem_rvalid;	// @[src/main/NPC.scala:18:21]
  wire        _mem_awready;	// @[src/main/NPC.scala:18:21]
  wire        _mem_wready;	// @[src/main/NPC.scala:18:21]
  wire        _mem_bvalid;	// @[src/main/NPC.scala:18:21]
  wire        _xbar_io_arb_arready;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_arb_rdata;	// @[src/main/NPC.scala:17:22]
  wire [1:0]  _xbar_io_arb_rresp;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_arb_rvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_arb_awready;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_arb_wready;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_arb_bvalid;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_sram_araddr;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_sram_arvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_sram_rready;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_sram_awaddr;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_sram_awvalid;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_sram_wdata;	// @[src/main/NPC.scala:17:22]
  wire [3:0]  _xbar_io_sram_wstrb;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_sram_wvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_sram_bready;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_uart_araddr;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_uart_arvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_uart_rready;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_uart_awaddr;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_uart_awvalid;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_uart_wdata;	// @[src/main/NPC.scala:17:22]
  wire [3:0]  _xbar_io_uart_wstrb;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_uart_wvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_uart_bready;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_clint_araddr;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_clint_arvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_clint_rready;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_clint_awaddr;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_clint_awvalid;	// @[src/main/NPC.scala:17:22]
  wire [31:0] _xbar_io_clint_wdata;	// @[src/main/NPC.scala:17:22]
  wire [3:0]  _xbar_io_clint_wstrb;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_clint_wvalid;	// @[src/main/NPC.scala:17:22]
  wire        _xbar_io_clint_bready;	// @[src/main/NPC.scala:17:22]
  wire        _arb_io_imem_arready;	// @[src/main/NPC.scala:16:21]
  wire [31:0] _arb_io_imem_rdata;	// @[src/main/NPC.scala:16:21]
  wire [1:0]  _arb_io_imem_rresp;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_imem_rvalid;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_dmem_arready;	// @[src/main/NPC.scala:16:21]
  wire [31:0] _arb_io_dmem_rdata;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_dmem_rvalid;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_dmem_awready;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_dmem_wready;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_dmem_bvalid;	// @[src/main/NPC.scala:16:21]
  wire [31:0] _arb_io_mem_araddr;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_mem_arvalid;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_mem_rready;	// @[src/main/NPC.scala:16:21]
  wire [31:0] _arb_io_mem_awaddr;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_mem_awvalid;	// @[src/main/NPC.scala:16:21]
  wire [31:0] _arb_io_mem_wdata;	// @[src/main/NPC.scala:16:21]
  wire [3:0]  _arb_io_mem_wstrb;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_mem_wvalid;	// @[src/main/NPC.scala:16:21]
  wire        _arb_io_mem_bready;	// @[src/main/NPC.scala:16:21]
  wire [31:0] _core_io_imem_araddr;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_imem_arvalid;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_imem_rready;	// @[src/main/NPC.scala:15:22]
  wire [31:0] _core_io_dmem_araddr;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_dmem_arvalid;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_dmem_rready;	// @[src/main/NPC.scala:15:22]
  wire [31:0] _core_io_dmem_awaddr;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_dmem_awvalid;	// @[src/main/NPC.scala:15:22]
  wire [31:0] _core_io_dmem_wdata;	// @[src/main/NPC.scala:15:22]
  wire [3:0]  _core_io_dmem_wstrb;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_dmem_wvalid;	// @[src/main/NPC.scala:15:22]
  wire        _core_io_dmem_bready;	// @[src/main/NPC.scala:15:22]
  Core core (	// @[src/main/NPC.scala:15:22]
    .clock           (clock),
    .reset           (reset),
    .io_imem_araddr  (_core_io_imem_araddr),
    .io_imem_arvalid (_core_io_imem_arvalid),
    .io_imem_arready (_arb_io_imem_arready),	// @[src/main/NPC.scala:16:21]
    .io_imem_rdata   (_arb_io_imem_rdata),	// @[src/main/NPC.scala:16:21]
    .io_imem_rresp   (_arb_io_imem_rresp),	// @[src/main/NPC.scala:16:21]
    .io_imem_rvalid  (_arb_io_imem_rvalid),	// @[src/main/NPC.scala:16:21]
    .io_imem_rready  (_core_io_imem_rready),
    .io_dmem_araddr  (_core_io_dmem_araddr),
    .io_dmem_arvalid (_core_io_dmem_arvalid),
    .io_dmem_arready (_arb_io_dmem_arready),	// @[src/main/NPC.scala:16:21]
    .io_dmem_rdata   (_arb_io_dmem_rdata),	// @[src/main/NPC.scala:16:21]
    .io_dmem_rvalid  (_arb_io_dmem_rvalid),	// @[src/main/NPC.scala:16:21]
    .io_dmem_rready  (_core_io_dmem_rready),
    .io_dmem_awaddr  (_core_io_dmem_awaddr),
    .io_dmem_awvalid (_core_io_dmem_awvalid),
    .io_dmem_awready (_arb_io_dmem_awready),	// @[src/main/NPC.scala:16:21]
    .io_dmem_wdata   (_core_io_dmem_wdata),
    .io_dmem_wstrb   (_core_io_dmem_wstrb),
    .io_dmem_wvalid  (_core_io_dmem_wvalid),
    .io_dmem_wready  (_arb_io_dmem_wready),	// @[src/main/NPC.scala:16:21]
    .io_dmem_bvalid  (_arb_io_dmem_bvalid),	// @[src/main/NPC.scala:16:21]
    .io_dmem_bready  (_core_io_dmem_bready)
  );
  Arbiter arb (	// @[src/main/NPC.scala:16:21]
    .clock           (clock),
    .reset           (reset),
    .io_imem_araddr  (_core_io_imem_araddr),	// @[src/main/NPC.scala:15:22]
    .io_imem_arvalid (_core_io_imem_arvalid),	// @[src/main/NPC.scala:15:22]
    .io_imem_arready (_arb_io_imem_arready),
    .io_imem_rdata   (_arb_io_imem_rdata),
    .io_imem_rresp   (_arb_io_imem_rresp),
    .io_imem_rvalid  (_arb_io_imem_rvalid),
    .io_imem_rready  (_core_io_imem_rready),	// @[src/main/NPC.scala:15:22]
    .io_dmem_araddr  (_core_io_dmem_araddr),	// @[src/main/NPC.scala:15:22]
    .io_dmem_arvalid (_core_io_dmem_arvalid),	// @[src/main/NPC.scala:15:22]
    .io_dmem_arready (_arb_io_dmem_arready),
    .io_dmem_rdata   (_arb_io_dmem_rdata),
    .io_dmem_rvalid  (_arb_io_dmem_rvalid),
    .io_dmem_rready  (_core_io_dmem_rready),	// @[src/main/NPC.scala:15:22]
    .io_dmem_awaddr  (_core_io_dmem_awaddr),	// @[src/main/NPC.scala:15:22]
    .io_dmem_awvalid (_core_io_dmem_awvalid),	// @[src/main/NPC.scala:15:22]
    .io_dmem_awready (_arb_io_dmem_awready),
    .io_dmem_wdata   (_core_io_dmem_wdata),	// @[src/main/NPC.scala:15:22]
    .io_dmem_wstrb   (_core_io_dmem_wstrb),	// @[src/main/NPC.scala:15:22]
    .io_dmem_wvalid  (_core_io_dmem_wvalid),	// @[src/main/NPC.scala:15:22]
    .io_dmem_wready  (_arb_io_dmem_wready),
    .io_dmem_bvalid  (_arb_io_dmem_bvalid),
    .io_dmem_bready  (_core_io_dmem_bready),	// @[src/main/NPC.scala:15:22]
    .io_mem_araddr   (_arb_io_mem_araddr),
    .io_mem_arvalid  (_arb_io_mem_arvalid),
    .io_mem_arready  (_xbar_io_arb_arready),	// @[src/main/NPC.scala:17:22]
    .io_mem_rdata    (_xbar_io_arb_rdata),	// @[src/main/NPC.scala:17:22]
    .io_mem_rresp    (_xbar_io_arb_rresp),	// @[src/main/NPC.scala:17:22]
    .io_mem_rvalid   (_xbar_io_arb_rvalid),	// @[src/main/NPC.scala:17:22]
    .io_mem_rready   (_arb_io_mem_rready),
    .io_mem_awaddr   (_arb_io_mem_awaddr),
    .io_mem_awvalid  (_arb_io_mem_awvalid),
    .io_mem_awready  (_xbar_io_arb_awready),	// @[src/main/NPC.scala:17:22]
    .io_mem_wdata    (_arb_io_mem_wdata),
    .io_mem_wstrb    (_arb_io_mem_wstrb),
    .io_mem_wvalid   (_arb_io_mem_wvalid),
    .io_mem_wready   (_xbar_io_arb_wready),	// @[src/main/NPC.scala:17:22]
    .io_mem_bvalid   (_xbar_io_arb_bvalid),	// @[src/main/NPC.scala:17:22]
    .io_mem_bready   (_arb_io_mem_bready)
  );
  Xbar xbar (	// @[src/main/NPC.scala:17:22]
    .clock            (clock),
    .reset            (reset),
    .io_arb_araddr    (_arb_io_mem_araddr),	// @[src/main/NPC.scala:16:21]
    .io_arb_arvalid   (_arb_io_mem_arvalid),	// @[src/main/NPC.scala:16:21]
    .io_arb_arready   (_xbar_io_arb_arready),
    .io_arb_rdata     (_xbar_io_arb_rdata),
    .io_arb_rresp     (_xbar_io_arb_rresp),
    .io_arb_rvalid    (_xbar_io_arb_rvalid),
    .io_arb_rready    (_arb_io_mem_rready),	// @[src/main/NPC.scala:16:21]
    .io_arb_awaddr    (_arb_io_mem_awaddr),	// @[src/main/NPC.scala:16:21]
    .io_arb_awvalid   (_arb_io_mem_awvalid),	// @[src/main/NPC.scala:16:21]
    .io_arb_awready   (_xbar_io_arb_awready),
    .io_arb_wdata     (_arb_io_mem_wdata),	// @[src/main/NPC.scala:16:21]
    .io_arb_wstrb     (_arb_io_mem_wstrb),	// @[src/main/NPC.scala:16:21]
    .io_arb_wvalid    (_arb_io_mem_wvalid),	// @[src/main/NPC.scala:16:21]
    .io_arb_wready    (_xbar_io_arb_wready),
    .io_arb_bvalid    (_xbar_io_arb_bvalid),
    .io_arb_bready    (_arb_io_mem_bready),	// @[src/main/NPC.scala:16:21]
    .io_sram_araddr   (_xbar_io_sram_araddr),
    .io_sram_arvalid  (_xbar_io_sram_arvalid),
    .io_sram_arready  (_mem_arready),	// @[src/main/NPC.scala:18:21]
    .io_sram_rdata    (_mem_rdata),	// @[src/main/NPC.scala:18:21]
    .io_sram_rresp    (_mem_rresp),	// @[src/main/NPC.scala:18:21]
    .io_sram_rvalid   (_mem_rvalid),	// @[src/main/NPC.scala:18:21]
    .io_sram_rready   (_xbar_io_sram_rready),
    .io_sram_awaddr   (_xbar_io_sram_awaddr),
    .io_sram_awvalid  (_xbar_io_sram_awvalid),
    .io_sram_awready  (_mem_awready),	// @[src/main/NPC.scala:18:21]
    .io_sram_wdata    (_xbar_io_sram_wdata),
    .io_sram_wstrb    (_xbar_io_sram_wstrb),
    .io_sram_wvalid   (_xbar_io_sram_wvalid),
    .io_sram_wready   (_mem_wready),	// @[src/main/NPC.scala:18:21]
    .io_sram_bvalid   (_mem_bvalid),	// @[src/main/NPC.scala:18:21]
    .io_sram_bready   (_xbar_io_sram_bready),
    .io_uart_araddr   (_xbar_io_uart_araddr),
    .io_uart_arvalid  (_xbar_io_uart_arvalid),
    .io_uart_arready  (_uart_arready),	// @[src/main/NPC.scala:19:22]
    .io_uart_rdata    (_uart_rdata),	// @[src/main/NPC.scala:19:22]
    .io_uart_rresp    (_uart_rresp),	// @[src/main/NPC.scala:19:22]
    .io_uart_rvalid   (_uart_rvalid),	// @[src/main/NPC.scala:19:22]
    .io_uart_rready   (_xbar_io_uart_rready),
    .io_uart_awaddr   (_xbar_io_uart_awaddr),
    .io_uart_awvalid  (_xbar_io_uart_awvalid),
    .io_uart_awready  (_uart_awready),	// @[src/main/NPC.scala:19:22]
    .io_uart_wdata    (_xbar_io_uart_wdata),
    .io_uart_wstrb    (_xbar_io_uart_wstrb),
    .io_uart_wvalid   (_xbar_io_uart_wvalid),
    .io_uart_wready   (_uart_wready),	// @[src/main/NPC.scala:19:22]
    .io_uart_bvalid   (_uart_bvalid),	// @[src/main/NPC.scala:19:22]
    .io_uart_bready   (_xbar_io_uart_bready),
    .io_clint_araddr  (_xbar_io_clint_araddr),
    .io_clint_arvalid (_xbar_io_clint_arvalid),
    .io_clint_arready (_clint_arready),	// @[src/main/NPC.scala:20:23]
    .io_clint_rdata   (_clint_rdata),	// @[src/main/NPC.scala:20:23]
    .io_clint_rresp   (_clint_rresp),	// @[src/main/NPC.scala:20:23]
    .io_clint_rvalid  (_clint_rvalid),	// @[src/main/NPC.scala:20:23]
    .io_clint_rready  (_xbar_io_clint_rready),
    .io_clint_awaddr  (_xbar_io_clint_awaddr),
    .io_clint_awvalid (_xbar_io_clint_awvalid),
    .io_clint_awready (_clint_awready),	// @[src/main/NPC.scala:20:23]
    .io_clint_wdata   (_xbar_io_clint_wdata),
    .io_clint_wstrb   (_xbar_io_clint_wstrb),
    .io_clint_wvalid  (_xbar_io_clint_wvalid),
    .io_clint_wready  (_clint_wready),	// @[src/main/NPC.scala:20:23]
    .io_clint_bvalid  (_clint_bvalid),	// @[src/main/NPC.scala:20:23]
    .io_clint_bready  (_xbar_io_clint_bready)
  );
  Mem mem (	// @[src/main/NPC.scala:18:21]
    .clk     (clock),
    .rst     (reset),
    .araddr  (_xbar_io_sram_araddr),	// @[src/main/NPC.scala:17:22]
    .arvalid (_xbar_io_sram_arvalid),	// @[src/main/NPC.scala:17:22]
    .arready (_mem_arready),
    .rdata   (_mem_rdata),
    .rresp   (_mem_rresp),
    .rvalid  (_mem_rvalid),
    .rready  (_xbar_io_sram_rready),	// @[src/main/NPC.scala:17:22]
    .awaddr  (_xbar_io_sram_awaddr),	// @[src/main/NPC.scala:17:22]
    .awvalid (_xbar_io_sram_awvalid),	// @[src/main/NPC.scala:17:22]
    .awready (_mem_awready),
    .wdata   (_xbar_io_sram_wdata),	// @[src/main/NPC.scala:17:22]
    .wstrb   (_xbar_io_sram_wstrb),	// @[src/main/NPC.scala:17:22]
    .wvalid  (_xbar_io_sram_wvalid),	// @[src/main/NPC.scala:17:22]
    .wready  (_mem_wready),
    .bresp   (/* unused */),
    .bvalid  (_mem_bvalid),
    .bready  (_xbar_io_sram_bready)	// @[src/main/NPC.scala:17:22]
  );
  Uart uart (	// @[src/main/NPC.scala:19:22]
    .clk     (clock),
    .rst     (reset),
    .araddr  (_xbar_io_uart_araddr),	// @[src/main/NPC.scala:17:22]
    .arvalid (_xbar_io_uart_arvalid),	// @[src/main/NPC.scala:17:22]
    .arready (_uart_arready),
    .rdata   (_uart_rdata),
    .rresp   (_uart_rresp),
    .rvalid  (_uart_rvalid),
    .rready  (_xbar_io_uart_rready),	// @[src/main/NPC.scala:17:22]
    .awaddr  (_xbar_io_uart_awaddr),	// @[src/main/NPC.scala:17:22]
    .awvalid (_xbar_io_uart_awvalid),	// @[src/main/NPC.scala:17:22]
    .awready (_uart_awready),
    .wdata   (_xbar_io_uart_wdata),	// @[src/main/NPC.scala:17:22]
    .wstrb   (_xbar_io_uart_wstrb),	// @[src/main/NPC.scala:17:22]
    .wvalid  (_xbar_io_uart_wvalid),	// @[src/main/NPC.scala:17:22]
    .wready  (_uart_wready),
    .bresp   (/* unused */),
    .bvalid  (_uart_bvalid),
    .bready  (_xbar_io_uart_bready)	// @[src/main/NPC.scala:17:22]
  );
  Clint clint (	// @[src/main/NPC.scala:20:23]
    .clk     (clock),
    .rst     (reset),
    .araddr  (_xbar_io_clint_araddr),	// @[src/main/NPC.scala:17:22]
    .arvalid (_xbar_io_clint_arvalid),	// @[src/main/NPC.scala:17:22]
    .arready (_clint_arready),
    .rdata   (_clint_rdata),
    .rresp   (_clint_rresp),
    .rvalid  (_clint_rvalid),
    .rready  (_xbar_io_clint_rready),	// @[src/main/NPC.scala:17:22]
    .awaddr  (_xbar_io_clint_awaddr),	// @[src/main/NPC.scala:17:22]
    .awvalid (_xbar_io_clint_awvalid),	// @[src/main/NPC.scala:17:22]
    .awready (_clint_awready),
    .wdata   (_xbar_io_clint_wdata),	// @[src/main/NPC.scala:17:22]
    .wstrb   (_xbar_io_clint_wstrb),	// @[src/main/NPC.scala:17:22]
    .wvalid  (_xbar_io_clint_wvalid),	// @[src/main/NPC.scala:17:22]
    .wready  (_clint_wready),
    .bresp   (/* unused */),
    .bvalid  (_clint_bvalid),
    .bready  (_xbar_io_clint_bready)	// @[src/main/NPC.scala:17:22]
  );
endmodule

